const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a << shift;
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn adler32_step(adler: i64, b: i64) i64 {
    var s1: i64 = 0;
    var s2: i64 = 0;

  s1 = adler & 65535;
  s2 = _lia_shr(adler, 16) & 65535;
  s1 = _lia_mod(s1 + b, 65521);
  s2 = _lia_mod(s2 + s1, 65521);
  return (_lia_shl(s2, 16) | s1) & 4294967295;

}

pub fn adler32_combine(adler1: i64, adler2: i64, len2: i64) i64 {
    var BASE: i64 = 0;
    var rem: i64 = 0;
    var a1: i64 = 0;
    var a2: i64 = 0;
    var b1: i64 = 0;
    var b2: i64 = 0;
    var s1: i64 = 0;
    var s2: i64 = 0;

  BASE = 65521;
  rem = _lia_mod(len2, BASE);
  a1 = adler1 & 65535;
  a2 = _lia_shr(adler1, 16) & 65535;
  b1 = adler2 & 65535;
  b2 = _lia_shr(adler2, 16) & 65535;

  s1 = _lia_mod(a1 + b1 + BASE - 1, BASE);
  s2 = _lia_mod(a2 + b2 + BASE - 1 + (rem * (a1 + BASE - 1)), BASE);

  return (_lia_shl(s2, 16) | s1) & 4294967295;

}

pub fn test_adler32_vector() i64 {
    var adler: i64 = 0;

  // Test with ASCII "Wikipedia": [87, 105, 107, 105, 112, 101, 100, 105, 97]
  // Standard Adler32 for "Wikipedia" is 0x11E60398 (300286872)
  adler = 1;
  adler = adler32_step(adler, 87);
  adler = adler32_step(adler, 105);
  adler = adler32_step(adler, 107);
  adler = adler32_step(adler, 105);
  adler = adler32_step(adler, 112);
  adler = adler32_step(adler, 101);
  adler = adler32_step(adler, 100);
  adler = adler32_step(adler, 105);
  adler = adler32_step(adler, 97);

  if (adler != 300286872) { return 0 ;}
  return 1;

}

