const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn poly1305_l2(r0: i64, r1: i64, r2: i64, h0: i64, h1: i64, b0: i64, b1: i64, b2: i64, b3: i64, b4: i64, b5: i64, b6: i64, b7: i64) i64 {
    var s1: i64 = 0;
    var s2: i64 = 0;
    var t0: i64 = 0;
    var t1: i64 = 0;
    var d0: i64 = 0;
    var d1: i64 = 0;
    var d2: i64 = 0;
    var c: i64 = 0;

  s1 = r1 * 5;
  s2 = r2 * 5;
  t0 = b0 + (_lia_shl(b1 ,  8)) + (_lia_shl(b2 ,  16)) + (_lia_shl(b3 ,  24));
  t1 = b4 + (_lia_shl(b5 ,  8)) + (_lia_shl(b6 ,  16)) + (_lia_shl(b7 ,  24));
  h0 = h0 + (t0 & 67108863);
  h1 = h1 + ((_lia_shr(t0 ,  2)) & 67108863);
  d0 = (h0 * r0) + (h1 * s2);
  d1 = (h0 * r1) + (h1 * r0);
  d2 = (h0 * r2) + (h1 * s1);
  c = _lia_shr(d0 ,  26);
  h0 = d0 & 67108863;
  d1 = d1 + c;
  c = _lia_shr(d1 ,  26);
  h1 = d1 & 67108863;
  d2 = d2 + c;
  c = _lia_shr(d2 ,  26);
  h0 = h0 + c * 5;
  c = _lia_shr(h0 ,  26);
  h0 = h0 & 67108863;
  h1 = h1 + c;
  return h0 + (_lia_shl(h1 ,  26));

}

pub fn test_aead_poly1305_vector() i64 {

  // poly1305_l2(r0,r1,r2,h0,h1,b0..b7)->h0|(h1<<26), from gcc oracle else if (poly1305_l2(1, 0, 0, 0, 0, 67, 114, 121, 112, 116, 111, 103, 114) != 133531614933571) { return 0 ;}
  if (poly1305_l2(1, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255) != 4503599627370495) { return 0 ;}
  if (poly1305_l2(139005364, 14005001, 1, 12345, 67890, 1, 2, 3, 4, 5, 6, 7, 8) != 3121720217052711) { return 0 ;}
  if (poly1305_l2(16479973, 13577653, 14205021, 0, 0, 111, 66, 71, 70, 0, 0, 0, 0) != 2924818195641624) { return 0 ;}
  if (poly1305_l2(139005364, 14005001, 1, 1, 2, 255, 0, 0, 4, 3, 16, 0, 0) != 279375329449360) { return 0 ;}
  return 1;

}

