const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn alac_decorrelate_stereo(a: i64, b: i64, weight: i64, shift: i64) i64 {

  a = a - (_lia_shr((b * weight) ,  shift));
  b = b + a;
  return b;

}

pub fn flac_lpc_restore4(c0: i64, c1: i64, c2: i64, c3: i64, d0: i64, d1: i64, d2: i64, d3: i64, residual: i64, qlevel: i64) i64 {
    var sum: i64 = 0;

  sum = 0;
  sum = sum + (c0 * d0);
  sum = sum + (c1 * d1);
  sum = sum + (c2 * d2);
  sum = sum + (c3 * d3);
  return residual + (_lia_shr(sum ,  qlevel));

}

pub fn test_alac_flac_vector() i64 {

  // ALAC decorrelate_stereo (a,b,weight,shift)->b  vs gcc oracle else if (alac_decorrelate_stereo(100, 50, 3, 4) != 141) { return 0 ;}
  if (alac_decorrelate_stereo(-100, 50, 3, 4) != -59) { return 0 ;}
  if (alac_decorrelate_stereo(7, -9, 2, 1) != 7) { return 0 ;}
  if (alac_decorrelate_stereo(0, 1000000, 9, 4) != 437500) { return 0 ;}
  if (alac_decorrelate_stereo(-128, 127, 255, 7) != -254) { return 0 ;}
  // FLAC flac_lpc_restore4 (c0..c3,d0..d3,residual,qlevel)->out vs gcc oracle else if (flac_lpc_restore4(2, -1, 0, 0, 100, 200, 150, 300, 5, 1) != 5) { return 0 ;}
  if (flac_lpc_restore4(-2, 1, 0, 0, -100, -200, -150, 300, -5, 2) != -5) { return 0 ;}
  if (flac_lpc_restore4(10, -5, 2, -1, 1000, 2000, -1500, 3000, 17, 0) != -5983) { return 0 ;}
  if (flac_lpc_restore4(1, 1, 1, 1, 1, 2, 3, 4, -10, 4) != -10) { return 0 ;}
  if (flac_lpc_restore4(-100, 50, -25, 12, 7, -7, 7, -7, 123, 8) != 117) { return 0 ;}
  if (flac_lpc_restore4(0, 0, 0, 0, 99, 88, 77, 66, -1, 3) != -1) { return 0 ;}
  return 1;

}

