const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a << shift;
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn rotr32(x: i64, n: i64) i64 {
    var w: i64 = 0;

  w = x & 4294967295;
  return ((_lia_shr(w, n)) | (_lia_shl(w, 32 - n))) & 4294967295;

}

pub fn blake3_g(a: i64, b: i64, c: i64, d: i64, mx: i64, my: i64, sel: i64) i64 {
    var oa: i64 = 0;
    var od: i64 = 0;
    var oc: i64 = 0;
    var ob: i64 = 0;

  oa = (a + b + mx) & 4294967295;
  od = rotr32(d  ^  oa, 16);
  oc = (c + od) & 4294967295;
  ob = rotr32(b  ^  oc, 12);
  oa = (oa + ob + my) & 4294967295;
  od = rotr32(od  ^  oa, 8);
  oc = (oc + od) & 4294967295;
  ob = rotr32(ob  ^  oc, 7);

  if (sel == 0) { return oa ;}
  if (sel == 1) { return ob ;}
  if (sel == 2) { return oc ;}
  return od;

}

pub fn test_blake3_g() i64 {
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var d: i64 = 0;

  // Initial IV constants from BLAKE3 spec
  // IV[0] = 0x6A09E667 (1779033703)
  // IV[1] = 0xBB67AE85 (3144134277)
  // IV[2] = 0x3C6EF372 (1013904242)
  // IV[3] = 0xA54FF53A (2773480762)
  // mx = 1, my = 2
  a = blake3_g(1779033703, 3144134277, 1013904242, 2773480762, 1, 2, 0);
  b = blake3_g(1779033703, 3144134277, 1013904242, 2773480762, 1, 2, 1);
  c = blake3_g(1779033703, 3144134277, 1013904242, 2773480762, 1, 2, 2);
  d = blake3_g(1779033703, 3144134277, 1013904242, 2773480762, 1, 2, 3);

  if (a != 4173588236  or  b != 336010164  or  c != 3504310295  or  d != 848893031) { return 0 ;}
  return 1;

}

