const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn brotli_next_table_bits(c0: i64, c1: i64, c2: i64, len: i64, root_bits: i64) i64 {
    var left: i64 = 0;
    var done: i64 = 0;
    var llen: i64 = 0;

  left = _lia_shl(1 ,  (len - root_bits));
  done = 0;
  llen = len;
  while (llen < 15  and  done == 0) {
  if (llen == 0) {   left = left - c0;
 }
  if (llen == 1) {   left = left - c1;
 }
  if (llen == 2) {   left = left - c2;
 }
  if (left <= 0) {   done = 1;
 }
  if (left > 0) {   llen = llen + 1;
  left = _lia_shl(left ,  1);
 }
  }
  return llen - root_bits;

}

pub fn test_brotli_huffman_vector() i64 {

  // brotli_next_table_bits(c0,c1,c2,len,root_bits)->out, from gcc oracle
  // on transpiled scalar C: 13 14 13 0 14 13 / 13 12 13 11
  if (brotli_next_table_bits(1, 0, 0, 3, 2) != 13) { return 0 ;}
  if (brotli_next_table_bits(0, 2, 0, 2, 1) != 14) { return 0 ;}
  if (brotli_next_table_bits(3, 0, 0, 4, 2) != 13) { return 0 ;}
  if (brotli_next_table_bits(1, 1, 1, 1, 1) != 0) { return 0 ;}
  if (brotli_next_table_bits(4, 0, 0, 2, 1) != 14) { return 0 ;}
  if (brotli_next_table_bits(0, 0, 0, 3, 2) != 13) { return 0 ;}
  if (brotli_next_table_bits(2, 1, 0, 5, 2) != 13) { return 0 ;}
  if (brotli_next_table_bits(1, 1, 0, 6, 3) != 12) { return 0 ;}
  if (brotli_next_table_bits(7, 0, 0, 8, 2) != 13) { return 0 ;}
  if (brotli_next_table_bits(0, 1, 2, 7, 4) != 11) { return 0 ;}
  return 1;

}

