const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn brotli_mask_bits(val: i64, n: i64) i64 {
    var mask: i64 = 0;

  mask = (_lia_shl(1, n) - 1) & 4294967295;
  return (val & mask);

}

pub fn brotli_fill_byte(val: i64, new_byte: i64, bits_in: i64) i64 {
    var b: i64 = 0;
    var shifted: i64 = 0;

  b = new_byte & 255;
  shifted = _lia_shl(b, bits_in) & 4294967295;
  return (val | shifted);

}

pub fn brotli_drop_bits(val: i64, n: i64) i64 {

  return (_lia_ushr(val, n));

}

pub fn test_brotli_vector() i64 {
    var w: i64 = 0;
    var peek4: i64 = 0;
    var w_dropped: i64 = 0;

  // Test filling byte 0xAB (171) at offset 0 -> 171
  // Fill byte 0xCD (205) at offset 8 -> 171 | (205 << 8) = 171 | 52480 = 52651 (0xCDAB)
  w = brotli_fill_byte(0, 171, 0);
  w = brotli_fill_byte(w, 205, 8);

  // Peek 4 bits -> 0xAB & 0xF = 11 (0xB)
  peek4 = brotli_mask_bits(w, 4);

  // Drop 4 bits -> 0xCDA = 3290
  w_dropped = brotli_drop_bits(w, 4);

  if (w != 52651) { return 0 ;}
  if (peek4 != 11) { return 0 ;}
  if (w_dropped != 3290) { return 0 ;}
  return 1;

}

