const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a << shift;
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn rotr32(x: i64, n: i64) i64 {
    var w: i64 = 0;

  w = x & 4294967295;
  return ((_lia_shr(w, n)) | (_lia_shl(w, 32 - n))) & 4294967295;

}

pub fn rotl32(x: i64, n: i64) i64 {
    var w: i64 = 0;

  w = x & 4294967295;
  return ((_lia_shl(w, n)) | (_lia_shr(w, 32 - n))) & 4294967295;

}

pub fn chacha_qr(a: i64, b: i64, c: i64, d: i64, sel: i64) i64 {
    var oa: i64 = 0;
    var od: i64 = 0;
    var oc: i64 = 0;
    var ob: i64 = 0;

  oa = (a + b) & 4294967295;
  od = rotl32(d  ^  oa, 16);
  oc = (c + od) & 4294967295;
  ob = rotl32(b  ^  oc, 12);
  oa = (oa + ob) & 4294967295;
  od = rotl32(od  ^  oa, 8);
  oc = (oc + od) & 4294967295;
  ob = rotl32(ob  ^  oc, 7);

  if (sel == 0) { return oa ;}
  if (sel == 1) { return ob ;}
  if (sel == 2) { return oc ;}
  return od;

}

pub fn test_chacha_rfc_vector() i64 {
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var d: i64 = 0;

  // Test vector from RFC 8439 Section 2.1.1:
  // a = 0x11111111, b = 0x01020304, c = 0x9b8d6f43, d = 0x01234567
  // Expected after QR:
  // a = 0xea2a92f4, b = 0xcb1cf8ce, c = 0x4581472e, d = 0x5881c4bb
  a = chacha_qr(286331153, 16909060, 2609737539, 19088743, 0);
  b = chacha_qr(286331153, 16909060, 2609737539, 19088743, 1);
  c = chacha_qr(286331153, 16909060, 2609737539, 19088743, 2);
  d = chacha_qr(286331153, 16909060, 2609737539, 19088743, 3);

  if (a != 3928658676  or  b != 3407673550  or  c != 1166100270  or  d != 1484899515) { return 0 ;}
  return 1;

}

