const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn cswap_limb(swap_bit: i64, a: i64, b: i64, sel: i64) i64 {
    var bit: i64 = 0;
    var mask: i64 = 0;
    var diff: i64 = 0;
    var na: i64 = 0;
    var nb: i64 = 0;

  // mask is -1 if swap_bit == 1, 0 if swap_bit == 0
  bit = swap_bit & 1;
  mask = 0 - bit;
  diff = mask & (a  ^  b);
  na = a  ^  diff;
  nb = b  ^  diff;

  if (sel == 0) { return na ;}
  return nb;

}

pub fn test_cswap_vector() i64 {
    var no_a: i64 = 0;
    var no_b: i64 = 0;
    var sw_a: i64 = 0;
    var sw_b: i64 = 0;

  // Test with swap = 0 (no change): a=100, b=200 -> na=100, nb=200
  no_a = cswap_limb(0, 100, 200, 0);
  no_b = cswap_limb(0, 100, 200, 1);

  // Test with swap = 1 (swapped): a=100, b=200 -> na=200, nb=100
  sw_a = cswap_limb(1, 100, 200, 0);
  sw_b = cswap_limb(1, 100, 200, 1);

  if (no_a != 100) { return 0 ;}
  if (no_b != 200) { return 0 ;}
  if (sw_a != 200) { return 0 ;}
  if (sw_b != 100) { return 0 ;}
  return 1;

}

