const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn morton_spread(v_in: i64) i64 {
    var w: i64 = 0;

  w = v_in & 4294967295;
  w = (w | _lia_shl(w, 16)) & 281470681808895;
  w = (w | _lia_shl(w, 8))  & 71777214294589695;
  w = (w | _lia_shl(w, 4))  & 1085102592571150095;
  w = (w | _lia_shl(w, 2))  & 3689348814741910323;
  w = (w | _lia_shl(w, 1))  & 6148914691236517205;
  return w;

}

pub fn morton2d_encode(x: i64, y: i64) i64 {
    var sx: i64 = 0;
    var sy: i64 = 0;

  sx = morton_spread(x);
  sy = morton_spread(y);
  return (sx | _lia_shl(sy, 1));

}

pub fn test_morton_vector() i64 {
    var code: i64 = 0;

  // Test coordinate x = 5 (0b101), y = 9 (0b1001)
  // Expected bit interleave:
  // x: _ 1 _ 0 _ 1
  // y: 1 _ 0 _ 0 _ 1
  // interleave = 0b10010011 = 147
  code = morton2d_encode(5, 9);
  if (code != 147) { return 0 ;}
  return 1;

}

