const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn philox4x32_round(x0: i64, x1: i64, x2: i64, x3: i64, k0: i64, k1: i64, sel: i64) i64 {
    var w0: i64 = 0;
    var w2: i64 = 0;
    var prod0: i64 = 0;
    var hi0: i64 = 0;
    var lo0: i64 = 0;
    var prod1: i64 = 0;
    var hi1: i64 = 0;
    var lo1: i64 = 0;
    var nx0: i64 = 0;
    var nx1: i64 = 0;
    var nx2: i64 = 0;
    var nx3: i64 = 0;

  w0 = x0 & 4294967295;
  w2 = x2 & 4294967295;
  prod0 = w0 * 3528531795;
  hi0 = _lia_ushr(prod0, 32) & 4294967295;
  lo0 = prod0 & 4294967295;

  prod1 = w2 * 3449695575;
  hi1 = _lia_ushr(prod1, 32) & 4294967295;
  lo1 = prod1 & 4294967295;

  nx0 = (hi1  ^  x1  ^  k0) & 4294967295;
  nx1 = lo1;
  nx2 = (hi0  ^  x3  ^  k1) & 4294967295;
  nx3 = lo0;

  if (sel == 0) { return nx0 ;}
  if (sel == 1) { return nx1 ;}
  if (sel == 2) { return nx2 ;}
  return nx3;

}

pub fn test_philox_vector() i64 {
    var r0: i64 = 0;
    var r1: i64 = 0;
    var r2: i64 = 0;
    var r3: i64 = 0;

  r0 = philox4x32_round(1, 2, 3, 4, 10, 20, 0);
  r1 = philox4x32_round(1, 2, 3, 4, 10, 20, 1);
  r2 = philox4x32_round(1, 2, 3, 4, 10, 20, 2);
  r3 = philox4x32_round(1, 2, 3, 4, 10, 20, 3);

  if (r0 != 10) { return 0 ;}
  if (r1 != 1759152133) { return 0 ;}
  if (r2 != 16) { return 0 ;}
  if (r3 != 3528531795) { return 0 ;}
  return 1;

}

