const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn zigzag_encode32(n: i64) i64 {

  return (_lia_shl(n, 1) ^ _lia_shr(n, 31)) & 4294967295;

}

pub fn zigzag_decode32(n: i64) i64 {
    var v: i64 = 0;
    var lsb: i64 = 0;
    var mask: i64 = 0;

  v = n & 4294967295;
  lsb = v & 1;
  mask = 0;
  if (lsb == 1) { mask = 4294967295; }
  return (_lia_ushr(v, 1) ^ mask) & 4294967295;

}

pub fn zigzag_encode64(n: i64) i64 {

  return (_lia_shl(n, 1) ^ _lia_shr(n, 63));

}

pub fn varint_tag7(v: i64) i64 {

  return (v & 127) | 128;

}

pub fn test_protobuf_vectors() i64 {
    var z_neg1: i64 = 0;
    var d_neg1: i64 = 0;
    var z_pos1: i64 = 0;
    var d_pos1: i64 = 0;
    var tag: i64 = 0;

  // Test -1: zigzag_encode32(-1) = 1, zigzag_decode32(1) = 0xFFFFFFFF (4294967295)
  // Test 1: zigzag_encode32(1) = 2, zigzag_decode32(2) = 1
  z_neg1 = zigzag_encode32(-1);
  d_neg1 = zigzag_decode32(1);
  z_pos1 = zigzag_encode32(1);
  d_pos1 = zigzag_decode32(2);

  if (z_neg1 != 1) { return 0 ;}
  if (d_neg1 != 4294967295) { return 0 ;}
  if (z_pos1 != 2) { return 0 ;}
  if (d_pos1 != 1) { return 0 ;}

  // Test varint tag on 300 (0x12c): first byte = (300 & 127) | 128 = 44 | 128 = 172 (0xAC)
  tag = varint_tag7(300);
  if (tag != 172) { return 0 ;}
  return 1;

}

