const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn rotl64(x: i64, b: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = x;
  s = b & 63;
  return (_lia_shl(w, s)) | (_lia_ushr(w, 64 - s));

}

pub fn sipround(v0_in: i64, v1_in: i64, v2_in: i64, v3_in: i64, sel: i64) i64 {
    var v0: i64 = 0;
    var v1: i64 = 0;
    var v2: i64 = 0;
    var v3: i64 = 0;

  v0 = v0_in + v1_in;
  v1 = rotl64(v1_in, 13)  ^  v0;
  v0 = rotl64(v0, 32);

  v2 = v2_in + v3_in;
  v3 = rotl64(v3_in, 16)  ^  v2;

  v0 = v0 + v3;
  v3 = rotl64(v3, 21)  ^  v0;

  v2 = v2 + v1;
  v1 = rotl64(v1, 17)  ^  v2;
  v2 = rotl64(v2, 32);

  if (sel == 0) { return v0 ;}
  if (sel == 1) { return v1 ;}
  if (sel == 2) { return v2 ;}
  return v3;

}

pub fn test_sipround_vectors() i64 {
    var r0: i64 = 0;
    var r1: i64 = 0;
    var r2: i64 = 0;
    var r3: i64 = 0;

  // Initial SipHash-2-4 state with zero key
  // v0 = 0x736f6d6570736575ULL (8317987319222330741)
  // v1 = 0x646f72616e646f6dULL (7237222888777715565)
  // v2 = 0x6c7967656e657261ULL (7816434079848116833)
  // v3 = 0x7465646279746573ULL (8387220255154660723)
  r0 = sipround(8317987319222330741, 7237222888777715565, 7816434079848116833, 8387220255154660723, 0);
  r1 = sipround(8317987319222330741, 7237222888777715565, 7816434079848116833, 8387220255154660723, 1);
  r2 = sipround(8317987319222330741, 7237222888777715565, 7816434079848116833, 8387220255154660723, 2);
  r3 = sipround(8317987319222330741, 7237222888777715565, 7816434079848116833, 8387220255154660723, 3);

  if (r0 != 7718041194505935093  or  r1 != -6345287271303893494  or  r2 != -4268866800948359747  or  r3 != 9015346770765090660) { return 0 ;}
  return 1;

}

