const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn vp8_dct_row_out0(ip0: i64, ip1: i64, ip2: i64, ip3: i64) i64 {
    var a1: i64 = 0;
    var b1: i64 = 0;

  a1 = (ip0 + ip3) * 8;
  b1 = (ip1 + ip2) * 8;
  return a1 + b1;

}

pub fn vp8_dct_row_out1(ip0: i64, ip1: i64, ip2: i64, ip3: i64) i64 {
    var a1: i64 = 0;
    var c1: i64 = 0;
    var d1: i64 = 0;

  a1 = (ip0 + ip3) * 8;
  c1 = (ip1 - ip2) * 8;
  d1 = (ip0 - ip3) * 8;
  return _lia_shr((c1 * 2217 + d1 * 5352 + 14500) ,  12);

}

pub fn vp8_dct_row_out2(ip0: i64, ip1: i64, ip2: i64, ip3: i64) i64 {
    var a1: i64 = 0;
    var b1: i64 = 0;

  a1 = (ip0 + ip3) * 8;
  b1 = (ip1 + ip2) * 8;
  return a1 - b1;

}

pub fn vp8_dct_row_out3(ip0: i64, ip1: i64, ip2: i64, ip3: i64) i64 {
    var d1: i64 = 0;
    var c1: i64 = 0;

  d1 = (ip0 - ip3) * 8;
  c1 = (ip1 - ip2) * 8;
  return _lia_shr((d1 * 2217 - c1 * 5352 + 7500) ,  12);

}

pub fn vp8_dct_col0(ip0: i64, ip4: i64, ip8: i64, ip12: i64) i64 {
    var a1: i64 = 0;
    var b1: i64 = 0;

  a1 = ip0 + ip12;
  b1 = ip4 + ip8;
  return _lia_shr((a1 + b1 + 7) ,  4);

}

pub fn vp8_dct_col1(ip0: i64, ip4: i64, ip8: i64, ip12: i64) i64 {
    var a1: i64 = 0;
    var d1: i64 = 0;
    var c1: i64 = 0;

  a1 = ip0 + ip12;
  d1 = ip0 - ip12;
  c1 = ip4 - ip8;
  return (_lia_shr((c1 * 2217 + d1 * 5352 + 12000) ,  16)) + (d1 != 0);

}

pub fn vp8_dct_col2(ip0: i64, ip4: i64, ip8: i64, ip12: i64) i64 {
    var a1: i64 = 0;
    var b1: i64 = 0;

  a1 = ip0 + ip12;
  b1 = ip4 + ip8;
  return _lia_shr((a1 - b1 + 7) ,  4);

}

pub fn vp8_dct_col3(ip0: i64, ip4: i64, ip8: i64, ip12: i64) i64 {
    var d1: i64 = 0;
    var c1: i64 = 0;

  d1 = ip0 - ip12;
  c1 = ip4 - ip8;
  return _lia_shr((d1 * 2217 - c1 * 5352 + 51000) ,  16);

}

pub fn test_vp8_dct_vector() i64 {

  // 5 cases, 8 outputs each, from gcc oracle on transpiled C else if (vp8_dct_row_out0(5, 9, 1, 3) != 144  or  vp8_dct_row_out1(5, 9, 1, 3) != 59  or  vp8_dct_row_out2(5, 9, 1, 3) != -16  or  vp8_dct_row_out3(5, 9, 1, 3) != -74) { return 0 ;}
  if (vp8_dct_col0(5, 9, 1, 3) != 1  or  vp8_dct_col1(5, 9, 1, 3) != 1  or  vp8_dct_col2(5, 9, 1, 3) != 0  or  vp8_dct_col3(5, 9, 1, 3) != 0) { return 0 ;}
  if (vp8_dct_row_out0(0, 0, 0, 0) != 0  or  vp8_dct_row_out1(0, 0, 0, 0) != 3  or  vp8_dct_row_out2(0, 0, 0, 0) != 0  or  vp8_dct_row_out3(0, 0, 0, 0) != 1) { return 0 ;}
  if (vp8_dct_col0(0, 0, 0, 0) != 0  or  vp8_dct_col1(0, 0, 0, 0) != 0  or  vp8_dct_col2(0, 0, 0, 0) != 0  or  vp8_dct_col3(0, 0, 0, 0) != 0) { return 0 ;}
  if (vp8_dct_row_out0(-1, -2, -3, -4) != -80  or  vp8_dct_row_out1(-1, -2, -3, -4) != 39  or  vp8_dct_row_out2(-1, -2, -3, -4) != 0  or  vp8_dct_row_out3(-1, -2, -3, -4) != 4) { return 0 ;}
  if (vp8_dct_col0(-1, -2, -3, -4) != -1  or  vp8_dct_col1(-1, -2, -3, -4) != 1  or  vp8_dct_col2(-1, -2, -3, -4) != 0  or  vp8_dct_col3(-1, -2, -3, -4) != 0) { return 0 ;}
  if (vp8_dct_row_out0(100, 200, 150, 50) != 4000  or  vp8_dct_row_out1(100, 200, 150, 50) != 742  or  vp8_dct_row_out2(100, 200, 150, 50) != -1600  or  vp8_dct_row_out3(100, 200, 150, 50) != -305) { return 0 ;}
  if (vp8_dct_col0(100, 200, 150, 50) != 31  or  vp8_dct_col1(100, 200, 150, 50) != 6  or  vp8_dct_col2(100, 200, 150, 50) != -13  or  vp8_dct_col3(100, 200, 150, 50) != -2) { return 0 ;}
  if (vp8_dct_row_out0(-32768, 32767, 12345, -9876) != 19744  or  vp8_dct_row_out1(-32768, 32767, 12345, -9876) != -150861  or  vp8_dct_row_out2(-32768, 32767, 12345, -9876) != -702048  or  vp8_dct_row_out3(-32768, 32767, 12345, -9876) != -312597) { return 0 ;}
  if (vp8_dct_col0(-32768, 32767, 12345, -9876) != 154  or  vp8_dct_col1(-32768, 32767, 12345, -9876) != -1178  or  vp8_dct_col2(-32768, 32767, 12345, -9876) != -5485  or  vp8_dct_col3(-32768, 32767, 12345, -9876) != -2442) { return 0 ;}
  return 1;

}

