const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn _wyrot64(x: i64) i64 {
    var w: i64 = 0;

  w = x;
  return (_lia_ushr(w, 32)) | (_lia_shl(w, 32));

}

pub fn wymix32(a_in: i64, b_in: i64, sel: i64) i64 {
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var res_a: i64 = 0;
    var res_b: i64 = 0;

  a = a_in & 4294967295;
  b = b_in & 4294967295;
  c = (a  ^  1405471321) * (b  ^  1953774619);
  res_a = c & 4294967295;
  res_b = _lia_ushr(c, 32) & 4294967295;
  if (sel == 0) { return res_a ;}
  return res_b;

}

pub fn wy32x32(a_in: i64, b_in: i64) i64 {
    var a1: i64 = 0;
    var b1: i64 = 0;
    var a2: i64 = 0;
    var b2: i64 = 0;

  a1 = wymix32(a_in, b_in, 0);
  b1 = wymix32(a_in, b_in, 1);
  a2 = wymix32(a1, b1, 0);
  b2 = wymix32(a1, b1, 1);
  return (a2 ^ b2) & 4294967295;

}

pub fn wyrand_step(seed_in: i64) i64 {
    var s: i64 = 0;
    var see1: i64 = 0;
    var see1_rot: i64 = 0;
    var s_rot: i64 = 0;
    var see1_rot2: i64 = 0;

  s = seed_in + -6884282663029611473;
  see1 = s  ^  -1800455987208640293;
  see1_rot = _wyrot64(see1);
  see1 = see1 * see1_rot;
  s_rot = _wyrot64(s);
  see1_rot2 = _wyrot64(see1);
  return (s * s_rot) ^ see1_rot2;

}

pub fn test_wyhash_vectors() i64 {
    var w32: i64 = 0;
    var r: i64 = 0;

  // Test wy32x32(0x12345678, 0x9abcdef0)
  w32 = wy32x32(305419896, 2596069104);
  // Test wyrand_step(0)
  r = wyrand_step(0);
  if (w32 != 1207097889  or  r != -6556845288980439527) { return 0 ;}
  return 1;

}

