const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn rotl64(x: i64, k: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = x;
  s = k & 63;
  return (_lia_shl(w, s)) | (_lia_ushr(w, 64 - s));

}

pub fn xoshiro256ss_result(s1: i64) i64 {
    var res: i64 = 0;

  res = (rotl64(s1 * 5, 7) * 9);
  return res;

}

pub fn xoshiro256ss_step(s0: i64, s1: i64, s2: i64, s3: i64, sel: i64) i64 {
    var t: i64 = 0;
    var ns2: i64 = 0;
    var ns3: i64 = 0;
    var ns1: i64 = 0;
    var ns0: i64 = 0;

  t = _lia_shl(s1, 17);
  ns2 = s2  ^  s0;
  ns3 = s3  ^  s1;
  ns1 = s1  ^  ns2;
  ns0 = s0  ^  ns3;
  ns2 = ns2  ^  t;
  ns3 = rotl64(ns3, 45);

  if (sel == 0) { return ns0 ;}
  if (sel == 1) { return ns1 ;}
  if (sel == 2) { return ns2 ;}
  return ns3;

}

pub fn test_xoshiro256_vector() i64 {
    var r: i64 = 0;
    var ns0: i64 = 0;
    var ns1: i64 = 0;
    var ns2: i64 = 0;
    var ns3: i64 = 0;

  // Test seed: s0 = 1, s1 = 2, s2 = 3, s3 = 4
  // Expected result = rotl64(2 * 5, 7) * 9 = rotl64(10, 7) * 9 = 1280 * 9 = 11520
  r = xoshiro256ss_result(2);
  if (r != 11520) { return 0 ;}

  ns0 = xoshiro256ss_step(1, 2, 3, 4, 0);
  ns1 = xoshiro256ss_step(1, 2, 3, 4, 1);
  ns2 = xoshiro256ss_step(1, 2, 3, 4, 2);
  ns3 = xoshiro256ss_step(1, 2, 3, 4, 3);

  // s0return s3 = 1^6 = 7
  // s1^s2 = 2^2 = 0
  ?(ns0 != 7  or  ns1 != 0) { return 0 ;}
  return 1;

}

