const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn xxh_rotl32(x: i64, r: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = x & 4294967295;
  s = r & 31;
  return ((_lia_shl(w, s)) | (_lia_shr(w, (32 - s)))) & 4294967295;

}

pub fn xxh_rotl64(x: i64, r: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = x;
  s = r & 63;
  return (_lia_shl(w, s)) | (_lia_shr(w, (64 - s)));

}

pub fn xxh_swap32(x: i64) i64 {
    var w: i64 = 0;

  w = x & 4294967295;
  return ((_lia_shl(w, 24)) & 4278190080) |
   ((_lia_shl(w, 8)) & 16711680) |
   ((_lia_shr(w, 8)) & 65280) |
   ((_lia_shr(w, 24)) & 255);

}

pub fn xxh32_round(acc: i64, input: i64) i64 {
    var a: i64 = 0;

  a = (acc + ((input & 4294967295) * 2246822519)) & 4294967295;
  a = xxh_rotl32(a, 13);
  return (a * 2654435761) & 4294967295;

}

pub fn xxh32_avalanche(h: i64) i64 {
    var hash: i64 = 0;

  hash = h & 4294967295;
  hash = hash  ^  _lia_shr(hash, 15);
  hash = (hash * 2246822519) & 4294967295;
  hash = hash  ^  _lia_shr(hash, 13);
  hash = (hash * 3266489917) & 4294967295;
  hash = hash  ^  _lia_shr(hash, 16);
  return hash;

}

pub fn xxh_xorshift64(v: i64, shift: i64) i64 {

  return v ^ _lia_shr(v, shift);

}

pub fn xxh3_avalanche(h: i64) i64 {
    var hash: i64 = 0;

  hash = h;
  hash = xxh_xorshift64(hash, 37);
  hash = hash * 1609587929392839161;
  hash = xxh_xorshift64(hash, 32);
  return hash;

}

pub fn xxh3_rrmxmx(h: i64, len: i64) i64 {
    var hash: i64 = 0;

  hash = h;
  hash = hash  ^  xxh_rotl64(hash, 49)  ^  xxh_rotl64(hash, 24);
  hash = hash * 11400714785074694791;
  hash = hash  ^  (_lia_shr(hash, 35) + len);
  hash = hash * 11400714785074694791;
  return xxh_xorshift64(hash, 28);

}

pub fn test_xxhash_vectors() i64 {

  if (xxh_swap32(305419896) != 2018915346) { return 0 ;}
  if (xxh32_round(0, 1) != 2381891501) { return 0 ;}
  if (xxh32_avalanche(1) != 1617762472) { return 0 ;}
  return 1;

}

