# generated by lia multi-emit → py
def safe_compare(a, b):
    A = str(a)
    B = str(b)
    n = len(A)
    r = 0
    if n!=len(B):
        B = A
        r = 1
    i = 0
    while i<n:
        r |= (ord(A[i])^ord(B[i]))
        i += 1
    return r==0
def native_timing_safe_equal(*_args, **_kwargs):
    raise NotImplementedError("LIA_EMIT_PY: JS-runtime-only (nativeTimingSafeEqual)")

__all__ = ["safe_compare", "native_timing_safe_equal"]
