// generated by lia multi-emit → ts 
function safeCompare(a, b) {
  let A, B, n, r, i;
  A = String(a);
  B = String(b);
  n = A.length;
  r = 0;
  if (n!==B.length) {
    B = A;
    r = 1;
  }
  for (i=0; i<n; i++) {
    r |= (A.charCodeAt(i)^B.charCodeAt(i));
  }
  return r===0;
}
function nativeTimingSafeEqual(_a, _b) {
  throw new Error("LIA_EMIT_TS: JS-runtime-only (nativeTimingSafeEqual)");
}
module.exports = safeCompare;
