// generated by lia multi-emit → ts 
export function safeCompare(a: unknown, b: unknown): boolean {
  let A, B, n, r, i;
  A = String(a);
  B = String(b);
  n = A.length;
  r = 0;
  if (n!==B.length) {
    B = A;
    r = 1;
  }
  for (i=0; i<n; i++) {
    r |= (A.charCodeAt(i)^B.charCodeAt(i));
  }
  return r===0;
}
export function nativeTimingSafeEqual(_a: unknown, _b: unknown): boolean {
  throw new Error("LIA_EMIT_TS: JS-runtime-only (nativeTimingSafeEqual)");
}