/* generated by lia_compiler 1.0.0 */
/* effect:Write */function safeCompare(a, b){var A,B,n,r,i;A=String(a);B=String(b);n=A.length;r=0;if(n!==B.length){B=A;r=1;};for(i=0;i<n;i++){r|=(A.charCodeAt(i)^B.charCodeAt(i));}return r===0;}
/* effect:Write */function nativeTimingSafeEqual(a, b){var A,B,aL,bL,ba,bb;A=String(a);B=String(b);aL=Buffer.byteLength(A);bL=Buffer.byteLength(B);ba=bufferAllocUnsafe(aL);ba.write(A);bb=bufferAllocUnsafe(aL);bb.write(B);return crypto.timingSafeEqual(ba,bb)&&aL===bL;}
module.exports=safeCompare;