// generated by lia multi-emit → rust (MVP)
#![allow(non_snake_case, unused_assignments, unused_variables, unused_parens, unused_mut, dead_code)]
fn _lia_typeof<T>(_x: &T) -> &'static str { "object" }
fn _lia_instanceof<T>(_x: &T) -> bool { false }
fn _lia_set<T, V>(_o: &T, _k: &str, v: V) -> V { v }
fn _lia_isfinite<T>(_x: &T) -> bool { true }
fn _lia_isnan<T>(_x: T) -> bool { false }
fn _lia_obj() -> String { String::new() }
fn _lia_arr(items: &[&str]) -> String { format!("\u{1e}{}", items.join("\u{1f}")) }
fn _lia_len(s: &impl ToString) -> i64 { let t = s.to_string(); if let Some(rest) = t.strip_prefix('\u{1e}') { if rest.is_empty() { 0 } else { rest.split('\u{1f}').count() as i64 } } else { t.chars().count() as i64 } }
fn _lia_at(s: &impl ToString, i: i64) -> String { let t = s.to_string(); let u = if i < 0 { 0 } else { i as usize }; if let Some(rest) = t.strip_prefix('\u{1e}') { rest.split('\u{1f}').nth(u).unwrap_or("").to_string() } else { t.chars().nth(u).map(|c| c.to_string()).unwrap_or_default() } }
fn _lia_push(s: &mut String, v: impl ToString) { let v = v.to_string(); if s.is_empty() || !s.starts_with('\u{1e}') { *s = format!("\u{1e}{}", v); return; } if s.len() == '\u{1e}'.len_utf8() { s.push_str(&v); } else { s.push('\u{1f}'); s.push_str(&v); } }
fn _lia_index_of(s: &impl ToString, x: impl ToString) -> i64 { let t = s.to_string(); let q = x.to_string(); if let Some(rest) = t.strip_prefix('\u{1e}') { rest.split('\u{1f}').position(|p| p == q).map(|i| i as i64).unwrap_or(-1) } else { t.find(&q).map(|i| t[..i].chars().count() as i64).unwrap_or(-1) } }
fn _lia_keys(_o: &impl ToString) -> String { _lia_arr(&[]) }
fn _lia_truthy(s: impl ToString) -> bool { let t = s.to_string(); t != "" && t != "false" && t != "0" && t != "null" && t != "undefined" }
fn _lia_re_test(pat: &str, s: impl ToString) -> bool { let t = s.to_string(); if pat == "\\s" { t.chars().any(|c| c.is_whitespace()) } else if pat.contains("[A-Za-z0-9_$]") || pat == "[A-Za-z0-9_$]" { t.chars().any(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$') } else { t.contains(pat) } }
fn _lia_abs(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0).abs() }
fn _lia_round(x: i64) -> i64 { x }
fn _lia_str(x: impl ToString) -> String { x.to_string() }
fn _lia_val(x: impl ToString) -> String { x.to_string() }
fn _lia_cat<A: ToString, B: ToString>(a: &A, b: &B) -> String { format!("{}{}", a.to_string(), b.to_string()) }
fn _lia_num(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0) }
fn _lia_or(a: impl ToString, b: impl ToString) -> String { let a = a.to_string(); if a.is_empty() { b.to_string() } else { a } }
fn _lia_get<T>(_o: &T, _k: &str) -> String { String::new() }
fn _lia_includes(s: &impl ToString, x: impl ToString) -> bool { s.to_string().contains(&x.to_string()) }
fn _lia_re_exec<T>(_s: T) -> String { String::new() }
fn _lia_lower(x: impl ToString) -> String { x.to_string() }
fn _lia_cache_get(cache: &[String], i: i32) -> String {
    let u = if i < 0 { 0 } else { i as usize };
    if u < cache.len() { cache[u].clone() } else { String::new() }
}
pub fn safe_compare(a: impl ToString, b: impl ToString) -> bool {
    let mut a = a.to_string();
    let mut b = b.to_string();
    let A = String::new();
    let B = String::new();
    let mut A: String = String::new();
    let mut B: String = String::new();
    let mut n: i64 = 0;
    let mut r: i64 = 0;
    A = a.to_string();
    B = b.to_string();
    n = _lia_len(&A);
    r = 0;
    if n!=_lia_len(&B) {
        B = A.clone();
        r = 1;
    }
    for i in 0..n {
        r = r | (A.as_bytes()[i as usize] as i64^B.as_bytes()[i as usize] as i64);
    }
    return r == 0;
}
pub fn native_timing_safe_equal() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (nativeTimingSafeEqual)");
}

fn main() {
    assert!(safe_compare("ab", "ab"));
    assert!(!safe_compare("a", "b"));
    assert!(!safe_compare("prefix", "pre"));
    assert!(safe_compare("", ""));
    println!("ok rust safe-compare");
}
