/* generated by lia_compiler 1.0.0 */
const ActiveMath = {
  usedAdd: function(a, b){
return a + b
;}
};
const usedAdd = ActiveMath.usedAdd;
/* effect:Read */function liveCompute(a, b){var pt;
pt = ({__struct: "UsedPoint",  x: a, y: b });
return usedAdd(pt.x, pt.y)
;}
module.exports=liveCompute;