/* generated by lia_compiler 1.0.0 */
const math_helper = {
  square: function(n){
return n * n
;},
  cube: function(n){
return n * n * n
;}
};
const square = math_helper.square;
const cube = math_helper.cube;
/* effect:Read */function calculatePowerSum(x){var sq,cb;
sq = square(x);
cb = cube(x);
return sq + cb
;}
/* effect:Read */function qualifiedSquare(x){
return math_helper.square(x)
;}
module.exports={calculatePowerSum,qualifiedSquare};