/* generated by lia_compiler 1.0.0 */
/* @effects: io, state */ const Storage = {
  readEntry: function(key){
return "ENTRY:" + key
;},
  writeEntry: function(key, value){
return "STORED:" + key + "=" + value
;}
};
/* @caps: io, state */ const readEntry = Storage.readEntry;
/* @caps: io, state */ const writeEntry = Storage.writeEntry;
/* effect:Read */function queryData(key){
return readEntry(key)
;}
/* effect:Read */function saveData(key, value){
return writeEntry(key, value)
;}
module.exports={queryData,saveData};