/* generated by lia_compiler 1.0.0 */
/* effect:Read */function factorial(n){var res,i;res=1;for(i=2;i<=n;i++){res=res*i;};return res;}
/* effect:Pure */function isEven(n){return (n%2===0);}
/* effect:Read */function sumTo(n){var total,i;total=0;for(i=1;i<=n;i++){total=total+i;};return total;}
/* effect:Pure */function square(n){return n*n;}
/* effect:Pure */function double(n){return n+n;}
module.exports={factorial,isEven,sumTo,square,double};