/* generated by lia multi-emit → java */
public class LinEmit {
  static String _lia_typeof(Object x) { return x == null ? "object" : "string"; }
  static boolean _lia_instanceof(Object x) { return false; }
  static Object _lia_set(Object o, String k, Object v) { return v; }
  static boolean _lia_isfinite(Object x) { return true; }
  static boolean _lia_empty(Object s) { return s == null || String.valueOf(s).isEmpty(); }
  static long _lia_abs(Object x) { try { return Math.abs(Long.parseLong(String.valueOf(x))); } catch (Exception e) { return 0L; } }
  static long _lia_round(Object x) { return _lia_abs(x); }
  static String _lia_str(Object x) { return String.valueOf(x); }
  static String _lia_at(Object s, Object i) { String t = String.valueOf(s); int n = (int)_lia_num(i); if (n < 0 || n >= t.length()) return ""; return t.substring(n, n+1); }
  static long _lia_num(Object x) { try { return Long.parseLong(String.valueOf(x)); } catch (Exception e) { return 0L; } }
  static String _lia_or(Object a, Object b) { return a == null || "".equals(a) ? String.valueOf(b) : String.valueOf(a); }
  static String _lia_get(Object o, String k) { return null; }
  static String _lia_obj(Object... _a) { return ""; }
  static boolean _lia_includes(Object s, Object x) { return String.valueOf(s).contains(String.valueOf(x)); }
  static String _lia_re_exec(Object s) { return null; }
  static String _lia_lower(Object x) { return String.valueOf(x).toLowerCase(); }
  static boolean _lia_truthy(Object x) {
    if (x == null) return false;
    if (x instanceof Boolean) return (Boolean)x;
    if (x instanceof String) return !((String)x).isEmpty();
    if (x instanceof Number) return ((Number)x).longValue() != 0L;
    return true;
  }
  static String[] cache = new String[64];

  public static boolean factorial() { throw new RuntimeException("JS-runtime-only"); }
  public static boolean isEven() { throw new RuntimeException("JS-runtime-only"); }
  public static boolean sumTo() { throw new RuntimeException("JS-runtime-only"); }
  public static boolean countDown() { throw new RuntimeException("JS-runtime-only"); }
  public static boolean clamp() { throw new RuntimeException("JS-runtime-only"); }
}
