// generated by lia multi-emit → rust (MVP)
#![allow(non_snake_case, unused_assignments, unused_variables, unused_parens, unused_mut, dead_code)]
fn _lia_typeof<T>(_x: &T) -> &'static str { "object" }
fn _lia_instanceof<T>(_x: &T) -> bool { false }
fn _lia_set<T, V>(_o: &T, _k: &str, v: V) -> V { v }
fn _lia_isfinite<T>(_x: &T) -> bool { true }
fn _lia_isnan<T>(_x: T) -> bool { false }
fn _lia_obj() -> String { String::new() }
fn _lia_abs(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0).abs() }
fn _lia_round(x: i64) -> i64 { x }
fn _lia_str(x: impl ToString) -> String { x.to_string() }
fn _lia_val(x: impl ToString) -> String { x.to_string() }
fn _lia_cat<A: ToString, B: ToString>(a: &A, b: &B) -> String { format!("{}{}", a.to_string(), b.to_string()) }
fn _lia_num(x: &impl ToString) -> i64 { x.to_string().parse::<i64>().unwrap_or(0) }
fn _lia_at(s: &impl ToString, i: i64) -> String { let t = s.to_string(); let u = if i < 0 { 0 } else { i as usize }; t.chars().nth(u).map(|c| c.to_string()).unwrap_or_default() }
fn _lia_or(a: impl ToString, b: impl ToString) -> String { let a = a.to_string(); if a.is_empty() { b.to_string() } else { a } }
fn _lia_get<T>(_o: &T, _k: &str) -> String { String::new() }
fn _lia_includes(s: &impl ToString, x: impl ToString) -> bool { s.to_string().contains(&x.to_string()) }
fn _lia_re_exec<T>(_s: T) -> String { String::new() }
fn _lia_lower(x: impl ToString) -> String { x.to_string() }
fn _lia_cache_get(cache: &[String], i: i32) -> String {
    let u = if i < 0 { 0 } else { i as usize };
    if u < cache.len() { cache[u].clone() } else { String::new() }
}
pub fn factorial() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (factorial)");
}
pub fn is_even() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (isEven)");
}
pub fn sum_to() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (sumTo)");
}
pub fn square() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (square)");
}
pub fn double_() -> bool {
    panic!("LIA_EMIT_RUST: JS-runtime-only (double)");
}

fn main() {
    assert!(factorial("ab", "ab"));
    assert!(!factorial("a", "b"));
    assert!(!factorial("prefix", "pre"));
    assert!(factorial("", ""));
    println!("ok rust safe-compare");
}
