# generated by lia multi-emit → py
def _lia_typeof(x):
    if x is None: return 'object'
    if isinstance(x, bool): return 'boolean'
    if isinstance(x, (int, float)): return 'number'
    if isinstance(x, str): return 'string'
    if callable(x): return 'function'
    return 'object'
def _lia_instanceof(x):
    return False
def _lia_isfinite(x):
    try:
        return x == x and abs(float(x)) != float('inf')
    except Exception:
        return False
def _lia_isnan(x):
    try:
        return x != x
    except Exception:
        return True
def _lia_abs(x):
    try: return abs(x)
    except Exception: return 0
def _lia_round(x):
    try: return round(x)
    except Exception: return 0
def _lia_str(x):
    return str(x)
def _lia_num(x):
    try: return float(x)
    except Exception: return 0
def _lia_or(a, b):
    return b if a is None or a == "" or a is False else a
def _lia_get(o, k):
    if o is None: return None
    if isinstance(o, dict): return o.get(k)
    return getattr(o, k, None)
def _lia_set(o, k, v):
    if isinstance(o, dict):
        o[k] = v
        return v
    try: setattr(o, str(k).replace(".", "_"), v)
    except Exception: pass
    return v
def _lia_re_exec(s):
    return None
def _lia_obj(*_a, **_k):
    return {}
def _lia_includes(s, x):
    return str(x) in str(s)
def _lia_lower(x):
    return str(x).lower()
def safe_compare(a, b):
    A = None
    B = None
    A = str(a)
    B = str(b)
    n = len(A)
    r = 0
    if n!=len(B):
        B = A
        r = 1
    i = 0
    while i<n:
        r |= (ord(A[i])^ord(B[i]))
        i += 1
    return r==0
def native_timing_safe_equal(a, b):
    A = None
    B = None
    Buffer = None
    A = str(a)
    B = str(b)
    aL = _lia_obj()
    bL = _lia_obj()
    ba = bufferAllocUnsafe(aL)
    _lia_obj()
    bb = bufferAllocUnsafe(aL)
    _lia_obj()
    return _lia_obj() and aL==bL

__all__ = ["safe_compare", "native_timing_safe_equal"]
