/* generated by lia_compiler 1.0.0 */
const AstModule = {
  createNode: function(kind, id, line){
return ({__struct: "SyntaxNode",  kind: kind, id: id, line: line })
;}
};
const ParserModule = {
  parseFunctionSignature: function(sig, line){
return createNode(NodeKind.Function, sig, line)
;},
  parseModuleHeader: function(name, line){
return createNode(NodeKind.Module, name, line)
;}
};
const SemanticModule = {
  validateNode: function(node){
if((node!=null && typeof node==='object' && (node instanceof SyntaxNode || node.__struct==='SyntaxNode' || true)) && ((node.kind==="NodeKind.Function" || node.kind==="Function")) && (line > 0)){let id=node.id;let line=node.line; return true ;}else if((node!=null && typeof node==='object' && (node instanceof SyntaxNode || node.__struct==='SyntaxNode' || true)) && ((node.kind==="NodeKind.Module" || node.kind==="Module")) && (line > 0)){let id=node.id;let line=node.line; return true ;}else if(true){ return false ;};
}
};
const EmitterModule = {
  emitRustDeclaration: function(node){
if((node!=null && typeof node==='object' && (node instanceof SyntaxNode || node.__struct==='SyntaxNode' || true)) && ((node.kind==="NodeKind.Function" || node.kind==="Function"))){let id=node.id; return "pub fn " + id + "() {}" ;}else if((node!=null && typeof node==='object' && (node instanceof SyntaxNode || node.__struct==='SyntaxNode' || true)) && ((node.kind==="NodeKind.Module" || node.kind==="Module"))){let id=node.id; return "pub mod " + id + " {}" ;}else if(true){ return "// unknown node" ;};
}
};
const NodeKind = AstModule.NodeKind;
const SyntaxNode = AstModule.SyntaxNode;
const parseFunctionSignature = ParserModule.parseFunctionSignature;
const parseModuleHeader = ParserModule.parseModuleHeader;
const validateNode = SemanticModule.validateNode;
const emitRustDeclaration = EmitterModule.emitRustDeclaration;
/* effect:Write */function compilePipeline(fnName, line){var node,valid;
node = parseFunctionSignature(fnName, line);
valid = validateNode(node);
if(valid === true){
return emitRustDeclaration(node)
;}
return "ERROR_INVALID_NODE"
;}
/* effect:Write */function compileModulePipeline(modName, line){var node,valid;
node = parseModuleHeader(modName, line);
valid = validateNode(node);
if(valid === true){
return emitRustDeclaration(node)
;}
return "ERROR_INVALID_NODE"
;}
module.exports={compilePipeline,compileModulePipeline};