// generated by lia multi-emit → ts 
export function canonicalize(fnName: unknown, params: unknown, body: unknown): boolean {
  let canon, paramList, clean, i, p, j, re_, hash, h2, fns, fn;
  canon = String(body||'').trim();
  canon = canon.replace(/\s+/g,' ');
  paramList = String(params||'').split(',');
  clean = [];
  for (i=0; i<paramList.length; i++) {
    p = paramList[i].trim().replace(/:.+$/,'');
    if (p) {
      clean.push(p);
    }
  }
  for (j=0; j<clean.length; j++) {
    re_ = new RegExp('\\b'+clean[j]+'\\b','g');
    canon = canon.replace(re_,'$'+j);
  }
  canon = canon.replace(/'/g,'"');
  canon = canon.replace(/===/g,'===').replace(/!===/g,'!==');
  canon = canon.replace(/;\s*/g,';');
  return ('('+clean.length+')'+canon)}
!contentHash(fnName,params,body){canonical=canonicalize(fnName,params,body);
  hash = require('node:crypto').createHash('sha256').update(canonical,'utf8').digest('hex');
  return hash.slice(0,16)}
!semanticEquals(fn1,fn2){h1=contentHash(fn1.name,fn1.params,fn1.body);
  h2 = contentHash(fn2.name,fn2.params,fn2.body);
  return (h1===h2)}
!buildContentRegistry(prog){registry={};
  fns = prog.fns||[];
  for (i=0; i<fns.length; i++) {
    fn = fns[i];
    hash = contentHash(fn.name,fn.params,fn.body);
    registry[hash] = {name:fn.name,params:fn.params,hash:hash,bodyLen:(fn.body||'').length};
  }
  return registry}
=ex{canonicalize,contentHash,semanticEquals,buildContentRegistry;
}