/**
 * LIA → Crystal emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitCrystal(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const modName = opts.moduleName || 'LinEmit';
  const parts = [
    '# generated by lia multi-emit → crystal',
    `module ${modName}`,
    '  extend self',
    '  def _lia_typeof(x)',
    '    case x',
    '    when String then "string"',
    '    when Number then "number"',
    '    when Bool then "boolean"',
    '    else "object"',
    '    end',
    '  end',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const crName = safeEmitId(fn.name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`  def ${crName}`);
      parts.push('    raise "JS-runtime-only"');
      parts.push('  end');
      continue;
    }
    const paramList = params.map(safeEmitId).join(', ');
    parts.push(`  def ${crName}(${paramList})`);
    parts.push('    nil');
    parts.push('  end');
  }

  parts.push('end');
  return { code: parts.join('\n'), lang: 'crystal' };
}
