/**
 * LIA → WebAssembly Text (WAT) emitter.
 * Generates valid WAT that can be compiled to .wasm via Node WebAssembly.compile.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitWat(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    ';; generated by lia multi-emit → wat (WebAssembly Text)',
    '(module',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const watName = safeEmitId(fn.name);

    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      // Stub: export a function that returns 0
      parts.push(`  (func $${watName} (export "${watName}") (result i64)`);
      parts.push('    (i64.const 0)');
      parts.push('  )');
      continue;
    }

    const paramDecls = params.map((p) => `(param $${safeEmitId(p)} i64)`).join(' ');
    parts.push(`  (func $${watName} (export "${watName}") ${paramDecls} (result i64)`);

    // Simple body: return first param or 0
    if (params.length > 0) {
      parts.push(`    (local.get $${safeEmitId(params[0])})`);
    } else {
      parts.push('    (i64.const 0)');
    }
    parts.push('  )');
  }

  parts.push(')');
  return { code: parts.join('\n'), lang: 'wat' };
}
