/**
 * LIA → Lua emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, parseParamList, isNoopExpr, safeEmitId } from './emit_shared.mjs';

function rewriteLuaExpr(expr) {
  let s = String(expr || '');
  s = s.replace(/===/g, '==').replace(/!==/g, '~=');
  s = s.replace(/!=/g, '~=');
  s = s.replace(/&&/g, ' and ').replace(/\|\|/g, ' or ');
  s = s.replace(/!(?!=)/g, 'not ');
  s = s.replace(/\bnull\b|\bundefined\b/g, 'nil');
  s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
  s = s.replace(/([A-Za-z_][\w]*)\.length\b/g, '#$1');
  return s;
}

function emitStmts(stmts, indent) {
  const pad = '  '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(`${pad}${st.id} = ${rewriteLuaExpr(st.expr)}`);
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteLuaExpr(st.expr)}`);
    } else if (st.type === 'throw') {
      lines.push(`${pad}error(${rewriteLuaExpr(st.expr)})`);
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break`);
      else if (!isNoopExpr(st.expr)) lines.push(`${pad}${rewriteLuaExpr(st.expr)}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${rewriteLuaExpr(st.cond)} then`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}elseif ${rewriteLuaExpr(e.cond)} then`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}else`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}end`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while ${rewriteLuaExpr(st.cond)} do`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}end`);
    }
  }
  return lines;
}

export function emitLua(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '-- generated by lia multi-emit → lua',
    'local M = {}',
    'local function _lia_num(x) return tonumber(x) or 0 end',
    'local function _lia_str(x) return tostring(x or "") end',
    'local function _lia_typeof(x) return type(x) end',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const luaName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`function M.${luaName}() error("JS-runtime-only") end`);
      continue;
    }
    const stmts = tryParseStmts(fn.body);
    if (!stmts) {
      parts.push(`function M.${luaName}() error("JS-runtime-only") end`);
      continue;
    }
    const paramList = params.map(safeEmitId).join(', ');
    parts.push(`function M.${luaName}(${paramList})`);
    const assigned = collectAssignedIds(stmts).filter((id) => !params.includes(id)).map(safeEmitId);
    for (const id of assigned) parts.push(`  local ${id} = nil`);
    parts.push(...emitStmts(stmts, 1));
    parts.push('end\n');
  }

  parts.push('return M');
  return { code: parts.join('\n'), lang: 'lua' };
}
