/**
 * LIA → Assembly (x86_64 NASM) emitter.
 */
import { parseLia } from './compiler.mjs';
import { safeEmitId } from './emit_shared.mjs';

export function emitAsm(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '; generated by lia multi-emit → nasm x86_64',
    'default rel',
    'section .text',
    '',
  ];

  for (const fn of prog.fns) {
    const fnName = safeEmitId(fn.name);
    parts.push(`global ${fnName}`);
    parts.push(`${fnName}:`);
    parts.push('    xor rax, rax');
    parts.push('    ret');
    parts.push('');
  }

  return { code: parts.join('\n'), lang: 'nasm' };
}
