/**
 * LIA → Kotlin emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitKotlin(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '/* generated by lia multi-emit → kotlin */',
    'package lin.emit',
    '',
    'object LinEmit {',
    '    fun _lia_typeof(x: Any?): String = if (x == null) "object" else if (x is String) "string" else if (x is Number) "number" else if (x is Boolean) "boolean" else "object"',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const ktName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`    fun ${ktName}(): Any? = throw RuntimeException("JS-runtime-only")`);
      continue;
    }
    const paramList = params.map((p) => `${safeEmitId(p)}: Any? = null`).join(', ');
    parts.push(`    fun ${ktName}(${paramList}): Any? {`);
    parts.push('        return null');
    parts.push('    }');
  }

  parts.push('}');
  return { code: parts.join('\n'), lang: 'kotlin' };
}
