/**
 * LIA → Scala emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitScala(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const objName = opts.objectName || 'LinEmit';
  const parts = [
    '/* generated by lia multi-emit → scala */',
    `object ${objName} {`,
    '  def _lia_typeof(x: Any): String = if (x == null) "object" else x.getClass.getSimpleName.toLowerCase',
    '  def _lia_str(x: Any): String = if (x == null) "" else x.toString',
    '  def _lia_num(x: Any): Long = try { x.toString.toLong } catch { case _: Throwable => 0L }',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const scName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`  def ${scName}(): Any = throw new RuntimeException("JS-runtime-only")`);
      continue;
    }
    const paramList = params.map((p) => `${safeEmitId(p)}: Any = null`).join(', ');
    parts.push(`  def ${scName}(${paramList}): Any = {`);
    parts.push('    null');
    parts.push('  }');
  }

  parts.push('}');
  return { code: parts.join('\n'), lang: 'scala' };
}
