/**
 * LIA → Julia emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitJulia(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const modName = opts.moduleName || 'LinEmit';
  const parts = [
    '# generated by lia multi-emit → julia',
    `module ${modName}`,
    'export _lia_typeof, _lia_str, _lia_num',
    '_lia_typeof(x) = string(typeof(x))',
    '_lia_str(x) = string(x)',
    '_lia_num(x) = try parse(Int64, string(x)) catch; 0 end',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const jlName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`function ${jlName}() error("JS-runtime-only") end`);
      continue;
    }
    const paramList = params.map(safeEmitId).join(', ');
    parts.push(`function ${jlName}(${paramList})`);
    parts.push('    nothing');
    parts.push('end\n');
  }

  parts.push('end');
  return { code: parts.join('\n'), lang: 'julia' };
}
