/**
 * LIA → HCL emitter.
 */
import { parseLia } from './compiler.mjs';

export function emitHcl(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '# generated by lia multi-emit → hcl',
    'locals {',
  ];

  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) {
      parts.push(`  ${k} = ${JSON.stringify(v)}`);
    }
  }

  for (const fn of prog.fns) {
    parts.push(`  fn_${fn.name} = {`);
    parts.push(`    params = ${JSON.stringify(fn.params || '')}`);
    parts.push(`    body   = ${JSON.stringify(fn.body || '')}`);
    parts.push('  }');
  }

  parts.push('}');
  return { code: parts.join('\n'), lang: 'hcl' };
}
