/**
 * LIA → Go emitter (MVP: interface{} params, fmt.Sprint / len / byte index).
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, splitPrefixIncCond, emitCond, assignOpLine, isNumishId, inferTypes, parseParamList, emitNilDefaults, isNoopExpr, collectFreeHostIds, emitFreeHostDecls, safeEmitId, emitNameMap, isBoolFnName } from './emit_shared.mjs';
import { emitThrowLine, rewriteSiblingCalls } from './emit_rewrite.mjs';
import { rawParamNames, rewriteSafeParamIds } from './emit_safe_ids_load.mjs';
import { isQualityFnSet, wantSafeCompareMain, formatQualityMain } from './emit_entry_main_load.mjs';

function emitStmts(stmts, indent, types) {
  const pad = '\t'.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'go', pad, types));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'go')}`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'go', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'go', pad, rewriteExpr));
      else if (/^[A-Za-z_][\w]*$/.test(st.expr.trim())) continue;
      else if (isNoopExpr(st.expr) || isNoopExpr(rewriteExpr(st.expr, 'go'))) continue;
      else lines.push(`${pad}${rewriteExpr(st.expr, 'go')}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${emitCond(st.cond, 'go')} {`);
      lines.push(...emitStmts(st.then, indent + 1, types));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if ${emitCond(e.cond, 'go')} {`);
        lines.push(...emitStmts(e.body, indent + 1, types));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1, types));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for ${rewriteExpr(st.init, 'go')}; ${emitCond(st.cond, 'go')}; ${rewriteExpr(st.step, 'go')} {`,
      );
      lines.push(...emitStmts(st.body, indent + 1, types));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      const inc = splitPrefixIncCond(st.cond);
      if (inc) {
        lines.push(`${pad}for {`);
        lines.push(`${pad}\t${inc.id}++`);
        lines.push(`${pad}\tif !(${inc.id} ${inc.op} _lia_num(${rewriteExpr(inc.rhs, 'go')})) { break }`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      } else if (String(st.cond).trim() === 'true') {
        lines.push(`${pad}for {`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      } else {
        lines.push(`${pad}for ${emitCond(st.cond, 'go')} {`);
        lines.push(...emitStmts(st.body, indent + 1, types));
        lines.push(`${pad}}`);
      }
    }
  }
  return lines;
}

function goType(id, types, body) {
  if (/^(match|unit|matchUnit|value|options)$/i.test(id)) return 'interface{}';
  if (types && types.has(id)) {
    const t = types.get(id);
    if (t === 'int') return 'int';
    if (t === 'bool') return 'bool';
    return 'interface{}';
  }
  const b = String(body || '');
  if (new RegExp(`\\b${id}\\b\\s*=\\s*[-+]?\\d+`).test(b)) return 'int';
  if (new RegExp(`\\b${id}\\b\\s*(\\|=|\\^=|-=)`).test(b)) return 'int';
  if (/Abs$|^(n|ms)$/i.test(id)) return 'int';
  if (/mask|step|cutoff|index|accepted|target|offset|poolNext|poolOffset|alphabetLen|charCodes/i.test(id)) return 'int';
  return isNumishId(id) ? 'int' : 'interface{}';
}

function goDeclLocals(locals, types, body) {
  return locals.map((id) => `\tvar ${id} ${goType(id, types, body)}`);
}

export function emitGo(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const pkg = opts.package || 'main';
  const parts = [`// generated by lia multi-emit → go`, `package ${pkg}`, ``];
  const fileHosty = opts.stubRuntime === true || opts.fileHosty === true;
  if (prog.consts && !fileHosty) {
    parts.push(`var K = map[string]int{${Object.entries(prog.consts).map(([k, v]) => `"${k}": ${v}`).join(', ')}}`);
    for (const [k, v] of Object.entries(prog.consts)) parts.push(`var ${k} = ${v}`);
  }
  const names = emitNameMap(prog.fns);
  for (const fn of prog.fns) {
    const { names: params, defaults } = parseParamList(fn.params);
    const goName = names[fn.name];
    const paramList = params.map((p) => `${safeEmitId(p)} interface{}`).join(', ');
    const bodySrc = rewriteSafeParamIds(rewriteSiblingCalls(fn.body, names), rawParamNames(fn.params));
    if (fileHosty || (isJsRuntimeOnly(fn.body, fn.name) && opts.stubRuntime !== false)) {
      const keep = params.map((p) => `\t_ = ${safeEmitId(p)}`).join('\n');
      parts.push(
        `func ${goName}(${paramList}) bool {\n${keep ? `${keep}\n` : ''}\tpanic("LIA_EMIT_GO: JS-runtime-only (${fn.name})")\n}`,
      );
      continue;
    }
    const stmts = tryParseStmts(bodySrc) || tryParseStmts(rewriteSafeParamIds(fn.body, rawParamNames(fn.params)));
    if (!stmts) {
      parts.push(
        `func ${goName}(${paramList}) bool {\n\tpanic("LIA_EMIT_GO: JS-runtime-only (${fn.name})")\n}`,
      );
      continue;
    }
    const safePs = params.map((p) => safeEmitId(p));
    const locals = collectAssignedIds(stmts).filter((id) => !params.includes(id) && !safePs.includes(id));
    const inferredTypes = inferTypes(stmts);
    const cacheStub = /\bcache\b/.test(fn.body) ? ['\tcache := make([]string, 64)'] : [];
    const freeHostIds = collectFreeHostIds(fn.body, params, prog.fns.map((f) => f.name));
    const freeHost = emitFreeHostDecls(freeHostIds, 'go');
    const declLocals = locals.filter((id) => id !== 'cache' && !freeHostIds.includes(id));
    const keepUnused = declLocals.map((id) => `\t_ = ${id}`);
    const emitted = emitStmts(stmts, 1, inferredTypes);
    const retType = isBoolFnName(fn.name) ? 'bool' : 'interface{}';
    if (!/\breturn\b/.test(emitted.join('\n'))) {
      emitted.push(retType === 'bool' ? '\treturn false' : '\treturn nil');
    }
    const bodyLines = [...cacheStub, ...freeHost, ...emitNilDefaults(defaults, 'go'), ...goDeclLocals(declLocals, inferredTypes, fn.body), ...keepUnused, ...emitted];
    parts.push(`func ${goName}(${paramList}) ${retType} {\n${bodyLines.join('\n')}\n}`);
  }
  const helpers = `
func _lia_instanceof(x interface{}) bool { return false }
func _lia_set(_o interface{}, _k string, v interface{}) interface{} { return v }
func _lia_typeof(x interface{}) string {
	switch x.(type) {
	case nil:
		return "object"
	case bool:
		return "boolean"
	case int, int64, float64:
		return "number"
	case string:
		return "string"
	default:
		return "object"
	}
}
func _lia_at(s interface{}, i interface{}) string {
	str := _lia_str(s)
	n := _lia_num(i)
	if n < 0 || n >= len(str) { return "" }
	return str[n:n+1]
}
func _lia_code_at(s interface{}, i interface{}) int {
	str := _lia_str(s)
	n := _lia_num(i)
	if n < 0 || n >= len(str) { return 0 }
	return int(str[n])
}
func _lia_isfinite(x interface{}) bool { return true }
func _lia_isnan(x interface{}) bool { return false }
func _lia_falsy(x interface{}) bool {
	if x == nil || x == false || x == 0 || x == "" { return true }
	return false
}
func _lia_len(x interface{}) int {
	switch v := x.(type) {
	case string:
		return len(v)
	default:
		return 0
	}
}
func _lia_num(x interface{}) int {
	switch v := x.(type) {
	case int:
		return v
	case int64:
		return int(v)
	case float64:
		return int(v)
	default:
		return 0
	}
}
func _lia_obj(_ ...interface{}) interface{} { return nil }
func _lia_or(a interface{}, b interface{}) interface{} {
	if _lia_falsy(a) { return b }
	return a
}
func _lia_cat(a interface{}, b interface{}) string { return _lia_str(a) + _lia_str(b) }
func _lia_str(x interface{}) string {
	switch v := x.(type) {
	case string:
		return v
	case nil:
		return ""
	case bool:
		if v {
			return "true"
		}
		return "false"
	case int:
		return _lia_itoa(v)
	case int64:
		return _lia_itoa(int(v))
	case float64:
		return _lia_itoa(int(v))
	default:
		return ""
	}
}
func _lia_abs(x interface{}) int {
	n := _lia_num(x)
	if n < 0 { return -n }
	return n
}
func _lia_round(x interface{}) int { return _lia_num(x) }
func _lia_get(_ interface{}, _ string) interface{} { return nil }
func _lia_includes(_ interface{}, _ interface{}) bool { return false }
func _lia_re_exec(_ interface{}) string { return "" }
func _lia_lower(x interface{}) string { return _lia_str(x) }
func _lia_f64(x interface{}) float64 { return float64(_lia_num(x)) }
func _lia_if(c interface{}, a interface{}, b interface{}) string {
	if _lia_falsy(c) { return _lia_str(b) }
	return _lia_str(a)
}
func _lia_itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [32]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}
`;
  parts.splice(parts.length > 2 ? 3 : 2, 0, helpers);
  const bodySoFar = parts.join('\n');
  const imports = [];
  const fnNames = prog.fns.map((f) => f.name);
  const quality = isQualityFnSet(fnNames);
  const safeMain = wantSafeCompareMain(opts.withMain, fnNames);
  if (/fmt\./.test(bodySoFar) || /fmt\./.test(helpers) || quality || safeMain) imports.push('"fmt"');
  if (/strings\./.test(bodySoFar)) imports.push('"strings"');
  if (imports.length) parts.splice(2, 0, `import (${imports.map((x) => `\n\t${x}`).join('')}\n)`);
  if (quality) {
    parts.push(formatQualityMain('go', names));
  } else if (safeMain) {
    const primary = prog.exports[0] || prog.fns[0]?.name || 'safeCompare';
    parts.push(`
func main() {
	if !${primary}("ab", "ab") { panic("eq") }
	if ${primary}("a", "b") { panic("neq") }
	if ${primary}("prefix", "pre") { panic("len") }
	if !${primary}("", "") { panic("empty") }
	fmt.Println("ok go safe-compare")
}`);
  }
  return { code: parts.join('\n') + '\n', program: prog, target: 'go' };
}
