/**
 * LIA → Zig emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitZig(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '// generated by lia multi-emit → zig',
    'const std = @import("std");',
    '',
    'pub fn _lia_typeof(x: anytype) []const u8 { _ = x; return "object"; }',
    'pub fn _lia_num(x: anytype) i64 { _ = x; return 0; }',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const zigName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`pub fn ${zigName}() void {}`);
      continue;
    }
    const paramList = params.map((p) => `${safeEmitId(p)}: anytype`).join(', ');
    parts.push(`pub fn ${zigName}(${paramList}) void {`);
    for (const p of params) parts.push(`    _ = ${safeEmitId(p)};`);
    parts.push('}');
  }

  return { code: parts.join('\n'), lang: 'zig' };
}
