/**
 * LIA → Prolog emitter.
 */
import { parseLia } from './compiler.mjs';

export function emitProlog(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '% generated by lia multi-emit → prolog',
    ':- dynamic lia_fn/2.',
    '',
  ];

  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) {
      parts.push(`lia_const(${k.toLowerCase()}, ${JSON.stringify(v)}).`);
    }
  }

  for (const fn of prog.fns) {
    const pCount = (fn.params || '').split(',').filter(Boolean).length;
    parts.push(`lia_fn(${fn.name.toLowerCase()}, ${pCount}).`);
  }

  return { code: parts.join('\n'), lang: 'prolog' };
}
