/**
 * LIA → Python emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, snakeCase, parseParamList, collectFreeHostIds, emitFreeHostDecls, safeEmitId, emitNameMap } from './emit_shared.mjs';
import { emitThrowLine, rewriteSiblingCalls } from './emit_rewrite.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      const rhs = rewriteExpr(st.expr, 'py');
      if (String(st.id).includes('.') || /\[[^\]]+\]/.test(String(st.id))) {
        const idx = String(st.id).match(/^([A-Za-z_$][\w$]*)\[(.+)\]$/);
        const obj = idx ? idx[1] : st.id.slice(0, String(st.id).indexOf('.'));
        const key = idx ? rewriteExpr(idx[2], 'py') : JSON.stringify(st.id.slice(String(st.id).indexOf('.') + 1));
        lines.push(`${pad}_lia_set(${obj}, ${key}, ${rhs})`);
      } else if (st.op === '=') lines.push(`${pad}${st.id} = ${rhs}`);
      else if (st.op === '|=') lines.push(`${pad}${st.id} |= ${rhs}`);
      else if (st.op === '+=') lines.push(`${pad}${st.id} += ${rhs}`);
      else if (st.op === '-=') lines.push(`${pad}${st.id} -= ${rhs}`);
      else if (st.op === '>>=') lines.push(`${pad}${st.id} >>= ${rhs}`);
      else if (st.op === '<<=') lines.push(`${pad}${st.id} <<= ${rhs}`);
      else lines.push(`${pad}${st.id} = ${st.id} ${st.op[0]} (${rhs})`);
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'py')}`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'py', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'py', pad, rewriteExpr));
      else lines.push(`${pad}${rewriteExpr(st.expr, 'py')}`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if ${rewriteExpr(st.cond, 'py')}:`);
      const thenL = emitStmts(st.then, indent + 1);
      lines.push(...(thenL.length ? thenL : [`${pad}    pass`]));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}elif ${rewriteExpr(e.cond, 'py')}:`);
        const bl = emitStmts(e.body, indent + 1);
        lines.push(...(bl.length ? bl : [`${pad}    pass`]));
      }
      if (st.else) {
        lines.push(`${pad}else:`);
        const el = emitStmts(st.else, indent + 1);
        lines.push(...(el.length ? el : [`${pad}    pass`]));
      }
    } else if (st.type === 'for') {
      // C-style for → while
      const init = st.init.match(/^([A-Za-z_][\w]*)\s*=\s*(.+)$/);
      if (init) lines.push(`${pad}${init[1]} = ${rewriteExpr(init[2], 'py')}`);
      else lines.push(`${pad}${rewriteExpr(st.init, 'py')}`);
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'py')}:`);
      const body = emitStmts(st.body, indent + 1);
      lines.push(...(body.length ? body : [`${pad}    pass`]));
      const step = st.step.match(/^([A-Za-z_][\w]*)\+\+$/);
      const step2 = st.step.match(/^([A-Za-z_][\w]*)\-\-$/);
      if (step) lines.push(`${pad}    ${step[1]} += 1`);
      else if (step2) lines.push(`${pad}    ${step2[1]} -= 1`);
      else lines.push(`${pad}    ${rewriteExpr(st.step, 'py')}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while ${rewriteExpr(st.cond, 'py')}:`);
      const wl = emitStmts(st.body, indent + 1);
      lines.push(...(wl.length ? wl : [`${pad}    pass`]));
    }
  }
  return lines;
}

export function emitPy(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const parts = [
    '# generated by lia multi-emit → py',
    'def _lia_typeof(x):',
    "    if x is None: return 'object'",
    '    if isinstance(x, bool): return \'boolean\'',
    '    if isinstance(x, (int, float)): return \'number\'',
    '    if isinstance(x, str): return \'string\'',
    '    if callable(x): return \'function\'',
    "    return 'object'",
    'def _lia_instanceof(x):',
    '    return False',
    'def _lia_isfinite(x):',
    '    try:',
    "        return x == x and abs(float(x)) != float('inf')",
    '    except Exception:',
    '        return False',
    'def _lia_isnan(x):',
    '    try:',
    '        return x != x',
    '    except Exception:',
    '        return True',
    'def _lia_abs(x):',
    '    try: return abs(x)',
    '    except Exception: return 0',
    'def _lia_round(x):',
    '    try: return round(x)',
    '    except Exception: return 0',
    'def _lia_str(x):',
    '    return str(x)',
    'def _lia_num(x):',
    '    try: return float(x)',
    '    except Exception: return 0',
    'def _lia_or(a, b):',
    '    return b if a is None or a == "" or a is False else a',
    'def _lia_get(o, k):',
    '    if o is None: return None',
    '    if isinstance(o, dict): return o.get(k)',
    '    return getattr(o, k, None)',
    'def _lia_set(o, k, v):',
    '    if isinstance(o, dict):',
    '        o[k] = v',
    '        return v',
    '    try: setattr(o, str(k).replace(".", "_"), v)',
    '    except Exception: pass',
    '    return v',
    'def _lia_re_exec(s):',
    '    return None',
    'def _lia_obj(*_a, **_k):',
    '    return {}',
    'def _lia_includes(s, x):',
    '    return str(x) in str(s)',
    'def _lia_lower(x):',
    '    return str(x).lower()',
  ];
  const fileHosty = opts.stubRuntime === true || opts.fileHosty === true;
  if (prog.consts && !fileHosty) {
    parts.push(`K = {${Object.entries(prog.consts).map(([k, v]) => `${JSON.stringify(k)}: ${v}`).join(', ')}}`);
    for (const [k, v] of Object.entries(prog.consts)) parts.push(`${k} = ${v}`);
  }
  const aliases = emitNameMap(prog.fns, snakeCase);
  for (const fn of prog.fns) {
    const name = aliases[fn.name];
    const { names: params, sigPy } = parseParamList(fn.params);
    if (fileHosty || (isJsRuntimeOnly(fn.body, fn.name) && opts.stubRuntime !== false)) {
      parts.push(`def ${name}(*_args, **_kwargs):\n    raise NotImplementedError("LIA_EMIT_PY: JS-runtime-only (${fn.name})")`);
      continue;
    }
    const stmts = tryParseStmts(rewriteSiblingCalls(fn.body, aliases)) || tryParseStmts(fn.body);
    if (!stmts) {
      parts.push(`def ${name}(*_args, **_kwargs):\n    raise NotImplementedError("LIA_EMIT_PY: JS-runtime-only (${fn.name})")`);
      continue;
    }
    const locals = collectAssignedIds(stmts).filter((id) => !params.includes(id));
    const body = [];
    body.push(...emitFreeHostDecls(collectFreeHostIds(fn.body, params, prog.fns.map((f) => f.name)), 'py'));
    body.push(...emitStmts(stmts, 1));
    if (!body.length) body.push('    pass');
    parts.push(`def ${name}(${sigPy.join(', ')}):\n${body.join('\n')}`);
  }
  const ex = (prog.exports.length ? prog.exports : prog.fns.map((f) => f.name)).map(snakeCase);
  parts.push(`\n__all__ = [${ex.map((n) => JSON.stringify(n)).join(', ')}]`);
  return { code: parts.join('\n') + '\n', program: prog, target: 'py' };
}
