/**
 * LIA → Haskell emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseParamList, safeEmitId, isJsRuntimeOnly } from './emit_shared.mjs';

export function emitHaskell(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const modName = opts.moduleName || 'LinEmit';
  const parts = [
    '{- generated by lia multi-emit → haskell -}',
    `module ${modName} where`,
    '',
    '_lia_str :: Show a => a -> String',
    '_lia_str = show',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const hsName = safeEmitId(fn.name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`${hsName} :: IO ()`);
      parts.push(`${hsName} = error "JS-runtime-only"`);
      continue;
    }
    const paramList = params.map(safeEmitId).join(' ');
    parts.push(`${hsName} ${paramList} = ()`);
  }

  return { code: parts.join('\n'), lang: 'haskell' };
}
