/**
 * LIA → C# emitter.
 */
import { parseLia } from './compiler.mjs';
import { parseStmts, tryParseStmts, collectAssignedIds } from './body_ast.mjs';
import { isJsRuntimeOnly, rewriteExpr, emitCond, assignOpLine, isNumishId, parseParamList, inferTypes, rewriteFnValues, isNoopExpr, safeEmitId } from './emit_shared.mjs';
import { emitThrowLine } from './emit_rewrite.mjs';

function emitStmts(stmts, indent) {
  const pad = '    '.repeat(indent);
  const lines = [];
  for (const st of stmts) {
    if (st.type === 'assign') {
      lines.push(assignOpLine(st.id, st.op, st.expr, 'java', pad));
    } else if (st.type === 'return') {
      lines.push(`${pad}return ${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'throw') {
      lines.push(emitThrowLine(st.expr, 'java', pad, rewriteExpr));
    } else if (st.type === 'expr') {
      if (/^break\b/.test(st.expr.trim())) lines.push(`${pad}break;`);
      else if (/^throw\b/.test(st.expr.trim())) lines.push(emitThrowLine(st.expr, 'java', pad, rewriteExpr));
      else if (/^[A-Za-z_][\w]*$/.test(st.expr.trim())) continue;
      else if (isNoopExpr(st.expr) || isNoopExpr(rewriteExpr(st.expr, 'java'))) continue;
      else lines.push(`${pad}${rewriteExpr(st.expr, 'java')};`);
    } else if (st.type === 'if') {
      lines.push(`${pad}if (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.then, indent + 1));
      for (const e of st.elseIf || []) {
        lines.push(`${pad}} else if (${emitCond(e.cond, 'java')}) {`);
        lines.push(...emitStmts(e.body, indent + 1));
      }
      if (st.else) {
        lines.push(`${pad}} else {`);
        lines.push(...emitStmts(st.else, indent + 1));
      }
      lines.push(`${pad}}`);
    } else if (st.type === 'for') {
      lines.push(
        `${pad}for (${rewriteExpr(st.init, 'java')}; ${emitCond(st.cond, 'java')}; ${rewriteExpr(st.step, 'java')}) {`,
      );
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    } else if (st.type === 'while') {
      lines.push(`${pad}while (${emitCond(st.cond, 'java')}) {`);
      lines.push(...emitStmts(st.body, indent + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

export function emitCs(liaText, opts = {}) {
  const prog = parseLia(liaText);
  const className = opts.className || 'LinEmit';
  const parts = [
    '/* generated by lia multi-emit → csharp */',
    'using System;',
    'using System.Collections.Generic;',
    '',
    `public static class ${className} {`,
    '    public static string _lia_typeof(object x) => x == null ? "object" : "string";',
    '    public static bool _lia_instanceof(object x) => false;',
    '    public static object _lia_set(object o, string k, object v) => v;',
    '    public static bool _lia_isfinite(object x) => true;',
    '    public static bool _lia_empty(object s) => s == null || string.IsNullOrEmpty(s.ToString());',
    '    public static long _lia_abs(object x) { try { return Math.Abs(Convert.ToInt64(x)); } catch { return 0; } }',
    '    public static long _lia_round(object x) => _lia_abs(x);',
    '    public static string _lia_str(object x) => x?.ToString() ?? "";',
    '    public static string _lia_at(object s, object i) { string t = _lia_str(s); int n = (int)_lia_num(i); return (n < 0 || n >= t.Length) ? "" : t.Substring(n, 1); }',
    '    public static long _lia_num(object x) { try { return Convert.ToInt64(x); } catch { return 0; } }',
    '    public static string _lia_or(object a, object b) => _lia_empty(a) ? _lia_str(b) : _lia_str(a);',
    '    public static string _lia_get(object o, string k) => "";',
    '    public static string _lia_obj(params object[] a) => "";',
    '    public static bool _lia_includes(object s, object x) => _lia_str(s).Contains(_lia_str(x));',
    '    public static bool _lia_truthy(object x) {',
    '        if (x == null) return false;',
    '        if (x is bool b) return b;',
    '        if (x is string s) return !string.IsNullOrEmpty(s);',
    '        if (x is long l) return l != 0;',
    '        if (x is int i) return i != 0;',
    '        return true;',
    '    }',
    '    public static string[] cache = new string[64];',
    '',
  ];

  for (const fn of prog.fns) {
    const { names: params } = parseParamList(fn.params);
    const csName = safeEmitId(fn.name);
    if (opts.stubRuntime !== false || isJsRuntimeOnly(fn.body, fn.name)) {
      parts.push(`    public static object ${csName}() => throw new NotSupportedException("JS-runtime-only");`);
      continue;
    }
    const stmts = tryParseStmts(fn.body);
    if (!stmts) {
      parts.push(`    public static object ${csName}() => throw new NotSupportedException("JS-runtime-only");`);
      continue;
    }
    const paramList = params.map((p) => `object ${safeEmitId(p)} = null`).join(', ');
    parts.push(`    public static object ${csName}(${paramList}) {`);
    const assigned = collectAssignedIds(stmts).filter((id) => !params.includes(id) && id !== 'cache').map(safeEmitId);
    for (const id of assigned) parts.push(`        object ${id} = null;`);
    parts.push(...emitStmts(stmts, 2));
    parts.push('        return null;');
    parts.push('    }');
  }

  parts.push('}');
  return { code: parts.join('\n'), lang: 'csharp' };
}
