/* generated by lia_compiler 1.0.0 */
/* effect:Read */function safeDiv(value, divisor){
return value / divisor;
}
/* effect:Read */function classify(n){
if((n===1)){return 10;}else if((n===2)){return 20;}else if(true){return 0;}
return 0;
}
/* effect:Read */function runTests(){
let a = safeDiv(10, 2);
return a;
}
module.exports={safeDiv,classify,runTests};