/* generated by lia_compiler 1.0.0 */
const MathOps = {
  add: function(a, b){
return a + b
;},
  multiply: function(a, b){
return a * b
;}
};
const add = MathOps.add;
const multiply = MathOps.multiply;
/* effect:Read */function compute(x, y){var sum,prod;
sum = add(x, y);
prod = multiply(x, y);
return sum + prod
;}
/* effect:Read */function qualifiedCompute(x, y){
return MathOps.multiply(x, y)
;}
module.exports={compute,qualifiedCompute};