import { renderBody as jsBody, normalizeElse } from './render_core.mjs';
import { collectAssignedIds, firstUseIsRead } from './effects.mjs';
import { collectBareStmtIds, stripBareIdStmts } from './render_js.mjs';
import { snakeCase, safeEmitId, prepareNativeFn } from './emit_shared.mjs';

export class EmitUnsupportedError extends Error {
  constructor(message) {
    super(`LIN_EMIT_UNSUPPORTED: ${message}`);
    this.name = 'EmitUnsupportedError';
  }
}

const JS_RUNTIME_ONLY = /\b(Buffer|crypto|bufferAllocUnsafe|timingSafeEqual|process|Intl|arguments)\b|\bthis\.|\bthis\[|\bswitch\b|\bnew\s+Date\b|Object\.(setPrototypeOf|defineProperty|entries|create)/;

export function isJsRuntimeOnly(body) {
  return JS_RUNTIME_ONLY.test(String(body || ''));
}

export function stmtsText(fn) {
  if (fn.__bodyText) return fn.__bodyText;
  // Prefer AST→JS when rawBody still has LIN sigils (lossy clone corpus).
  if (typeof fn.rawBody === 'string' && !/[?#]|:\s*[\{\(?]|^\s*\^|(?:^|[;{}])\s*\^/.test(fn.rawBody)) {
    return fn.rawBody;
  }
  return jsBody(fn.body || []);
}


function inlineStrAliases(text) {
  let out = String(text || '');
  const aliases = [];
  const re = /([A-Za-z_$][\w$]*)\s*=\s*String\(([A-Za-z_$][\w$]*)\)\s*;/g;
  let m;
  while ((m = re.exec(out)) !== null) {
    aliases.push([m[1], m[2]]);
  }
  for (const [alias, real] of aliases) {
    out = out.replace(new RegExp(`\\b${alias}\\b`, 'g'), real);
  }
  return { text: out, aliases };
}


function stripDeclKw(line) {
  return String(line).replace(/(^|[;{}])\s*(?:const|let|var)\s+/g, '$1');
}

function strParamNames(fn) {
  const text = stmtsText(fn);
  const out = [];
  for (const p of paramList(fn)) {
    if (new RegExp(`\\b${p.name}\\s*\\.\\s*(charCodeAt|length)\\b`).test(text) || new RegExp(`String\\(\\s*${p.name}\\s*\\)`).test(text)) {
      out.push(p.name);
    }
  }
  return out;
}

function retIsBool(fn) {
  const text = stmtsText(fn);
  const rets = text.match(/\breturn\s+([^;{}]+)/g) || [];
  if (!rets.length) return false;
  return rets.every((rr) => /[=!<>]==?|&&|\|\||\b(true|false)\b/.test(rr));
}

function paramList(fn) {
  return (fn.params || []).map((p) => ({ name: p.name, type: normType(p.type), rawType: String(p.type || ''), def: p.def, arr: !!(p.arr || p.isArray) }));
}

function normType(t) {
  const s = String(t || '').trim();
  if (!s) return 'any';
  if (/^(int|i32|i64|integer)$/.test(s)) return 'int';
  if (/^(float|f64|double|number)$/.test(s)) return 'float';
  if (/^(str|string)$/.test(s)) return 'string';
  if (/^bool(ean)?$/.test(s)) return 'bool';
  return 'any';
}

function defaultFor(t) {
  switch (t) {
    case 'int': return '0';
    case 'float': return '0.0';
    case 'bool': return 'false';
    case 'string': return '""';
    default: return null;
  }
}

export function emitTs(prog, opts = {}) {
  const parts = [`/* generated by lin-rewrite → ts */`];
  if (prog.consts) {
    parts.push(`const $K: Record<string, number> = { ${Object.entries(prog.consts).map(([k, v]) => `${JSON.stringify(k)}:${v}`).join(',')} };`);
  }
  const exported = new Set(prog.exports.map((e) => e.split(/\s+as\s+/)[0].trim()));
  for (const mod of prog.modules || []) {
    parts.push(`const ${mod.name}: Record<string, (...a: unknown[]) => unknown> = ${moduleObjTs(mod)};`);
  }
  for (const u of prog.uses || []) {
    for (const sym of u.symbols) parts.push(`const ${sym} = ${u.module}.${sym};`);
  }
  for (const fn of prog.fns) {
    const ps = (fn.params || []).map((p) => {
      const t = p.type && normType(p.type) !== 'any' ? mapTsType(normType(p.type)) : 'unknown';
      return `${safeEmitId(p.name)}${p.def != null && p.def !== '' ? `: ${t} = ${p.def}` : `: ${t}`}`;
    }).join(', ');
    const rt = fn.returnType ? `: ${mapTsType(normType(fn.returnType.replace(/^[^A-Za-z]+/, '')))}` : ': unknown';
    const kw = exported.has(fn.name) ? 'export function' : 'function';
    const bodyText = jsBody(fn.body);
    const paramsSet = new Set((fn.params || []).map((p) => p.name));
    const bareIds = collectBareStmtIds(bodyText);
    const cleaned = stripBareIdStmts(bodyText);
    const locals = [...new Set([...collectAssignedIds(cleaned), ...bareIds])].filter((id) => {
      if (paramsSet.has(id)) return false;
      if (bareIds.has(id)) return true;
      return !firstUseIsRead(cleaned, id);
    });
    parts.push(`${kw} ${fn.name}(${ps})${rt} {${locals.length ? `let ${locals.join(',')};` : ''}${bodyText}}`);
  }
  void opts;
  return parts.join('\n');
}

function mapTsType(t) {
  switch (t) {
    case 'int': case 'float': return 'number';
    case 'string': return 'string';
    case 'bool': return 'boolean';
    default: return 'unknown';
  }
}

function moduleObjTs(mod) {
  const fns = (mod.program.fns || []).map((fn) => `${fn.name}: (${(fn.params || []).map(() => 'a: unknown').join(',') || ''}) => unknown`);
  void fns;
  const body = (mod.program.fns || []).map((fn) => `${fn.name}: function(...a: unknown[]): unknown { return (${fn.name}_impl)(...a); }`);
  void body;
  const defs = (mod.program.fns || []).map((fn) => `function ${mod.name}_${fn.name}(...a: unknown[]): unknown { throw new Error('stub'); }`);
  void defs;
  return `{ ${(mod.program.fns || []).map((fn) => `${fn.name}: ${mod.name}_${fn.name}`).join(', ')} }`;
}

export function emitPy(prog, opts = {}) {
  const lines = ['# generated by lin-rewrite → py'];
  lines.push(PY_RUNTIME);
  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) lines.push(`${safeEmitId(k)} = ${v}`);
    lines.push('$K = {' + Object.entries(prog.consts).map(([k]) => `${JSON.stringify(k)}: ${safeEmitId(k)}`).join(', ') + '}');
  }
  for (const u of prog.uses || []) {
    for (const sym of u.symbols) lines.push(`${sym} = ${u.module}.${sym}`);
  }
  for (const fn of prog.fns) {
    emitPyFn(lines, prog, fn);
  }
  void opts;
  return lines.join('\n');
}

function emitPyFn(lines, prog, fn) {
  prepareNativeFn(fn);
  const text = stmtsText(fn);
  if (prog.__stubNames && prog.__stubNames.has(fn.name)) {
    const ps0 = paramList(fn).map((x) => safeEmitId(x.name)).join(', ');
    lines.push(`def ${safeEmitId(snakeCase(fn.name))}(${ps0}):`);
    lines.push(`    raise NotImplementedError('${fn.name}: js_runtime_only')`);
    lines.push('');
    return;
  }
  const name = safeEmitId(snakeCase(fn.name));
  const ps = paramList(fn);
  const sig = ps.map((p) => {
    const id = safeEmitId(p.name);
    return p.def != null && p.def !== '' ? `${id}=${pyExpr(p.def)}` : id;
  }).join(', ');
  lines.push(`def ${name}(${sig}):`);
  if (isJsRuntimeOnly(text)) {
    lines.push(`    raise NotImplementedError('${fn.name}: js_runtime_only')`);
    return;
  }
  const bodyLines = pyStmts(fn.body, 1, prog);
  lines.push(...(bodyLines.length ? bodyLines : ['    pass']));
  lines.push('');
}

function pyStmts(stmts, indent, prog) {
  const pad = '    '.repeat(indent);
  const out = [];
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${pyStmtTail(st.expr, indent)}`);
        break;
      case 'throw':
        out.push(`${pad}raise Exception(${pyExpr(stripThrow(st.expr))})`);
        break;
      case 'break':
        out.push(`${pad}break`);
        break;
      case 'continue':
        out.push(`${pad}continue`);
        break;
      case 'assign':
        out.push(`${pad}${pyLhs(st.idPath)} ${pyAssignOp(st.op)} ${pyStmtRhs(st.rhs, indent)}`);
        break;
      case 'expr':
        out.push(`${pad}${stripDeclKw(pyStmtTail(st.expr, indent))}`);
        break;
      case 'assign':
        break;
      case 'if': {
        out.push(`${pad}if ${pyCond(st.cond)}:`);
        pushBlock(out, pyStmts(st.then, indent + 1, prog), pad);
        for (const ei of st.elseIf || []) {
          out.push(`${pad}elif ${pyCond(ei.cond)}:`);
          pushBlock(out, pyStmts(collectChainBodies(ei), indent + 1, prog), pad);
        }
        if (st.else) {
          out.push(`${pad}else:`);
          pushBlock(out, pyStmts(normalizeElse(st.else), indent + 1, prog), pad);
        }
        break;
      }
      case 'blockternary': {
        out.push(`${pad}${pyLhs('_lt')} = (${pyBody(st.then)} if ${pyCond(st.cond)} else ${pyBody(st.elseExpr)})`.replace('_lt = ', '_lt = '));
        out.push(`${pad}pass`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        if (initM) {
          out.push(`${pad}${safeEmitId(initM[1])} = ${pyExpr(initM[2])}`);
        }
        out.push(`${pad}while ${pyCond(st.cond)}:`);
        const inner = pyStmts(st.body, indent + 1, prog);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        if (stepM) {
          inner.push(`${'    '.repeat(indent + 1)}${safeEmitId(stepM[1])} ${stepM[2] === '++' ? '+' : '-'}= 1`);
        } else if (st.step.trim()) {
          inner.push(`${'    '.repeat(indent + 1)}${pyExpr(st.step)}`);
        }
        pushBlock(out, inner, pad);
        break;
      }
      case 'while':
        out.push(`${pad}while ${pyCond(st.cond)}:`);
        pushBlock(out, pyStmts(st.body, indent + 1, prog), pad);
        break;
      case 'match':
        pyMatch(out, st, indent, prog);
        break;
      default:
        throw new EmitUnsupportedError(`py stmt ${st.type}`);
    }
  }
  return out;
}

function collectChainBodies(ei) {
  return ei.body;
}

function pushBlock(out, inner, pad) {
  out.push(...(inner.length ? inner : [`${pad}    pass`]));
}

function stripThrow(expr) {
  const t = pyExprRaw(expr).trim();
  return t.replace(/^new\s+/, '').replace(/^Error\((.*)\)$/, '$1');
}

function pyCond(cond) {
  return pyExprRaw(cond);
}

function pyStmtRhs(rhs, indent) {
  void indent;
  return pyExprRaw(rhs);
}

function pyStmtTail(expr, indent) {
  void indent;
  return pyExprRaw(expr);
}

function pyBody(blockternaryOrExpr) {
  if (blockternaryOrExpr && blockternaryOrExpr.parts) return pyExprRaw(blockternaryOrExpr);
  return '';
}

function pyLhs(path) {
  return String(path).split('.').map(safeEmitId).join('.');
}

function pyAssignOp(op) {
  switch (op) {
    case '=': return '=';
    case '+=': return '+=';
    case '-=': return '-=';
    case '*=': return '*=';
    case '/=': return '/=';
    case '%=': return '%=';
    case '|=': return '|=';
    case '&=': return '&=';
    case '^=': return '^=';
    case '<<=': return '<<=';
    case '>>=': return '>>=';
    default:
      if (op === '|=') return '|=';
      throw new Error(`LIN_EMIT_PY_OP: ${op}`);
  }
}

export function pyExprRaw(expr) {
  const text = expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : nodeToJs(p.node))).join(' ')
    : String(expr ?? '');
  return pyExpr(text);
}

function nodeToJs(node) {
  return jsBodyNodeInline(node);
}

function jsBodyNodeInline(node) {
  if (node.kind === 'closure' || node.kind === 'fnlit') return `lambda: None`;
  if (node.kind === 'arrow') return `lambda: None`;
  throw new EmitUnsupportedError(`py inline ${node.kind}`);
}

function templatesToFStrings(s) {
  let guard = 0;
  while (s.includes('`') && guard++ < 50) {
    const start = s.indexOf('\`');
    let i = start + 1;
    let depth = 0;
    let end = -1;
    for (; i < s.length; i++) {
      const c = s[i];
      if (c === '\\') {
        i++;
        continue;
      }
      if (c === '$' && s[i + 1] === '{') {
        depth++;
        i++;
        continue;
      }
      if (c === '}') depth--;
      else if (c === '\`' && depth <= 0) {
        end = i;
        break;
      }
      void depth;
    }
    if (end < 0) break;
    const body = s.slice(start + 1, end);
    const expr = 'f"' + body.replace(/\$\{([^}]*)\}/g, (_, e) => '{' + e.trim() + '}').replace(/"/g, '\\"') + '"';
    s = s.slice(0, start) + expr + s.slice(end + 1);
  }
  return s;
}

export function pyExpr(text) {
  let s = String(text);
  s = templatesToFStrings(s);
  s = s.replace(/JSON\.stringify\(/g, 'json.dumps(');
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, '_lia_ord($1[$2])');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b/g, '_lia_len($1)');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, '_lia_str($1)');
  s = s.replace(/\btypeof\s+([A-Za-z_$][\w$]*(?:\([^()]*\))?)/g, '_lia_typeof($1)');
  s = s.replace(/\bundefined\b/g, 'None').replace(/\bnull\b/g, 'None');
  s = s.replace(/\btrue\b/g, 'True').replace(/\bfalse\b/g, 'False');
  s = s.replace(/\bnew\s+Error\(([^()]*)\)/g, 'Exception($1)');
  s = s.replace(/\bMath\.floor\(/g, '_lia_floor(');
  s = s.replace(/\bMath\.abs\(/g, 'abs(');
  s = s.replace(/\bMath\.min\(/g, 'min(');
  s = s.replace(/\bMath\.max\(/g, 'max(');
  s = s.replace(/\bMath\.round\(/g, '_lia_round(');
  s = s.replace(/\bString\(/g, '_lia_str(');
  s = s.replace(/\bNumber\(/g, '_lia_num(');
  s = s.replace(/\bisNaN\(/g, '_lia_isnan(');
  s = s.replace(/\bNumber\.isFinite\(/g, '_lia_isfinite(');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\s*&&\s*/g, ' and ').replace(/\s*\|\|\s*/g, ' or ');
  s = replaceNot(s);
  s = replaceTernariesPy(s);
  return s;
}

function replaceNot(s) {
  let out = '';
  let i = 0;
  while (i < s.length) {
    if (s[i] === '!' && /[A-Za-z_(]/.test(s[i + 1] || '')) {
      out += 'not ';
      i++;
      continue;
    }
    out += s[i];
    i++;
  }
  return out;
}

export function replaceTernariesPy(s) {
  let guard = 0;
  for (;;) {
    if (guard++ > 50) break;
    const t = findTopTernary(s);
    if (!t) break;
    const cond = s.slice(t.condStart, t.qIdx).trim();
    const thenE = s.slice(t.qIdx + 1, t.colonIdx).trim();
    const elseE = s.slice(t.colonIdx + 1, t.end).trim();
    s = s.slice(0, t.condStart) + `(${thenE} if (${cond}) else ${elseE})` + s.slice(t.end);
  }
  return s;
}

function findTopTernary(s) {
  let depth = 0;
  let quote = null;
  let qIdx = -1;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') {
      quote = c;
      continue;
    }
    if ('([{'.includes(c)) depth++;
    else if (')]}'.includes(c)) depth--;
    else if (depth === 0 && c === '?' ) qIdx = i;
    else if (depth === 0 && c === ':' && qIdx >= 0) {
      return { condStart: 0, qIdx, colonIdx: i, end: s.length };
    }
  }
  return null;
}

const PY_RUNTIME = `import json
def _lia_typeof(x):
    if x is None: return 'object'
    if isinstance(x, bool): return 'boolean'
    if isinstance(x, (int, float)): return 'number'
    if isinstance(x, str): return 'string'
    if callable(x): return 'function'
    try:
        len(x)
        return 'object'
    except Exception:
        return 'object'
def _lia_isfinite(x):
    try:
        return x == x and abs(float(x)) != float('inf')
    except Exception:
        return False
def _lia_isnan(x):
    try:
        return x != x
    except Exception:
        return True
def _lia_floor(x):
    import math
    try: return int(math.floor(float(x)))
    except Exception: return 0
def _lia_round(x):
    try: return int(round(x))
    except Exception: return 0
def _lia_abs(x):
    try: return abs(x)
    except Exception: return 0
def _lia_str(x):
    if isinstance(x, bool): return 'true' if x else 'false'
    if isinstance(x, float) and x == int(x): return str(int(x))
    return str(x)
def _lia_num(x):
    try: return float(x)
    except Exception:
        try: return float(int(str(x)))
        except Exception: return 0
def _lia_len(x):
    try: return len(x)
    except Exception: return 0
def _lia_ord(x):
    try: return ord(x)
    except Exception: return 0
def _lia_or(a, b):
    return b if a is None or a == "" or a is False else a`;

function pyMatch(out, st, indent, prog) {
  void prog;
  const pad = '    '.repeat(indent);
  const target = pyExprRaw(st.target);
  for (let idx = 0; idx < st.arms.length; idx++) {
    const arm = st.arms[idx];
    const condTxt = pyArmCond(target, arm.pat, arm.guard);
    const kw = idx === 0 ? 'if' : 'elif';
    out.push(`${pad}${kw} ${condTxt}:`);
    pushBlock(out, pyStmts(arm.body, indent + 1), pad);
  }
}

function pyArmCond(target, pat, guard) {
  if (pat === '_') return guard ? `(${guard})` : 'True';
  const enumMatch = pat.match(/^([A-Za-z_$][\w$]*)\(([^)]+)\)$/);
  const tupleMatch = pat.match(/^\(([^)]+)\)$/);
  let base;
  if (enumMatch) {
    const tag = enumMatch[1];
    const v = safeEmitId(enumMatch[2].trim());
    base = `getattr(${target}, 'tag', None) == '${tag}'`;
    base += ` # binds ${v}`;
  } else if (tupleMatch) {
    base = `isinstance(${target}, (list, tuple)) and len(${target}) >= ${tupleMatch[1].split(',').length}`;
  } else {
    base = `${target} == ${pat}`;
  }
  if (guard) base += ` and (${guard})`;
  return base;
}

export function emitGo(prog, opts = {}) {
  const fnLines = [];
  for (const fn of prog.fns) {
    if (opts.__stubNames && opts.__stubNames.has(fn.name)) {
      fnLines.push(`func ${safeEmitId(snakeCase(fn.name))}(...interface{}) interface{} { panic("${fn.name}: js_runtime_only") }`);
      continue;
    }
    emitGoFn(fnLines, fn);
  }
  const lines = ['// generated by lin-rewrite → go'];
  lines.push('package main');
  const bodyText = fnLines.join('\n');
  const needsMath = /\bmath\.Abs\b|\bmath\.Floor\b/.test(bodyText);
  const needsFmt = true;
  lines.push('');
  lines.push('import (');
  if (needsFmt) lines.push('\t"fmt"');
  if (needsMath) lines.push('\t"math"');
  lines.push(')');
  lines.push('');
  lines.push(...fnLines);
  void opts;
  return lines.join('\n');
}

function goType(t) {
  if (t === '@str') return 'string';
  if (t === '@bool') return 'bool';
  switch (t) {
    case 'int': return 'int';
    case 'float': return 'float64';
    case 'string': return 'string';
    case 'bool': return 'bool';
    default: return 'interface{}';
  }
}

function zeroFor(t) {
  switch (goType(t)) {
    case 'int': return '0';
    case 'float64': return '0.0';
    case 'string': return '""';
    case 'bool': return 'false';
    default: return 'nil';
  }
}

function emitGoFn(lines, fn, opts) {
  prepareNativeFn(fn);
  const strP = new Set(strParamNames(fn));
  const ps = paramList(fn);
  for (const p of ps) if (strP.has(p.name)) p.type = '@str';
  const sig = ps.map((p) => `${safeEmitId(p.name)} ${goType(p.type)}`).join(', ');
  const retTypes = fn.returnType ? goType(normType(fn.returnType.replace(/^[^A-Za-z]+/, ''))) : (retIsBool(fn) ? 'bool' : 'interface{}');
  lines.push(`func ${safeEmitId(snakeCase(fn.name))}(${sig}) ${retTypes} {`);
  for (const p of ps) {
    if (p.def != null && p.def !== '' && goType(p.type) === 'interface{}') {
      lines.push(`\tif ${safeEmitId(p.name)} == nil { ${safeEmitId(p.name)} = ${p.def} }`);
    }
  }
  const locals = new Set();
  for (const st of fn.body) collectLocalsGo(st, locals, ps.map((p) => p.name));
  const lt = 'int';
  for (const l of locals) {
    lines.push(`\tvar ${safeEmitId(l)} ${lt}`);
  }
  lines.push(goStmts(fn.body, 1));
  lines.push('}');
  lines.push('');
}

function collectLocalsGo(st, locals, params) {
  const add = (id) => {
    if (!params.includes(id) && !['return', 'if', 'for', 'else'].includes(id)) locals.add(id);
  };
  if (st.type === 'assign' && /^[A-Za-z_$][\w$]*$/.test(st.idPath)) add(st.idPath);
  for (const key of ['then', 'else', 'body']) {
    if (Array.isArray(st[key])) for (const s2 of st[key]) collectLocalsGo(s2, locals, params);
  }
  if (Array.isArray(st.elseIf)) {
    for (const ei of st.elseIf) {
      for (const s2 of ei.body) collectLocalsGo(s2, locals, params);
      let tail = ei.chainTail;
      while (tail) {
        for (const s2 of tail.body) collectLocalsGo(s2, locals, params);
        tail = tail.chainTail;
      }
    }
  }
}

function goIndent(depth) {
  return '\t'.repeat(depth);
}

function goStmts(stmts, depth) {
  const out = [];
  const pad = goIndent(depth);
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${goExpr(goExprRaw(st.expr))}`);
        break;
      case 'throw':
        out.push(`${pad}panic(${goExpr(goExprRaw(st.expr))})`);
        break;
      case 'break':
        out.push(`${pad}break`);
        break;
      case 'continue':
        out.push(`${pad}continue`);
        break;
      case 'assign':
        out.push(`${pad}${safeEmitId(st.idPath)} ${st.op} ${stripDeclKw(goExpr(goExprRaw(st.rhs)))}`);
        break;
      case 'expr':
        out.push(`${pad}_ = ${stripDeclKw(goExpr(goExprRaw(st.expr)))}`);
        break;
      case 'if': {
        out.push(`${pad}if (${goExpr(goExprRaw(st.cond))}) {`);
        out.push(goStmts(st.then, depth + 1));
        let closed = false;
        for (const ei of st.elseIf || []) {
          out.push(`${pad}} else if (${goExpr(goExprRaw(ei.cond))}) {`);
          out.push(goStmts(collectChainBodies(ei), depth + 1));
          closed = true;
        }
        void closed;
        if (st.else) {
          out.push(`${pad}} else {`);
          out.push(goStmts(normalizeElse(st.else), depth + 1));
        }
        out.push(`${pad}}`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        const initPart = initM ? `${safeEmitId(initM[1])} := ${goExpr(initM[2])}; ` : '';
        const condPart = `(${goExpr(goExprRaw(st.cond))})`;
        const stepPart = stepM ? `; ${stepM[1]} ${stepM[2] === '++' ? '+=' : '-='} 1` : `; ${goExpr(st.step)}`;
        out.push(`${pad}for ${initPart}${condPart}${stepPart} {`);
        out.push(goStmts(st.body, depth + 1));
        out.push(`${pad}}`);
        break;
      }
      case 'while':
        out.push(`${pad}for (${goExpr(goExprRaw(st.cond))}) {`);
        out.push(goStmts(st.body, depth + 1));
        out.push(`${pad}}`);
        break;
      case 'match': {
        const target = goExpr(goExprRaw(st.target));
        for (let idx = 0; idx < st.arms.length; idx++) {
          const arm = st.arms[idx];
          const cond = goArmCond(target, arm.pat, arm.guard);
          const kw = idx === 0 ? 'if' : '} else if';
          if (idx === 0) out.push(`${pad}if ${cond} {`);
          else out.push(`${pad}${kw} ${cond} {`);
          out.push(goStmts(arm.body, depth + 1));
        }
        out.push(`${pad}}`);
        break;
      }
      default:
        throw new EmitUnsupportedError(`go stmt ${st.type}`);
    }
  }
  return out.join('\n');
}

function goArmCond(target, pat, guard) {
  if (pat === '_') return guard ? guard : 'true';
  const tupleMatch = pat.match(/^\(([^)]+)\)$/);
  let base;
  if (tupleMatch) {
    base = `isSlice(${target}) && sliceLen(${target}) >= ${tupleMatch[1].split(',').length}`;
  } else {
    base = `eqAny(${target}, ${pat})`;
  }
  if (guard) base += ` && (${guard})`;
  return base;
}

export function goExprRaw(expr) {
  return expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : goInline(p.node))).join(' ')
    : String(expr ?? '');
}

function goInline(node) {
  throw inlineErr('go', node);
}

export function goExpr(text) {
  let s = String(text);
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, 'int($1[$2])');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b/g, 'len($1)');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, '$1');
  s = s.replace(/\btypeof\s+([A-Za-z_$][\w$]*)/g, 'goTypeOf($1)');
  s = s.replace(/\bundefined\b|\bnull\b/g, 'nil');
  s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
  s = s.replace(/\bMath\.abs\(/g, 'math.Abs(');
  s = s.replace(/\bMath\.floor\(/g, 'math.Floor(');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\s*&&\s*/g, ' && ').replace(/\s*\|\|\s*/g, ' || ');
  s = s.replace(/!(?=[A-Za-z_(])/g, '!');
  s = s.replace(/\?/g, '');
  return s;
}

export function emitRust(prog, opts = {}) {
  const lines = ['// generated by lin-rewrite → rust'];
  lines.push('#![allow(dead_code, unused_variables, unused_mut)]');
  lines.push('');
  for (const fn of prog.fns) {
    if (opts.__stubNames && opts.__stubNames.has(fn.name)) {
      lines.push(`pub fn ${snakeCaseRust(fn.name)}() -> i64 { panic!("${fn.name}: js_runtime_only"); }`);
      continue;
    }
    emitRustFn(lines, fn);
  }
  void opts;
  return lines.join('\n');
}

function rustType(t) {
  if (t === '@str') return '&str';
  if (t === '@bool') return 'bool';
  switch (normType(t)) {
    case 'int': return 'i64';
    case 'float': return 'f64';
    case 'string': return 'String';
    case 'bool': return 'bool';
    default: return 'i64';
  }
}

function rustZero(t) {
  switch (rustType(t)) {
    case 'i64': return '0';
    case 'f64': return '0.0';
    case 'String': return 'String::new()';
    case 'bool': return 'false';
    default: return '0';
  }
}

function emitRustFn(lines, fn) {
  prepareNativeFn(fn);
  const strP = new Set(strParamNames(fn));
  const isBool = retIsBool(fn);
  const ps = paramList(fn);
  if (ps.some((p) => !p.type)) {
    for (const p of ps) {
      if (!p.type) p.type = strP.has(p.name) ? '@str' : inferRustParamType({ ...fn, rawBody: stmtsText(fn), __bodyText: null, body: fn.body }, p.name);
      if (!p.type || p.type === 'int') {
        const t2 = stmtsText(fn);
        if (new RegExp(`\\b${p.name}\\.len\\(|\\bas_bytes`).test('')) {}
      }
    }
  } else {
    for (const p of ps) if (strP.has(p.name)) p.type = '@str';
  }
  if (!fn.returnType && isBool) fn.__forceBoolRet = true;
  const reassigned = new Set();
  const walkAssignsRust = (stmts) => {
    for (const st of stmts) {
      if (st.type === 'assign' && /^[A-Za-z_$][\w$]*$/.test(st.idPath)) reassigned.add(st.idPath);
      for (const key of ['then', 'else', 'body']) {
        if (Array.isArray(st[key])) walkAssignsRust(st[key], reassigned);
      }
      if (Array.isArray(st.elseIf)) for (const ei of st.elseIf) walkAssignsRust(ei.body, reassigned);
    }
  };
  walkAssignsRust(fn.body, reassigned);
  const strCount = ps.filter((p) => rustType(p.type) === '&str').length;
  const lifetime = strCount >= 2 ? "<'a>" : '';
  const lt = strCount >= 2 ? "'a " : '';
  const sig = ps.map((p) => `${reassigned.has(p.name) ? 'mut ' : ''}${safeEmitId(p.name)}: ${rustType(p.type).replace('&str', "&'a str")}`).join(', ');
  const generics = lifetime;
  let retKw = fn.returnType ? rustType(fn.returnType.replace(/^[^A-Za-z]+/, '')) : null;
  if (!retKw && fn.__forceBoolRet) retKw = 'bool';
  if (!retKw) retKw = rustType(ps[0] ? ps[0].type : 'int');
  const ret = ` -> ${retKw}`;
  lines.push(`pub fn ${snakeCaseRust(fn.name)}${generics}(${sig})${ret} {`);
  const locals = new Set();
  for (const st of fn.body) collectLocalsGo(st, locals, ps.map((p) => p.name));
  if (locals.size) {
    lines.push(`    let mut ${[...locals].map(safeEmitId).join(' = ' + rustZero(ps[0] ? ps[0].type : 'int') + '; let mut ') } = ${rustZero(ps[0] ? ps[0].type : 'int')};`);
  }
  lines.push(rustStmts(fn.body, 1, fn));
  lines.push('}');
  lines.push('');
}

function snakeCaseRust(name) {
  return snakeCase(name);
}

function inferRustParamType(fn, name) {
  const text = stmtsText(fn);
  if (new RegExp(`\\b${name}\\b[^\\n]*\\.charCodeAt|\\.length`).test(text)) return 'string';
  return 'int';
}

function rustIndent(d) {
  return '    '.repeat(d);
}

function rustStmts(stmts, depth, fn) {
  void fn;
  const out = [];
  const pad = rustIndent(depth);
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${rustExpr(rustRaw(st.expr))};`);
        break;
      case 'throw':
        out.push(`${pad}panic!(${rustExpr(rustRaw(st.expr))});`);
        break;
      case 'break':
        out.push(`${pad}break;`);
        break;
      case 'continue':
        out.push(`${pad}continue;`);
        break;
      case 'assign':
        out.push(`${pad}${safeEmitId(st.idPath)} ${st.op === '=' ? '=' : rustCompound(st.op)} ${stripDeclKw(rustExpr(rustRaw(st.rhs)))};`);
        break;
      case 'expr':
        out.push(`${pad}${stripDeclKw(rustExpr(rustRaw(st.expr)))};`);
        break;
      case 'if': {
        out.push(`${pad}if ${rustExpr(rustRaw(st.cond))} {`);
        out.push(rustStmts(st.then, depth + 1, fn));
        for (const ei of st.elseIf || []) {
          out.push(`${pad}} else if ${rustExpr(rustRaw(ei.cond))} {`);
          out.push(rustStmts(collectChainBodies(ei), depth + 1, fn));
        }
        if (st.else) {
          out.push(`${pad}} else {`);
          out.push(rustStmts(normalizeElse(st.else), depth + 1, fn));
        }
        out.push(`${pad}}`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        if (initM) out.push(`${pad}let mut ${safeEmitId(initM[1])} = ${rustExpr(initM[2])};`);
        out.push(`${pad}while ${rustExpr(rustRaw(st.cond))} {`);
        const inner = [];
        if (stepM) {
          inner.push(`${rustIndent(depth + 1)}${safeEmitId(stepM[1])} ${stepM[2] === '++' ? '+' : '-'}= 1;`);
        } else if (st.step.trim()) {
          inner.push(`${rustIndent(depth + 1)}${rustExpr(st.step)};`);
        }
        out.push(rustStmts(st.body, depth + 1, fn));
        out.push(...inner);
        out.push(`${pad}}`);
        break;
      }
      case 'while':
        out.push(`${pad}while ${rustExpr(rustRaw(st.cond))} {`);
        out.push(rustStmts(st.body, depth + 1, fn));
        out.push(`${pad}}`);
        break;
      case 'match':
        emitRustMatch(out, st, depth, fn);
        break;
      default:
        throw new EmitUnsupportedError(`rust stmt ${st.type}`);
    }
  }
  return out.join('\n');
}

function rustCompound(op) {
  if (op === '|=') return '|=';
  if (op === '&=') return '&=';
  if (op === '^=') return '^=';
  if (op === '+=') return '+=';
  if (op === '-=') return '-=';
  if (op === '*=') return '*=';
  if (op === '/=') return '/=';
  if (op === '%=') return '%=';
  return '=';
}

function emitRustMatch(out, st, depth, fn) {
  const pad = rustIndent(depth);
  const target = safeEmitId(rustRaw(st.target).trim());
  const allLiteral = st.arms.every((a) => /^[-\w"'().,\s|]+$/.test(a.pat) && !/[{}]/.test(a.pat));
  if (allLiteral) {
    out.push(`${pad}match ${target} {`);
    for (const arm of st.arms) {
      const pat = arm.pat === '_' ? '_'.replace('_', '_ =>'.slice(0, 1)) : arm.pat;
      const armPat = arm.pat === '_' ? '_ =>' : `${arm.pat} =>`;
      void pat;
      out.push(`${pad}    ${armPat} {`);
      const body = rustStmts(arm.body, depth + 2, fn);
      out.push(body);
      out.push(`${pad}    }`);
    }
    out.push(`${pad}}`);
    return;
  }
  for (let idx = 0; idx < st.arms.length; idx++) {
    const arm = st.arms[idx];
    const cond = rustArmCond(target, arm.pat, arm.guard);
    if (idx === 0) out.push(`${pad}if ${cond} {`);
    else out.push(`${pad}} else if ${cond} {`);
    out.push(rustStmts(arm.body, depth + 1, fn));
  }
  out.push(`${pad}}`);
}

function rustArmCond(target, pat, guard) {
  if (pat === '_') return guard ? guard : 'true';
  const enumMatch = pat.match(/^([A-Za-z_$][\w$]*)\(([^)]+)\)$/);
  let base;
  if (enumMatch) {
    const tag = enumMatch[1];
    const v = safeEmitId(enumMatch[2].trim());
    base = `matches_tag(&${target}, "${tag}") /* bind ${v} */`;
  } else {
    base = `${target} == ${pat}`;
  }
  if (guard) base += ` && (${guard})`;
  return base;
}

function rustRaw(expr) {
  return expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : rustInline(p.node))).join(' ')
    : String(expr ?? '');
}

function rustInline(node) {
  throw inlineErr('rust', node);
}

export function rustExpr(text) {
  let s = String(text);
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, '($1.as_bytes()[$2 as usize] as i64)');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b/g, '$1.len() as i64');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, '$1');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
  s = s.replace(/\bMath\.abs\(/g, 'i64::abs(');
  s = s.replace(/!(?=[A-Za-z_(])/g, '!');
  s = s.replace(/\?/g, '');
  return s;
}

export function emitC(prog, opts = {}) {
  const lines = ['/* generated by lin-rewrite → c */'];
  lines.push('#include <stdio.h>');
  lines.push('#include <stdlib.h>');
  lines.push('#include <string.h>');
  lines.push('#include <math.h>');
  lines.push('');
  for (const fn of prog.fns) {
    if (opts.__stubNames && opts.__stubNames.has(fn.name)) {
      lines.push(`long long ${snakeCase(fn.name)}() { fprintf(stderr, "${fn.name}: js_runtime_only\\n"); exit(70); }`);
      continue;
    }
    emitCFn(lines, fn, prog);
  }
  void opts;
  return lines.join('\n');
}

function cType(t) {
  if (t === '@arr') return 'long long*';
  if (t === '@cb') return 'char*';
  if (t === '@str') return 'char*';
  switch (normType(t)) {
    case 'int': return 'long long';
    case 'float': return 'double';
    case 'bool': return 'int';
    default: return 'long long';
  }
}

function cZero(t) {
  if (t === 'const char*') return '""';
  switch (cType(t)) {
    case 'double': return '0.0';
    case 'long long': return '0';
    default: return '0';
  }
}

function splitTopC(raw) {
  const out = [];
  let d = 0, cur = '';
  for (const ch of String(raw)) {
    if (ch === '[' || ch === '(') d++;
    else if (ch === ']' || ch === ')') d--;
    if (ch === ',' && d === 0) { out.push(cur.trim()); cur = ''; }
    else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

function lhsC(idPath) {
  const m = /^([A-Za-z_$][\w$]*)\[([\s\S]+)\]$/.exec(String(idPath || '').trim());
  if (!m) return safeEmitId(idPath);
  return `${safeEmitId(m[1])}[${cExpr(m[2])}]`;
}

function collectArrLocals(st, map, params) {
  const reg = (id, len) => { if (!params.includes(id)) map.set(id, len); };
  if (st.type === 'assign' && st.op === '=') {
    const rhsT = String(st.rhs && st.rhs.parts ? cRaw(st.rhs) : st.rhs ?? '').trim();
    const im = /^([A-Za-z_$][\w$]*)\[/.exec(st.idPath);
    if (im && !/^[A-Za-z_$][\w$]*$/.test(st.idPath) && !map.has(im[1])) reg(im[1], 64);
    if (/^\[[\s\S]*\]$/.test(rhsT) && /^[A-Za-z_$][\w$]*$/.test(st.idPath)) {
      const items = rhsT.slice(1, -1).trim();
      const parts = items === '' ? [] : splitTopC(items);
      reg(st.idPath, Math.max(parts.length, 1));
    }
  }
  for (const key of ['then', 'else', 'body']) {
    if (Array.isArray(st[key])) for (const s2 of st[key]) collectArrLocals(s2, map, params);
  }
  if (Array.isArray(st.elseIf)) {
    for (const ei of st.elseIf) {
      for (const s2 of ei.body) collectArrLocals(s2, map, params);
      let tail = ei.chainTail;
      while (tail) { for (const s2 of tail.body) collectArrLocals(s2, map, params); tail = tail.chainTail; }
    }
  }
}

function emitCFn(lines, fn, prog) {
  prepareNativeFn(fn);
  const ps0 = paramList(fn);
  const textHint = stmtsText(fn);
  const heur = new Set(strParamNames(fn));
  const ps = paramList(fn);
  for (const p of ps) {
    if (p.rawType === 's') p.type = '@str';
    else if (p.rawType === 'cb') p.type = '@cb';
    else if (p.arr) p.type = '@arr';
    else if (heur.has(p.name)) p.type = '@str';
    else if (!p.type || p.type === 'any' || p.type === 'string') p.type = 'int';
  }
  const sig = ps.map((p) => `${cType(p.type)} ${safeEmitId(p.name)}`).join(', ');
  const ret = fn.returnType ? cType(fn.returnType.replace(/^[^A-Za-z]+/, '')) : (retIsBool(fn) ? 'int' : 'long long');
  lines.push(`${ret} ${snakeCase(fn.name)}(${sig}) {`);
  const paramNames = ps.map((p) => p.name);
  const arrLocals = new Map();
  for (const st of fn.body) collectArrLocals(st, arrLocals, paramNames);
  const sigMap = new Map();
  for (const f2 of prog.fns || []) {
    sigMap.set(f2.name, new Set((f2.params || []).map((pp, ix4) => (pp.isArray ? ix4 : -1)).filter((x4) => x4 >= 0)));
  }
  {
    const texts = [];
    (function tw(list) {
      for (const q of list || []) {
        const toT = (v2) => String(v2 && v2.parts ? cRaw(v2) : v2 || '');
        texts.push(toT(q.expr), toT(q.cond), toT(q.rhs));
        tw(q.then); tw(q.elseIf?.map((e3) => e3.body)); tw(q.else); tw(q.body);
      }
    })(fn.body);
    for (const tx of texts) {
      if (!tx) continue;
      let mm5;
      const cre = /\b([A-Za-z_$][\w$]*)\s*\(([^()]*?)\)/g;
      while ((mm5 = cre.exec(tx))) {
        const posset = sigMap.get(mm5[1]);
        if (!posset || !posset.size) continue;
        const args2 = splitTopC(mm5[2]);
        for (const pos of posset) {
          if (pos < args2.length) {
            const aid = args2[pos].trim();
            if (/^[A-Za-z_$][\w$]*$/.test(aid) && !paramNames.includes(aid)) arrLocals.set(aid, 64);
          }
        }
      }
    }
  }
  for (const [name2, len2] of arrLocals) lines.push(`    long long ${safeEmitId(name2)}[${len2}] = {0};`);
  const locals = new Set();
  for (const st of fn.body) collectLocalsGo(st, locals, paramNames);
  for (const l of locals) {
    if (arrLocals.has(l)) continue;
    lines.push(`    long long ${safeEmitId(l)} = 0;`);
  }
  lines.push(cStmts(fn.body, 1, fn));
  lines.push('}');
  lines.push('');
}

function cIndent(d) {
  return '    '.repeat(d);
}

function cStmts(stmts, depth, fn) {
  const out = [];
  const pad = cIndent(depth);
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${cExpr(cRaw(st.expr))};`);
        break;
      case 'throw':
        throw new EmitUnsupportedError('c: throw');
      case 'break':
        out.push(`${pad}break;`);
        break;
      case 'continue':
        out.push(`${pad}continue;`);
        break;
      case 'assign': {
        const rhsT = String(st.rhs && st.rhs.parts ? cRaw(st.rhs) : st.rhs ?? '').trim();
        if (st.op === '=' && /^\[[\s\S]*\]$/.test(rhsT) && /^[A-Za-z_$][\w$]*$/.test(st.idPath)) {
          const els = splitTopC(rhsT.slice(1, -1));
          els.forEach((el, ix3) => out.push(`${pad}${lhsC(st.idPath)}[${ix3}] = ${stripDeclKw(cExpr(el))};`));
          break;
        }
        out.push(`${pad}${lhsC(st.idPath)} ${cOp(st.op)} ${stripDeclKw(cExpr(cRaw(st.rhs)))};`);
        break;
      }
      case 'expr':
        out.push(`${pad}${stripDeclKw(cExpr(cRaw(st.expr)))};`);
        break;
      case 'if': {
        out.push(`${pad}if (${cExpr(cRaw(st.cond))}) {`);
        out.push(cStmts(st.then, depth + 1, fn));
        for (const ei of st.elseIf || []) {
          out.push(`${pad}} else if (${cExpr(cRaw(ei.cond))}) {`);
          out.push(cStmts(collectChainBodies(ei), depth + 1, fn));
        }
        if (st.else) {
          out.push(`${pad}} else {`);
          out.push(cStmts(normalizeElse(st.else), depth + 1, fn));
        }
        out.push(`${pad}}`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        const init = initM ? `long long ${initM[1]} = ${cExpr(initM[2])}` : '';
        const step = stepM ? `${stepM[1]}${stepM[2] === '++' ? '++' : '--'}` : cExpr(st.step);
        out.push(`${pad}for (${init}; ${cExpr(cRaw(st.cond))}; ${step}) {`);
        out.push(cStmts(st.body, depth + 1, fn));
        out.push(`${pad}}`);
        break;
      }
      case 'while':
        out.push(`${pad}while (${cExpr(cRaw(st.cond))}) {`);
        out.push(cStmts(st.body, depth + 1, fn));
        out.push(`${pad}}`);
        break;
      case 'match':
        throw new EmitUnsupportedError('c: match');
      default:
        throw new EmitUnsupportedError(`c stmt ${st.type}`);
    }
  }
  return out.join('\n');
}

function cOp(op) {
  return op;
}

function cRaw(expr) {
  return expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : cInline(p.node))).join(' ')
    : String(expr ?? '');
}

function cInline(node) {
  throw inlineErr('c', node);
}

export function cExpr(text) {
  let s = String(text);
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, '((long long)(unsigned char)$1[(int)($2)])');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b/g, '((long long)strlen($1))');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, '(char*)($1)');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\btrue\b/g, '1').replace(/\bfalse\b/g, '0');
  return s;
}

export function emitJava(prog, opts = {}) {
  const lines = ['// generated by lin-rewrite → java'];
  lines.push('public class LinProgram {');
  for (const fn of prog.fns) {
    if (opts.__stubNames && opts.__stubNames.has(fn.name)) {
      lines.push(`  public static long ${safeEmitId(snakeCase(fn.name))}() { throw new UnsupportedOperationException("${fn.name}: js_runtime_only"); }`);
      continue;
    }
    emitJavaFn(lines, fn);
  }
  lines.push('  public static void main(String[] args) {');
  lines.push('  }');
  lines.push('}');
  void opts;
  return lines.join('\n');
}

function javaType(t) {
  if (t === '@str') return 'String';
  if (t === '@bool') return 'boolean';
  switch (normType(t)) {
    case 'int': return 'long';
    case 'float': return 'double';
    case 'bool': return 'boolean';
    case 'string': return 'String';
    default: return 'long';
  }
}

function javaZero(t) {
  switch (javaType(t)) {
    case 'long': return '0L';
    case 'double': return '0.0';
    case 'boolean': return 'false';
    case 'String': return '""';
    default: return '0L';
  }
}

function emitJavaFn(lines, fn) {
  prepareNativeFn(fn);
  if (process.env.DBG2) console.error('JAVA FN', fn.name, 'bodyText:', JSON.stringify(stmtsText(fn).slice(0,60)), 'strP:', [...strParamNames(fn)]);
  const strP = new Set(strParamNames(fn));
  const isBool = retIsBool(fn);
  const ps = paramList(fn);
  for (const p of ps) {
    if (strP.has(p.name)) p.type = '@str';
    else if (!p.type || p.type === 'any') p.type = 'int';
  }
  const sig = ps.map((p) => `${javaType(p.type)} ${safeEmitId(p.name)}`).join(', ');
  let retT = fn.returnType ? fn.returnType.replace(/^[^A-Za-z]+/, '') : null;
  if (!retT && isBool) retT = '@bool';
  const ret = retT ? javaType(retT) : javaType(ps[0] && !strP.has(ps[0].name) ? ps[0].type : 'int');
  lines.push(`  public static ${ret} ${safeEmitId(snakeCase(fn.name))}(${sig}) {`);
  const locals = new Set();
  for (const st of fn.body) collectLocalsGo(st, locals, ps.map((p) => p.name));
  for (const l of locals) {
    const pt = ps.find((p) => p.name === l)?.type || 'int';
    lines.push(`    ${javaType(pt)} ${safeEmitId(l)} = ${javaZero(pt)};`);
  }
  lines.push(javaStmts(fn.body, 2, fn));
  lines.push('  }');
}

function javaIndent(d) {
  return '  '.repeat(d);
}

function javaStmts(stmts, depth, fn) {
  const out = [];
  const pad = javaIndent(depth);
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${javaExpr(javaRaw(st.expr))};`);
        break;
      case 'throw':
        throw new EmitUnsupportedError('java: throw (use unchecked)');
      case 'break':
        out.push(`${pad}break;`);
        break;
      case 'continue':
        out.push(`${pad}continue;`);
        break;
      case 'assign':
        out.push(`${pad}${safeEmitId(st.idPath)} ${st.op} ${stripDeclKw(javaExpr(javaRaw(st.rhs)))};`);
        break;
      case 'expr':
        out.push(`${pad}${stripDeclKw(javaExpr(javaRaw(st.expr)))};`);
        break;
      case 'if': {
        out.push(`${pad}if (${javaExpr(javaRaw(st.cond))}) {`);
        out.push(javaStmts(st.then, depth + 1, fn));
        for (const ei of st.elseIf || []) {
          out.push(`${pad}} else if (${javaExpr(javaRaw(ei.cond))}) {`);
          out.push(javaStmts(collectChainBodies(ei), depth + 1, fn));
        }
        if (st.else) {
          out.push(`${pad}} else {`);
          out.push(javaStmts(normalizeElse(st.else), depth + 1, fn));
        }
        out.push(`${pad}}`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        const init = initM ? `long ${initM[1]} = ${javaExpr(initM[2])}` : '';
        const step = stepM ? `${stepM[1]}${stepM[2] === '++' ? '++' : '--'}` : javaExpr(st.step);
        out.push(`${pad}for (${init}; ${javaExpr(javaRaw(st.cond))}; ${step}) {`);
        out.push(javaStmts(st.body, depth + 1, fn));
        out.push(`${pad}}`);
        break;
      }
      case 'while':
        out.push(`${pad}while (${javaExpr(javaRaw(st.cond))}) {`);
        out.push(javaStmts(st.body, depth + 1, fn));
        out.push(`${pad}}`);
        break;
      case 'match': {
        const target = safeEmitId(javaRaw(st.target).trim());
        for (let idx = 0; idx < st.arms.length; idx++) {
          const arm = st.arms[idx];
          const cond = javaArmCond(target, arm.pat, arm.guard);
          if (idx === 0) out.push(`${pad}if (${cond}) {`);
          else out.push(`${pad}} else if (${cond}) {`);
          out.push(javaStmts(arm.body, depth + 1, fn));
        }
        out.push(`${pad}}`);
        break;
      }
      default:
        throw new EmitUnsupportedError(`java stmt ${st.type}`);
    }
  }
  return out.join('\n');
}

function javaArmCond(target, pat, guard) {
  if (pat === '_') return guard ? guard : 'true';
  let base = `${target} == ${pat}`;
  if (guard) base += ` && (${guard})`;
  return base;
}

function javaRaw(expr) {
  return expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : javaInline(p.node))).join(' ')
    : String(expr ?? '');
}

function javaInline(node) {
  throw inlineErr('java', node);
}

export function javaExpr(text) {
  let s = String(text);
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, '(int)($1.charAt((int)($2)))');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b(?!\()/g, '$1.length()');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, 'String.valueOf($1)');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
  return s;
}

/* ─────────────── zig ─────────────── */

export function emitZig(prog, opts = {}) {
  const fnLines = [];
  let needsCache = false;
  for (const fn of prog.fns) {
    if (opts.__stubNames && opts.__stubNames.has(fn.name)) {
      fnLines.push(`pub fn ${safeEmitId(snakeCase(fn.name))}() i64 { @panic("${fn.name}: js_runtime_only"); }`);
      continue;
    }
    if (/\bcache\b/.test(stmtsText(fn))) needsCache = true;
    emitZigFn(fnLines, fn);
  }
  const lines = ['// generated by lin-rewrite → zig'];
  lines.push('const std = @import("std");');
  lines.push('pub var LIA_ALLOC: std.mem.Allocator = undefined;');
  lines.push('');
  lines.push(ZIG_RUNTIME);
  if (prog.consts) {
    for (const [k, v] of Object.entries(prog.consts)) lines.push(`const ${safeEmitId(k)}: i64 = ${Number(v)};`);
  }
  if (needsCache) {
    lines.push('var cache = [_][]const u8{ "", " ", "  ", "   ", "    ", "     ", "      ", "       ", "        ", "         " };');
  }
  lines.push('');
  lines.push(...fnLines);
  void opts;
  return lines.join('\n');
}

const ZIG_RUNTIME = `fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    if (T == []const u8) return x;
    if (T == []u8) return x;
    if (T == bool) return if (x) "true" else "false";
    return switch (@typeInfo(T)) {
        .int, .comptime_int => std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .float, .comptime_float => std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => "",
    };
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_eqs(a: []const u8, b: []const u8) bool {
    return std.mem.eql(u8, a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    if (T == []const u8 or T == []u8) return @as(i64, @intCast(x.len));
    return 0;
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}`;

function zigType(t) {
  if (t === '@str') return '[]const u8';
  if (t === '@bool') return 'bool';
  switch (normType(t)) {
    case 'int': return 'i64';
    case 'float': return 'f64';
    case 'string': return '[]const u8';
    case 'bool': return 'bool';
    default: return 'i64';
  }
}

function zigZero(t) {
  switch (zigType(t)) {
    case 'f64': return '0.0';
    case '[]const u8': return '""';
    case 'bool': return 'false';
    default: return '0';
  }
}

function retIsStringy(fn) {
  const text = stmtsText(fn);
  const rets = text.match(/\breturn\s+([^;{}]+)/g) || [];
  return rets.some((rr) => rr.includes('"') || rr.includes("'") || /_lia_cat/.test(rr));
}

function emitZigFn(lines, fn) {
  prepareNativeFn(fn);
  const strP = new Set(strParamNames(fn));
  const isBool = retIsBool(fn);
  const ps = paramList(fn);
  for (const p of ps) {
    if (strP.has(p.name)) p.type = '@str';
    else if (!p.type || p.type === 'any') p.type = 'int';
  }
  const sig = ps.map((p) => `${safeEmitId(p.name)}: ${zigType(p.type)}`).join(', ');
  let retT = fn.returnType ? zigType(fn.returnType.replace(/^[^A-Za-z]+/, '')) : null;
  if (!retT && isBool) retT = 'bool';
  if (!retT && retIsStringy(fn)) retT = '[]const u8';
  if (!retT) retT = zigType(ps[0] ? ps[0].type : 'int');
  const stringIds = new Set();
  for (const p of ps) if (zigType(p.type) === '[]const u8') stringIds.add(p.name);
  const ctx = { stringIds, params: ps };
  lines.push(`pub fn ${safeEmitId(snakeCase(fn.name))}(${sig}) ${retT} {`);
  const locals = new Set();
  for (const st of fn.body) collectLocalsGo(st, locals, ps.map((p) => p.name));
  const bodyRaw = zigStmts(fn.body, 1, ctx);
  for (const p of ps) {
    const pId = safeEmitId(p.name);
    const reUsed = new RegExp(`\\b${pId}\\b`, 'm');
    if (!reUsed.test(bodyRaw)) {
      lines.push(`    _ = ${pId};`);
    }
  }
  for (const l of locals) {
    let t = 'i64';
    const reAssign = new RegExp(`\\b${l}\\b\\s*=\\s*([^;\\n]+)`, 'm').exec(bodyRaw);
    if (reAssign && /"|_lia_cat\(|String\(/.test(reAssign[1])) t = '[]const u8';
    else if (reAssign && /^(true|false)\b/.test(reAssign[1].trim())) t = 'bool';
    if (t === '[]const u8' || t === '') {} 
    const sid = safeEmitId(l);
    if (t === '[]const u8') ctx.stringIds.add(l);
    lines.push(`    var ${sid}: ${t} = ${t === '[]const u8' ? '""' : t === 'bool' ? 'false' : '0'};`);
  }
  lines.push(bodyRaw);
  lines.push('}');
  lines.push('');
}

function zigIndent(d) {
  return '    '.repeat(d);
}

function zigStmts(stmts, depth, ctx) {
  const out = [];
  const pad = zigIndent(depth);
  for (const st of stmts) {
    switch (st.type) {
      case 'return':
        out.push(`${pad}return ${zigExpr(zigRaw(st.expr), ctx)};`);
        break;
      case 'throw':
        out.push(`${pad}@panic(${zigExpr(zigRaw(st.expr), ctx)});`);
        break;
      case 'break':
        out.push(`${pad}break;`);
        break;
      case 'continue':
        out.push(`${pad}continue;`);
        break;
      case 'assign':
        out.push(`${pad}${safeEmitId(st.idPath)} ${st.op} ${stripDeclKw(zigExpr(zigRaw(st.rhs), ctx))};`);
        break;
      case 'expr':
        out.push(`${pad}_ = ${stripDeclKw(zigExpr(zigRaw(st.expr), ctx))};`);
        break;
      case 'if': {
        out.push(`${pad}if (${zigCond(st.cond, ctx)}) {`);
        out.push(zigStmts(st.then, depth + 1, ctx));
        for (const ei of st.elseIf || []) {
          out.push(`${pad}} else if (${zigCond(ei.cond, ctx)}) {`);
          out.push(zigStmts(collectChainBodies(ei), depth + 1, ctx));
        }
        if (st.else) {
          out.push(`${pad}} else {`);
          out.push(zigStmts(normalizeElse(st.else), depth + 1, ctx));
        }
        out.push(`${pad}}`);
        break;
      }
      case 'for': {
        const initM = st.init.match(/^([A-Za-z_$][\w$]*)\s*=\s*([\s\S]+)$/);
        const stepM = st.step.match(/^([A-Za-z_$][\w$]*)\s*(\+\+|--)$/);
        if (initM) out.push(`${pad}var ${safeEmitId(initM[1])}: i64 = ${zigExpr(initM[2], ctx)};`);
        const cont = stepM ? ` : (${safeEmitId(stepM[1])} ${stepM[2] === '++' ? '+=' : '-='} 1)` : '';
        out.push(`${pad}while (${zigCond(st.cond, ctx)})${cont} {`);
        out.push(zigStmts(st.body, depth + 1, ctx));
        if (!stepM && st.step.trim()) out.push(`${pad}    ${zigExpr(st.step, ctx)};`);
        out.push(`${pad}}`);
        break;
      }
      case 'while':
        out.push(`${pad}while (${zigCond(st.cond, ctx)}) {`);
        out.push(zigStmts(st.body, depth + 1, ctx));
        out.push(`${pad}}`);
        break;
      case 'match': {
        const target = safeEmitId(zigRaw(st.target).trim());
        for (let idx = 0; idx < st.arms.length; idx++) {
          const arm = st.arms[idx];
          const cond = zigArmCond(target, arm.pat, arm.guard, ctx);
          if (idx === 0) out.push(`${pad}if (${cond}) {`);
          else out.push(`${pad}} else if (${cond}) {`);
          out.push(zigStmts(arm.body, depth + 1, ctx));
        }
        out.push(`${pad}}`);
        break;
      }
      default:
        throw new EmitUnsupportedError(`zig stmt ${st.type}`);
    }
  }
  return out.join('\n');
}

function zigArmCond(target, pat, guard, ctx) {
  if (pat === '_') return guard ? guard : 'true';
  let base = `${zigEqFold(target, pat.trim(), '==', ctx)}`;
  if (guard) base += ` and (${guard})`;
  return base;
}

function zigCond(cond, ctx) {
  let s = zigExpr(zigRaw(cond), ctx);
  if (/^(true|false)$/.test(s.trim())) return s.trim();
  return s;
}

function zigRaw(expr) {
  return expr && expr.parts
    ? expr.parts.map((p) => (p.kind === 'raw' ? p.text : zigInline(p.node))).join(' ')
    : String(expr ?? '');
}

function zigInline(node) {
  throw new EmitUnsupportedError(`zig inline ${node.kind}`);
}

function inlineErr(target, node) {
  const tag = node && node.kind === 'regex' ? 'regex (LIN_REGEX_001: backend pendente; subconjunto portável roadmap)' : node && node.kind;
  return new EmitUnsupportedError(`${target} inline ${tag}`);
}

function isStrLit(t) {
  return /^"[^"]*"$/.test(String(t || '').trim());
}

function zigEqFold(a, b, op, ctx) {
  const A = String(a).trim();
  const B = String(b).trim();
  const strA = isStrLit(A) || ctx.stringIds.has(A.replace(/^\(|\)$/g, '')) || /^[A-Za-z_][\w]*$/.test(A) && !/^(\d|0x)/.test(A) && ctx.stringIds.has(A);
  const strB = isStrLit(B) || ctx.stringIds.has(B.replace(/^\(|\)$/g, '')) || /^[A-Za-z_][\w]*$/.test(B) && !/^(\d|0x)/.test(B) && ctx.stringIds.has(B);
  if ((isStrLit(A) || ctx.stringIds.has(A)) && (isStrLit(B) || ctx.stringIds.has(B))) {
    const eq = `_lia_eqs(${A}, ${B})`;
    return op === '!=' ? `!(${eq})` : eq;
  }
  void strA; void strB;
  return `${A} ${op} ${B}`;
}

export function zigExpr(text, ctx) {
  let s = String(text);
  s = s.replace(/([A-Za-z_$][\w$]*)\.charCodeAt\(([^()]*)\)/g, '@as(i64, $1[$2])');
  s = s.replace(/([A-Za-z_$][\w$]*)\.length\b/g, '@as(i64, @intCast($1.len))');
  s = s.replace(/String\(([A-Za-z_$][\w$]*)\)/g, '$1');
  s = s.replace(/\bMath\.abs\(/g, '@abs(');
  s = s.replace(/\bMath\.round\s*\(\s*([\s\S]+?)\s*\/\s*([\s\S]+?)\s*\)/g, '@divTrunc($1, $2)');
  s = s.replace(/\bMath\.floor\(/g, '@divTrunc(');
  s = s.replace(/JSON\.stringify\(([^()]*)\)/g, '$1');
  s = s.replace(/===/g, '==').replace(/!==/g, '!=');
  s = s.replace(/\btrue\b/g, 'true').replace(/\bfalse\b/g, 'false');
  s = s.replace(/\bnull\b|\bundefined\b/g, '""');
  s = s.replace(/\?(?!=)/g, '');
  s = s.replace(/&&/g, ' and ').replace(/\|\|/g, ' or ');
  s = s.replace(/([\w."']+)\s*%\s*([\w."']+)/g, '@rem($1, $2)');
  s = s.replace(/([\w."']+)\s*\/\s*([\w."']+)/g, '@divTrunc($1, $2)');
  // string-aware equality rewrite
  let prevEq;
  do {
    prevEq = s;
    s = s.replace(/([\w."']+)\s*(==|!=)\s*([\w."']+)/g, (m, a, op, b) => {
      if (op !== '==' && op !== '!=') return m;
      const litSide = isStrLit(a) || isStrLit(b);
      const idSide = ctx.stringIds.has(a) || ctx.stringIds.has(b);
      if (!litSide && !idSide) return m;
      return zigEqFold(a, b, op, ctx);
    });
  } while (s !== prevEq);
  // concat fold: X + Y where either side is a string literal or known string id
  let prevCat;
  do {
    prevCat = s;
    s = s.replace(/([\w."'@()\[\]]+(?:\([^()]*\))?)\s*\+\s*([\w."'@()\[\]]+(?:\([^()]*\))?)/g, (m, a, b) => {
      const strish = isStrLit(a) || isStrLit(b) || ctx.stringIds.has(a) || ctx.stringIds.has(b) || /_lia_cat\(/.test(a) || /_lia_cat\(/.test(b) || /@divTrunc\(/.test(a) || /@divTrunc\(/.test(b);
      if (!strish) return m;
      return `_lia_cat(${a}, ${b})`;
    });
  } while (s !== prevCat);
  return s;
}
