// generated by LIN Zig bootstrap — host for LIN compiling LIN
const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;

fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| {
                        if (a.child == u8) return x[0..];
                    },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a << shift;
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}

// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
// generated by LIN Zig bootstrap
pub fn slice2(s: []const u8, a: i64, b: i64) []const u8 {
 return _lia_slice(s, a, b) ;
}

pub fn skip_ws(s: []const u8, i: i64) i64 {
    var n: i64 = 0;
    var p: i64 = 0;
    var c: i64 = 0;

  n = @as(i64, @intCast(s.len));
  p = i;
  while (p < n) {
    c = _lia_char_code_at(s, p);
    if (c == 32  or  c == 9  or  c == 10  or  c == 13) { p = p + 1 ;}
     else if (c == 47  and  p + 1 < n  and  _lia_char_code_at(s, p + 1) == 47) {
      p = p + 2;
      while (p < n  and  _lia_char_code_at(s, p) != 10) { p = p + 1 ;}
    }
     else { return p ;}
  }
  return p;

}

pub fn is_ident_start(c: i64) bool {

  if ((c >= 65  and  c <= 90)  or  (c >= 97  and  c <= 122)  or  c == 95  or  c == 36) { return true ;}
  return false;

}

pub fn is_ident(c: i64) bool {

  if ((c >= 65  and  c <= 90)  or  (c >= 97  and  c <= 122)  or  (c >= 48  and  c <= 57)  or  c == 95  or  c == 36) { return true ;}
  return false;

}

pub fn read_ident(s: []const u8, i: i64) []const u8 {
    var n: i64 = 0;
    var j: i64 = 0;

  n = @as(i64, @intCast(s.len));
  if (i >= n) { return "" ;}
  if (is_ident_start(_lia_char_code_at(s, i)) == false) { return "" ;}
  j = i + 1;
  while (j < n  and  is_ident(_lia_char_code_at(s, j))) { j = j + 1 ;}
  return slice2(s, i, j);

}

pub fn match_brace(s: []const u8, open_idx: i64) i64 {
    var n: i64 = 0;
    var depth: i64 = 0;
    var p: i64 = 0;
    var c: i64 = 0;

  n = @as(i64, @intCast(s.len));
  depth = 0;
  p = open_idx;
  while (p < n) {
    c = _lia_char_code_at(s, p);
    if (c == 34) {
      p = p + 1;
      while (p < n  and  _lia_char_code_at(s, p) != 34) { p = p + 1 ;}
      if (p < n) { p = p + 1 ;}
      continue;
    }
    if (c == 123) { depth = depth + 1 ;}
     else if (c == 125) {
      depth = depth - 1;
      if (depth == 0) { return p ;}
    }
    p = p + 1;
  }
  return (-1);

}

pub fn find_brace(s: []const u8, i: i64) i64 {
    var n: i64 = 0;
    var p: i64 = 0;

  n = @as(i64, @intCast(s.len));
  p = i;
  while (p < n) {
    if (_lia_char_code_at(s, p) == 123) { return p ;}
    p = p + 1;
  }
  return (-1);

}

pub fn js_params(params: []const u8) []const u8 {
    var out: []const u8 = "";
    var k: i64 = 0;
    var pn: i64 = 0;
    var seen: i64 = 0;
    var id: []const u8 = "";

  out = "";
  k = 0;
  pn = @as(i64, @intCast(params.len));
  seen = 0;
  id = "";
  while (k < pn) {
    k = skip_ws(params, k);
    if (k >= pn) { break ;}
    id = read_ident(params, k);
    if (@as(i64, @intCast(id.len)) > 0) {
      if (seen == 1) { out = _lia_cat(out ,  ",") ;}
      out = _lia_cat(out ,  id);
      seen = 1;
      k = k + @as(i64, @intCast(id.len));
    }
     else { k = k + 1 ;}
    while (k < pn  and  _lia_char_code_at(params, k) != 44) { k = k + 1 ;}
    if (k < pn  and  _lia_char_code_at(params, k) == 44) { k = k + 1 ;}
  }
  return out;

}

pub fn rewrite_body(body: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var d: i64 = 0;
    var j: i64 = 0;
    var n: i64 = 0;
    var c: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  d = 0;
  j = 0;
  n = @as(i64, @intCast(body.len));
  while (i < n) {
    c = _lia_char_code_at(body, i);
    if (c == 34) {
      chs = _lia_char_at(body, i);
      out = _lia_cat(out ,  chs);
      i = i + 1;
      while (i < n  and  _lia_char_code_at(body, i) != 34) {
        chs = _lia_char_at(body, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { chs = _lia_char_at(body, i); out = _lia_cat(out ,  chs); i = i + 1 ;}
      continue;
    }
    if (c == 94) {
      var p_prev: i64 = i - 1;
      while (p_prev >= 0) {
        const pc = _lia_char_code_at(body, p_prev);
        if (pc == 32 or pc == 9 or pc == 10 or pc == 13) {
          p_prev -= 1;
          continue;
        }
        if (p_prev > 0) {
          var line_start = p_prev;
          while (line_start >= 0 and _lia_char_code_at(body, line_start) != 10) line_start -= 1;
          var has_comment = false;
          var ck = line_start + 1;
          while (ck < p_prev) : (ck += 1) {
            if (_lia_char_code_at(body, ck) == 47 and _lia_char_code_at(body, ck + 1) == 47) {
              has_comment = true;
              break;
            }
          }
          if (has_comment) {
            p_prev = line_start;
            continue;
          }
        }
        break;
      }
      var is_ret: bool = false;
      if (p_prev < 0 or _lia_char_code_at(body, p_prev) == 59 or _lia_char_code_at(body, p_prev) == 123 or _lia_char_code_at(body, p_prev) == 125) {
        is_ret = true;
      }
      if (is_ret) {
        out = _lia_cat(out ,  "return ");
        i = i + 1;
        while (i < n) {
          d = _lia_char_code_at(body, i);
          if (d == 125) { out = _lia_cat(out ,  ";"); break ;}
          if (d == 123) { break ;}
          chs = _lia_char_at(body, i);
          out = _lia_cat(out ,  chs);
          i = i + 1;
        }
        if (i >= n) { out = _lia_cat(out ,  ";") ;}
      } else {
        out = _lia_cat(out ,  " ^ ");
        i = i + 1;
      }
    }
     else if (c == 35  and  i + 1 < n  and  _lia_char_code_at(body, i + 1) == 40) {
      out = _lia_cat(out ,  "for");
      i = i + 1;
    }
     else if (c == 58) {
      j = skip_ws(body, i + 1);
      if (j < n) {
        d = _lia_char_code_at(body, j);
        if (d == 63  or  d == 123) { out = _lia_cat(out ,  " else "); i = j; continue ;}
        if (d == 40) { out = _lia_cat(out ,  " else if "); i = j; continue ;}
      }
      out = _lia_cat(out ,  ":");
      i = i + 1;
    }
     else if (c == 63  and  i + 1 < n  and  _lia_char_code_at(body, i + 1) == 40) {
      out = _lia_cat(out ,  "if ");
      i = i + 1;
    }
     else {
      chs = _lia_char_at(body, i);
      out = _lia_cat(out ,  chs);
      i = i + 1;
    }
  }
  return out;

}

pub fn each_fn(src: []const u8, i: i64) i64 {
    var n: i64 = 0;
    var name: []const u8 = "";
    var p: i64 = 0;
    var close_p: i64 = 0;
    var b: i64 = 0;
    var close_b: i64 = 0;

  n = @as(i64, @intCast(src.len));
  name = read_ident(src, i + 1);
  if (@as(i64, @intCast(name.len)) == 0) { return i + 1 ;}
  p = skip_ws(src, i + 1 + @as(i64, @intCast(name.len)));
  if (p >= n  or  _lia_char_code_at(src, p) != 40) { return i + 1 ;}
  close_p = p + 1;
  while (close_p < n  and  _lia_char_code_at(src, close_p) != 41) { close_p = close_p + 1 ;}
  b = find_brace(src, close_p + 1);
  if (b < 0) { return i + 1 ;}
  close_b = match_brace(src, b);
  if (close_b < 0) { return i + 1 ;}
  return close_b + 1;

}

pub fn lin_check(src: []const u8) []const u8 {
    var out: []const u8 = "";
    var name: []const u8 = "";
    var n: i64 = 0;
    var i: i64 = 0;
    var first: i64 = 0;

  out = "";
  name = "";
  n = @as(i64, @intCast(src.len));
  i = 0;
  first = 1;
  while (i < n) {
    i = skip_ws(src, i);
    if (i >= n) { return out ;}
    if (_lia_char_code_at(src, i) == 33  and  (i + 1 >= n  or  _lia_char_code_at(src, i + 1) != 61)) {
      name = read_ident(src, i + 1);
      if (@as(i64, @intCast(name.len)) > 0) {
        if (first == 0) { out = _lia_cat(out ,  ",") ;}
        out = _lia_cat(out ,  name);
        first = 0;
        i = each_fn(src, i);
        continue;
      }
    }
    i = i + 1;
  }
  return out;

}

pub const ParamTypeInfo = struct {
    name: []const u8,
    type_name: []const u8,
};

pub const FnTypeInfo = struct {
    name: []const u8,
    params: []ParamTypeInfo,
    return_type: []const u8,
    body: []const u8,
    line: usize,
};

fn is_valid_ident(s: []const u8) bool {
    if (s.len == 0) return false;
    for (s, 0..) |c, idx| {
        if (idx == 0) {
            if (!((c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or c == '_' or c == '$')) return false;
        } else {
            if (!((c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9') or c == '_' or c == '$')) return false;
        }
    }
    return true;
}

fn is_integer_literal(s: []const u8) bool {
    if (s.len == 0) return false;
    var start: usize = 0;
    if (s[0] == '-' and s.len > 1) start = 1;
    for (s[start..]) |c| {
        if (c < '0' or c > '9') return false;
    }
    return true;
}

const OpParts = struct {
    left: []const u8,
    right: []const u8,
};

fn has_top_level_op(s: []const u8, op: []const u8) bool {
    var in_quote = false;
    var paren_depth: i64 = 0;
    var brace_depth: i64 = 0;
    var i: usize = 0;
    while (i < s.len) {
        const c = s[i];
        if (c == '"') {
            in_quote = !in_quote;
            i += 1;
            continue;
        }
        if (!in_quote) {
            if (c == '(') paren_depth += 1
            else if (c == ')') paren_depth -= 1
            else if (c == '{') brace_depth += 1
            else if (c == '}') brace_depth -= 1
            else if (paren_depth == 0 and brace_depth == 0) {
                if (i + op.len <= s.len and std.mem.eql(u8, s[i .. i + op.len], op)) {
                    return true;
                }
            }
        }
        i += 1;
    }
    return false;
}

fn split_top_level_op(s: []const u8, op_ch: u8) ?OpParts {
    var in_quote = false;
    var paren_depth: i64 = 0;
    var brace_depth: i64 = 0;
    var i: usize = 0;
    while (i < s.len) {
        const c = s[i];
        if (c == '"') {
            in_quote = !in_quote;
            i += 1;
            continue;
        }
        if (!in_quote) {
            if (c == '(') paren_depth += 1
            else if (c == ')') paren_depth -= 1
            else if (c == '{') brace_depth += 1
            else if (c == '}') brace_depth -= 1
            else if (paren_depth == 0 and brace_depth == 0 and c == op_ch) {
                return OpParts{
                    .left = s[0..i],
                    .right = s[i + 1 ..],
                };
            }
        }
        i += 1;
    }
    return null;
}

fn find_matching_paren(s: []const u8, open_idx: usize) ?usize {
    var in_quote = false;
    var depth: i64 = 0;
    var i: usize = open_idx;
    while (i < s.len) {
        const c = s[i];
        if (c == '"') {
            in_quote = !in_quote;
            i += 1;
            continue;
        }
        if (!in_quote) {
            if (c == '(') depth += 1
            else if (c == ')') {
                depth -= 1;
                if (depth == 0) return i;
            }
        }
        i += 1;
    }
    return null;
}

fn split_call_args(allocator: std.mem.Allocator, raw: []const u8) ![][]const u8 {
    var args = std.ArrayList([]const u8).init(allocator);
    var start: usize = 0;
    var in_quote = false;
    var paren_depth: i64 = 0;
    var brace_depth: i64 = 0;
    var i: usize = 0;
    while (i <= raw.len) {
        if (i == raw.len) {
            const item = std.mem.trim(u8, raw[start..i], " \t\r\n");
            if (item.len > 0) try args.append(item);
            break;
        }
        const c = raw[i];
        if (c == '"') in_quote = !in_quote;
        if (!in_quote) {
            if (c == '(') paren_depth += 1
            else if (c == ')') paren_depth -= 1
            else if (c == '{') brace_depth += 1
            else if (c == '}') brace_depth -= 1
            else if (paren_depth == 0 and brace_depth == 0 and c == ',') {
                const item = std.mem.trim(u8, raw[start..i], " \t\r\n");
                if (item.len > 0) try args.append(item);
                start = i + 1;
            }
        }
        i += 1;
    }
    return args.toOwnedSlice();
}

pub fn infer_expr_type(expr: []const u8, locals: *const std.StringHashMap([]const u8), fns: []const FnTypeInfo) []const u8 {
    const trimmed = std.mem.trim(u8, expr, " \t\r\n;");
    if (trimmed.len == 0) return "any";

    // String literal: "..."
    if (trimmed.len >= 2 and trimmed[0] == '"' and trimmed[trimmed.len - 1] == '"') {
        return "string";
    }

    // Boolean literal: true / false
    if (std.mem.eql(u8, trimmed, "true") or std.mem.eql(u8, trimmed, "false")) {
        return "bool";
    }

    // Single identifier
    if (is_valid_ident(trimmed)) {
        if (locals.get(trimmed)) |t| {
            return t;
        }
        return "any";
    }

    // Integer literal
    if (is_integer_literal(trimmed)) {
        return "int";
    }

    // Function call: name(...)
    if (std.mem.indexOfScalar(u8, trimmed, '(')) |oparen| {
        if (trimmed[trimmed.len - 1] == ')') {
            const callee_name = std.mem.trim(u8, trimmed[0..oparen], " \t");
            for (fns) |f| {
                if (std.mem.eql(u8, f.name, callee_name)) {
                    return f.return_type;
                }
            }
        }
    }

    // Comparison operators (==, !=, <=, >=, <, >) outside quotes/parens
    if (has_top_level_op(trimmed, "==") or has_top_level_op(trimmed, "!=") or
        has_top_level_op(trimmed, "<=") or has_top_level_op(trimmed, ">=") or
        has_top_level_op(trimmed, "<") or has_top_level_op(trimmed, ">"))
    {
        return "bool";
    }

    // Logical operators (&&, ||, and, or)
    if (has_top_level_op(trimmed, "&&") or has_top_level_op(trimmed, "||") or
        has_top_level_op(trimmed, " and ") or has_top_level_op(trimmed, " or "))
    {
        return "bool";
    }

    // Arithmetic operators (+, -, *, /, %)
    if (has_top_level_op(trimmed, "+")) {
        if (split_top_level_op(trimmed, '+')) |parts| {
            const t_left = infer_expr_type(parts.left, locals, fns);
            const t_right = infer_expr_type(parts.right, locals, fns);
            if (std.mem.eql(u8, t_left, "string") or std.mem.eql(u8, t_right, "string")) {
                return "string";
            }
            if (std.mem.eql(u8, t_left, "int") and std.mem.eql(u8, t_right, "int")) {
                return "int";
            }
        }
        return "int";
    }

    if (has_top_level_op(trimmed, "-") or has_top_level_op(trimmed, "*") or
        has_top_level_op(trimmed, "/") or has_top_level_op(trimmed, "%"))
    {
        return "int";
    }

    // Parenthesized expression: (expr)
    if (trimmed.len >= 2 and trimmed[0] == '(' and trimmed[trimmed.len - 1] == ')') {
        return infer_expr_type(trimmed[1 .. trimmed.len - 1], locals, fns);
    }

    return "any";
}

pub fn parse_fn_type_infos(allocator: std.mem.Allocator, src: []const u8) ![]FnTypeInfo {
    var list = std.ArrayList(FnTypeInfo).init(allocator);
    var i: usize = 0;
    var current_line: usize = 1;

    while (i < src.len) {
        if (src[i] == '\n') current_line += 1;
        if (src[i] == '!' and (i + 1 >= src.len or src[i + 1] != '=')) {
            const fn_line = current_line;
            var pos = i + 1;
            while (pos < src.len and (src[pos] == ' ' or src[pos] == '\t' or src[pos] == '\r' or src[pos] == '\n')) {
                if (src[pos] == '\n') current_line += 1;
                pos += 1;
            }
            const name_start = pos;
            while (pos < src.len and ((src[pos] >= 'a' and src[pos] <= 'z') or (src[pos] >= 'A' and src[pos] <= 'Z') or (src[pos] >= '0' and src[pos] <= '9') or src[pos] == '_' or src[pos] == '$')) {
                pos += 1;
            }
            const fn_name = src[name_start..pos];
            if (fn_name.len > 0 and pos < src.len and src[pos] == '(') {
                const open_p = pos;
                var paren_depth: i64 = 1;
                pos += 1;
                while (pos < src.len and paren_depth > 0) {
                    if (src[pos] == '\n') current_line += 1;
                    if (src[pos] == '"') {
                        pos += 1;
                        while (pos < src.len and src[pos] != '"') {
                            if (src[pos] == '\n') current_line += 1;
                            pos += 1;
                        }
                        if (pos < src.len) pos += 1;
                        continue;
                    }
                    if (src[pos] == '(') paren_depth += 1
                    else if (src[pos] == ')') paren_depth -= 1;
                    pos += 1;
                }
                const close_p = pos - 1;
                const raw_params = src[open_p + 1 .. close_p];

                // Parse parameters
                var param_list = std.ArrayList(ParamTypeInfo).init(allocator);
                var p_it = std.mem.splitScalar(u8, raw_params, ',');
                while (p_it.next()) |p_raw| {
                    const p_trimmed = std.mem.trim(u8, p_raw, " \t\r\n");
                    if (p_trimmed.len == 0) continue;
                    if (std.mem.indexOfScalar(u8, p_trimmed, ':')) |colon_idx| {
                        const p_name = std.mem.trim(u8, p_trimmed[0..colon_idx], " \t\r\n");
                        const p_type = std.mem.trim(u8, p_trimmed[colon_idx + 1 ..], " \t\r\n");
                        try param_list.append(.{ .name = p_name, .type_name = p_type });
                    } else {
                        try param_list.append(.{ .name = p_trimmed, .type_name = "any" });
                    }
                }

                // Look for return type before '{'
                var hdr_end = pos;
                while (hdr_end < src.len and src[hdr_end] != '{') {
                    if (src[hdr_end] == '\n') current_line += 1;
                    hdr_end += 1;
                }
                const hdr_extra = src[pos..hdr_end];
                var ret_type: []const u8 = "any";
                if (std.mem.indexOf(u8, hdr_extra, "->")) |arrow_idx| {
                    ret_type = std.mem.trim(u8, hdr_extra[arrow_idx + 2 ..], " \t\r\n");
                } else if (std.mem.indexOfScalar(u8, hdr_extra, ':')) |colon_idx| {
                    ret_type = std.mem.trim(u8, hdr_extra[colon_idx + 1 ..], " \t\r\n");
                }

                // Extract body
                if (hdr_end < src.len and src[hdr_end] == '{') {
                    const brace_open = hdr_end;
                    var brace_depth: i64 = 1;
                    var bpos = brace_open + 1;
                    while (bpos < src.len and brace_depth > 0) {
                        if (src[bpos] == '\n') current_line += 1;
                        if (src[bpos] == '"') {
                            bpos += 1;
                            while (bpos < src.len and src[bpos] != '"') {
                                if (src[bpos] == '\n') current_line += 1;
                                bpos += 1;
                            }
                            if (bpos < src.len) bpos += 1;
                            continue;
                        }
                        if (src[bpos] == '{') brace_depth += 1
                        else if (src[bpos] == '}') brace_depth -= 1;
                        bpos += 1;
                    }
                    const brace_close = bpos - 1;
                    const body_text = src[brace_open + 1 .. brace_close];
                    try list.append(.{
                        .name = fn_name,
                        .params = try param_list.toOwnedSlice(),
                        .return_type = ret_type,
                        .body = body_text,
                        .line = fn_line,
                    });
                    i = bpos;
                    continue;
                }
            }
        }
        i += 1;
    }
    return list.toOwnedSlice();
}

pub fn lin_type_check(src: []const u8) ?[]const u8 {
    const fns = parse_fn_type_infos(LIA_ALLOC, src) catch return null;
    defer LIA_ALLOC.free(fns);

    for (fns) |fn_info| {
        var locals = std.StringHashMap([]const u8).init(LIA_ALLOC);
        defer locals.deinit();

        for (fn_info.params) |p| {
            locals.put(p.name, p.type_name) catch {};
        }

        // Scan statements inside function body
        var stmt_start: usize = 0;
        var in_quote = false;
        var paren_depth: i64 = 0;
        var brace_depth: i64 = 0;
        var idx: usize = 0;

        while (idx <= fn_info.body.len) {
            var is_stmt_end = false;
            if (idx == fn_info.body.len) {
                is_stmt_end = true;
            } else {
                const ch = fn_info.body[idx];
                if (ch == '"') in_quote = !in_quote;
                if (!in_quote) {
                    if (ch == '(') paren_depth += 1
                    else if (ch == ')') paren_depth -= 1
                    else if (ch == '{') brace_depth += 1
                    else if (ch == '}') brace_depth -= 1
                    else if (paren_depth == 0 and brace_depth == 0 and ch == ';') {
                        is_stmt_end = true;
                    }
                }
            }

            if (is_stmt_end) {
                const stmt = std.mem.trim(u8, fn_info.body[stmt_start..idx], " \t\r\n;");
                stmt_start = idx + 1;
                idx += 1;
                if (stmt.len == 0) continue;

                // Check assignment: var = expr
                if (std.mem.indexOfScalar(u8, stmt, '=')) |eq_idx| {
                    if (eq_idx > 0 and stmt[eq_idx - 1] != '=' and stmt[eq_idx - 1] != '!' and stmt[eq_idx - 1] != '<' and stmt[eq_idx - 1] != '>' and
                        (eq_idx + 1 >= stmt.len or stmt[eq_idx + 1] != '='))
                    {
                        const lhs = std.mem.trim(u8, stmt[0..eq_idx], " \t");
                        const rhs = std.mem.trim(u8, stmt[eq_idx + 1 ..], " \t");
                        if (is_valid_ident(lhs)) {
                            const rhs_type = infer_expr_type(rhs, &locals, fns);
                            locals.put(lhs, rhs_type) catch {};
                        }
                    }
                }

                // Check return statements: ^expr or return expr
                var ret_expr: ?[]const u8 = null;
                if (stmt[0] == '^') {
                    ret_expr = std.mem.trim(u8, stmt[1..], " \t");
                } else if (std.mem.startsWith(u8, stmt, "return ")) {
                    ret_expr = std.mem.trim(u8, stmt[7..], " \t");
                }

                if (ret_expr) |rx| {
                    const actual_ret_type = infer_expr_type(rx, &locals, fns);
                    if (!std.mem.eql(u8, fn_info.return_type, "any") and !std.mem.eql(u8, actual_ret_type, "any")) {
                        if (std.mem.eql(u8, fn_info.return_type, "int") and (std.mem.eql(u8, actual_ret_type, "string") or std.mem.eql(u8, actual_ret_type, "bool"))) {
                            return std.fmt.allocPrint(LIA_ALLOC, "LIN_TYPE_ERROR: function '{s}' return type mismatch: expected int, got {s}", .{ fn_info.name, actual_ret_type }) catch "LIN_TYPE_ERROR: return type mismatch";
                        }
                        if (std.mem.eql(u8, fn_info.return_type, "string") and (std.mem.eql(u8, actual_ret_type, "int") or std.mem.eql(u8, actual_ret_type, "bool"))) {
                            return std.fmt.allocPrint(LIA_ALLOC, "LIN_TYPE_ERROR: function '{s}' return type mismatch: expected string, got {s}", .{ fn_info.name, actual_ret_type }) catch "LIN_TYPE_ERROR: return type mismatch";
                        }
                        if (std.mem.eql(u8, fn_info.return_type, "bool") and (std.mem.eql(u8, actual_ret_type, "string") or std.mem.eql(u8, actual_ret_type, "int"))) {
                            return std.fmt.allocPrint(LIA_ALLOC, "LIN_TYPE_ERROR: function '{s}' return type mismatch: expected bool, got {s}", .{ fn_info.name, actual_ret_type }) catch "LIN_TYPE_ERROR: return type mismatch";
                        }
                    }
                }

                // Check function call argument types in statement
                for (fns) |callee| {
                    var search_pos: usize = 0;
                    while (std.mem.indexOfPos(u8, stmt, search_pos, callee.name)) |call_idx| {
                        const after_name = call_idx + callee.name.len;
                        search_pos = after_name;
                        if (call_idx > 0 and ((stmt[call_idx - 1] >= 'a' and stmt[call_idx - 1] <= 'z') or (stmt[call_idx - 1] >= 'A' and stmt[call_idx - 1] <= 'Z') or (stmt[call_idx - 1] >= '0' and stmt[call_idx - 1] <= '9') or stmt[call_idx - 1] == '_' or stmt[call_idx - 1] == '$')) continue;
                        if (after_name < stmt.len and stmt[after_name] == '(') {
                            if (find_matching_paren(stmt, after_name)) |close_call_p| {
                                const args_raw = stmt[after_name + 1 .. close_call_p];
                                const call_args = split_call_args(LIA_ALLOC, args_raw) catch null;
                                if (call_args) |args| {
                                    defer LIA_ALLOC.free(args);
                                    for (args, 0..) |arg_trimmed, arg_idx| {
                                        if (arg_idx < callee.params.len) {
                                            const expected_type = callee.params[arg_idx].type_name;
                                            const actual_type = infer_expr_type(arg_trimmed, &locals, fns);
                                            if (!std.mem.eql(u8, expected_type, "any") and !std.mem.eql(u8, actual_type, "any")) {
                                                if (!std.mem.eql(u8, expected_type, actual_type)) {
                                                    return std.fmt.allocPrint(LIA_ALLOC, "LIN_TYPE_ERROR: function '{s}' argument '{s}' expected type {s}, got {s}", .{ callee.name, callee.params[arg_idx].name, expected_type, actual_type }) catch "LIN_TYPE_ERROR: argument type mismatch";
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                idx += 1;
            }
        }
    }
    return null;
}

pub fn lin_syntax_valid(src: []const u8) i64 {
    var names: []const u8 = "";
    var n: i64 = 0;
    var i: i64 = 0;
    var depth: i64 = 0;
    var c: i64 = 0;

    names = "";
    n = @as(i64, @intCast(src.len));
    i = 0;
    depth = 0;
    c = 0;
    while (i < n) {
        c = _lia_char_code_at(src, i);
        if (c == 34) {
            i = i + 1;
            while (i < n and _lia_char_code_at(src, i) != 34) { i = i + 1; }
            if (i < n) { i = i + 1; }
            continue;
        }
        if (c == 123) { depth = depth + 1; }
        if (c == 125) {
            depth = depth - 1;
            if (depth < 0) { return 0; }
        }
        i = i + 1;
    }
    if (depth != 0) { return 0; }
    names = lin_check(src);
    if (@as(i64, @intCast(names.len)) == 0) { return 0; }
    return 1;
}

pub fn lin_valid(src: []const u8) i64 {
    if (lin_syntax_valid(src) == 0) return 0;
    if (lin_type_check(src) != null) return 0;
    return 1;
}

pub fn q() []const u8 {
    return _lia_from_code(34);
}

pub fn csv_json_arr(csv: []const u8) []const u8 {
    var out: []const u8 = "";
    var k: i64 = 0;
    var n: i64 = 0;
    var first: i64 = 0;
    var id: []const u8 = "";

    out = "[";
    k = 0;
    n = @as(i64, @intCast(csv.len));
    first = 1;
    id = "";
    while (k < n) {
        id = read_ident(csv, k);
        if (@as(i64, @intCast(id.len)) > 0) {
            if (first == 0) { out = _lia_cat(out, ","); }
            out = _lia_cat(out, q());
            out = _lia_cat(out, id);
            out = _lia_cat(out, q());
            first = 0;
            k = k + @as(i64, @intCast(id.len));
        } else { k = k + 1; }
    }
    out = _lia_cat(out, "]");
    return out;
}

pub fn read_header(src: []const u8) []const u8 {
    var n: i64 = 0;
    var i: i64 = 0;
    var j: i64 = 0;

    n = @as(i64, @intCast(src.len));
    i = 0;
    while (i < n) {
        if (_lia_char_code_at(src, i) == 64) {
            j = i;
            while (j < n and _lia_char_code_at(src, j) != 10) { j = j + 1; }
            return slice2(src, i, j);
        }
        i = i + 1;
    }
    return "@LIN:L1c:0.2";
}

pub fn read_exports(src: []const u8) []const u8 {
    var n: i64 = 0;
    var i: i64 = 0;
    var j: i64 = 0;

    n = @as(i64, @intCast(src.len));
    i = 0;
    while (i < n) {
        if (_lia_char_code_at(src, i) == 61 and i + 3 < n and _lia_char_code_at(src, i + 1) == 101 and _lia_char_code_at(src, i + 2) == 120 and _lia_char_code_at(src, i + 3) == 123) {
            j = i + 4;
            while (j < n and _lia_char_code_at(src, j) != 125) { j = j + 1; }
            return slice2(src, i + 4, j);
        }
        i = i + 1;
    }
    return "";
}

pub fn lin_check_json(src: []const u8) []const u8 {
    const names = lin_check(src);
    const ex = read_exports(src);
    const h = read_header(src);
    const fns = parse_fn_type_infos(LIA_ALLOC, src) catch null;

    var types_json = std.ArrayList(u8).init(LIA_ALLOC);
    defer types_json.deinit();
    const tw = types_json.writer();
    tw.writeAll("{") catch {};
    if (fns) |fn_list| {
        for (fn_list, 0..) |f, fidx| {
            if (fidx > 0) tw.writeAll(",") catch {};
            tw.print("\"{s}\":{{\"params\":[", .{f.name}) catch {};
            for (f.params, 0..) |p, pidx| {
                if (pidx > 0) tw.writeAll(",") catch {};
                tw.print("\"{s}:{s}\"", .{ p.name, p.type_name }) catch {};
            }
            tw.print("],\"return\":\"{s}\"}}", .{f.return_type}) catch {};
        }
    }
    tw.writeAll("}") catch {};

    var out = std.ArrayList(u8).init(LIA_ALLOC);
    defer out.deinit();
    const ow = out.writer();
    ow.print("{{\"header\":\"{s}\",\"fns\":{s},\"exports\":{s},\"types\":{s},\"typecheck\":\"passed\"}}", .{
        h,
        csv_json_arr(names),
        csv_json_arr(ex),
        types_json.items,
    }) catch {};
    return out.toOwnedSlice() catch "{}";
}

pub fn andor(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (_lia_char_code_at(s, i) == 38  and  i + 1 < n  and  _lia_char_code_at(s, i + 1) == 38) {
      out = _lia_cat(out ,  " and ");
      i = i + 2;
    }
     else if (_lia_char_code_at(s, i) == 124  and  i + 1 < n  and  _lia_char_code_at(s, i + 1) == 124) {
      out = _lia_cat(out ,  " or ");
      i = i + 2;
    }
     else {
      chs = _lia_char_at(s, i);
      out = _lia_cat(out ,  chs);
      i = i + 1;
    }
  }
  return out;

}

pub fn in_csv(csv: []const u8, id: []const u8) i64 {
    var k: i64 = 0;
    var n: i64 = 0;
    var t: []const u8 = "";
    var m: i64 = 0;
    var same: i64 = 0;

  k = 0;
  n = @as(i64, @intCast(csv.len));
  t = "";
  while (k < n) {
    t = read_ident(csv, k);
    if (@as(i64, @intCast(t.len)) > 0) {
      if (@as(i64, @intCast(t.len)) == @as(i64, @intCast(id.len))) {
        m = 0;
        same = 1;
        while (m < @as(i64, @intCast(id.len))) {
          if (_lia_char_code_at(t, m) != _lia_char_code_at(id, m)) { same = 0 ;}
          m = m + 1;
        }
        if (same == 1) { return 1 ;}
      }
      k = k + @as(i64, @intCast(t.len));
    }
     else { k = k + 1 ;}
  }
  return 0;

}

pub fn match_paren(s: []const u8, open: i64) i64 {
    var n: i64 = 0;
    var depth: i64 = 0;
    var p: i64 = 0;
    var c: i64 = 0;

  n = @as(i64, @intCast(s.len));
  depth = 0;
  p = open;
  while (p < n) {
    c = _lia_char_code_at(s, p);
    if (c == 34) {
      p = p + 1;
      while (p < n  and  _lia_char_code_at(s, p) != 34) { p = p + 1 ;}
      if (p < n) { p = p + 1 ;}
      continue;
    }
    if (c == 40) { depth = depth + 1 ;}
     else if (c == 41) {
      depth = depth - 1;
      if (depth == 0) { return p ;}
    }
    p = p + 1;
  }
  return (-1);

}

pub fn starts_lit(s: []const u8, i: i64, lit: []const u8) i64 {
    var n: i64 = 0;
    var ln: i64 = 0;
    var k: i64 = 0;

  n = @as(i64, @intCast(s.len));
  ln = @as(i64, @intCast(lit.len));
  k = 0;
  while (k < ln) {
    if (i + k >= n) { return 0 ;}
    if (_lia_char_code_at(s, i + k) != _lia_char_code_at(lit, k)) { return 0 ;}
    k = k + 1;
  }
  return 1;

}

pub fn kw_space(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var t: i64 = 0;
    var prev: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  t = 0;
  prev = 0;
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (starts_lit(s, i, "while(") == 1) { out = _lia_cat(out ,  "while ("); i = i + 6; continue ;}
    if (starts_lit(s, i, "if(") == 1) { out = _lia_cat(out ,  "if ("); i = i + 3; continue ;}
    if (i + 1 < n  and  _lia_char_code_at(s, i) == 41  and  _lia_char_code_at(s, i + 1) == 123) { out = _lia_cat(out ,  ") {"); i = i + 2; continue ;}
    if (i + 1 < n  and  _lia_char_code_at(s, i) == 125  and  _lia_char_code_at(s, i + 1) == 59) { out = _lia_cat(out ,  "}"); i = i + 2; continue ;}
    if (_lia_char_code_at(s, i) == 59) {
      t = @as(i64, @intCast(out.len));
      while (t > 0) {
        prev = _lia_char_code_at(out, t - 1);
        if (prev == 32  or  prev == 9  or  prev == 10  or  prev == 13) { t = t - 1 ;}
         else { break ;}
      }
      if (t > 0) {
        prev = _lia_char_code_at(out, t - 1);
        if (prev == 59  or  prev == 125) { i = i + 1; continue ;}
      }
      out = _lia_cat(out ,  ";");
      i = i + 1;
      continue;
    }
    chs = _lia_char_at(s, i);
    out = _lia_cat(out ,  chs);
    i = i + 1;
  }
  return out;

}

pub fn rewrite_js_methods(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var k: i64 = 0;
    var open: i64 = 0;
    var cl: i64 = 0;
    var id: []const u8 = "";

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  k = 0;
  open = 0;
  cl = 0;
  id = "";
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (starts_lit(s, i, "String.fromCharCode(") == 1) {
      open = i + 19;
      cl = match_paren(s, open);
      if (cl > open) {
        out = _lia_cat(out ,  "_lia_from_code(");
        out = _lia_cat(out ,  slice2(s, open + 1, cl));
        out = _lia_cat(out ,  ")");
        i = cl + 1;
        continue;
      }
    }
    id = read_ident(s, i);
    if (@as(i64, @intCast(id.len)) > 0) {
      k = i + @as(i64, @intCast(id.len));
      if (k < n  and  _lia_char_code_at(s, k) == 46) {
        if (starts_lit(s, k + 1, "charCodeAt(") == 1) {
          open = k + 11;
          cl = match_paren(s, open);
          if (cl > open) {
            out = _lia_cat(out ,  "_lia_char_code_at(");
            out = _lia_cat(out ,  id);
            out = _lia_cat(out ,  ", ");
            out = _lia_cat(out ,  slice2(s, open + 1, cl));
            out = _lia_cat(out ,  ")");
            i = cl + 1;
            continue;
          }
        }
        if (starts_lit(s, k + 1, "charAt(") == 1) {
          open = k + 7;
          cl = match_paren(s, open);
          if (cl > open) {
            out = _lia_cat(out ,  "_lia_char_at(");
            out = _lia_cat(out ,  id);
            out = _lia_cat(out ,  ", ");
            out = _lia_cat(out ,  slice2(s, open + 1, cl));
            out = _lia_cat(out ,  ")");
            i = cl + 1;
            continue;
          }
        }
        if (starts_lit(s, k + 1, "slice(") == 1) {
          open = k + 6;
          cl = match_paren(s, open);
          if (cl > open) {
            out = _lia_cat(out ,  "_lia_slice(");
            out = _lia_cat(out ,  id);
            out = _lia_cat(out ,  ", ");
            out = _lia_cat(out ,  slice2(s, open + 1, cl));
            out = _lia_cat(out ,  ")");
            i = cl + 1;
            continue;
          }
        }
        if (starts_lit(s, k + 1, "length") == 1) {
          out = _lia_cat(out ,  "@as(i64, @intCast(");
          out = _lia_cat(out ,  id);
          out = _lia_cat(out ,  ".len))");
          i = k + 7;
          continue;
        }
      }
      out = _lia_cat(out ,  id);
      i = i + @as(i64, @intCast(id.len));
      continue;
    }
    chs = _lia_char_at(s, i);
    out = _lia_cat(out ,  chs);
    i = i + 1;
  }
  return out;

}

pub fn atom_is_str(a: []const u8) i64 {
    var c: i64 = 0;

  if (@as(i64, @intCast(a.len)) == 0) { return 0 ;}
  c = _lia_char_code_at(a, 0);
  if (c == 32  or  c == 9) { return atom_is_str(slice2(a, 1, @as(i64, @intCast(a.len)))) ;}
  if (c == 34) { return 1 ;}
  if (starts_lit(a, 0, "_lia_") == 1) { return 1 ;}
  if (starts_lit(a, 0, "slice2") == 1) { return 1 ;}
  if (starts_lit(a, 0, "read_ident") == 1) { return 1 ;}
  if (starts_lit(a, 0, "out") == 1  and  (@as(i64, @intCast(a.len)) == 3  or  _lia_char_code_at(a, 3) < 48  or  _lia_char_code_at(a, 3) > 122)) { return 1 ;}
  if (starts_lit(a, 0, "id") == 1  and  @as(i64, @intCast(a.len)) == 2) { return 1 ;}
  if (starts_lit(a, 0, "src") == 1  and  @as(i64, @intCast(a.len)) == 3) { return 1 ;}
  if (starts_lit(a, 0, "body") == 1) { return 1 ;}
  if (starts_lit(a, 0, "params") == 1) { return 1 ;}
  if (starts_lit(a, 0, "names") == 1) { return 1 ;}
  if (starts_lit(a, 0, "chs") == 1) { return 1 ;}
  if (starts_lit(a, 0, "js_p") == 1) { return 1 ;}
  if (starts_lit(a, 0, "zig_params") == 1) { return 1 ;}
  return 0;

}

pub fn atom_is_num(a: []const u8) i64 {
    var c: i64 = 0;

  if (@as(i64, @intCast(a.len)) == 0) { return 0 ;}
  c = _lia_char_code_at(a, 0);
  if (c == 32  or  c == 9) { return atom_is_num(slice2(a, 1, @as(i64, @intCast(a.len)))) ;}
  if (c >= 48  and  c <= 57) { return 1 ;}
  if (c == 45) { return 1 ;}
  if (starts_lit(a, 0, "@as") == 1) { return 1 ;}
  if (starts_lit(a, 0, "_lia_char_code") == 1) { return 1 ;}
  return 0;

}

pub fn rewrite_plus(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var L: i64 = 0;
    var R: i64 = 0;
    var left: []const u8 = "";
    var right: []const u8 = "";
    var cut: i64 = 0;
    var take: i64 = 0;
    var c: i64 = 0;
    var id: []const u8 = "";
    var cl: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  L = 0;
  R = 0;
  left = "";
  right = "";
  cut = 0;
  take = 0;
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (_lia_char_code_at(s, i) == 43) {
      L = i;
      while (L > 0) {
        c = _lia_char_code_at(s, L - 1);
        if (c == 32  or  c == 9) { L = L - 1 ;}
         else { break ;}
      }
      while (L > 0  and  is_ident(_lia_char_code_at(s, L - 1))) { L = L - 1 ;}
      R = skip_ws(s, i + 1);
      if (R < n  and  _lia_char_code_at(s, R) == 34) {
        R = R + 1;
        while (R < n  and  _lia_char_code_at(s, R) != 34) { R = R + 1 ;}
        if (R < n) { R = R + 1 ;}
      }
       else {
        id = read_ident(s, R);
        if (@as(i64, @intCast(id.len)) > 0) {
          R = R + @as(i64, @intCast(id.len));
          if (R < n  and  _lia_char_code_at(s, R) == 40) {
            cl = match_paren(s, R);
            if (cl > R) { R = cl + 1 ;}
          }
        }
         else { R = R + 1 ;}
      }
      left = slice2(s, L, i);
      right = slice2(s, i + 1, R);
      if (atom_is_str(left) == 1  or  atom_is_str(right) == 1) {
        if (atom_is_num(left) == 0  or  atom_is_num(right) == 0) {
          take = i - L;
          cut = @as(i64, @intCast(out.len)) - take;
          if (cut < 0) { cut = 0 ;}
          out = slice2(out, 0, cut);
          out = _lia_cat(out ,  "_lia_cat(");
          out = _lia_cat(out ,  left);
          out = _lia_cat(out ,  ", ");
          out = _lia_cat(out ,  right);
          out = _lia_cat(out ,  ")");
          i = R;
          continue;
        }
      }
    }
    chs = _lia_char_at(s, i);
    out = _lia_cat(out ,  chs);
    i = i + 1;
  }
  return out;

}

pub fn rewrite_semi(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var t: i64 = 0;
    var prev: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  t = 0;
  prev = 0;
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (_lia_char_code_at(s, i) == 125) {
      t = @as(i64, @intCast(out.len));
      while (t > 0) {
        prev = _lia_char_code_at(out, t - 1);
        if (prev == 32  or  prev == 9  or  prev == 10  or  prev == 13) { t = t - 1 ;}
         else { break ;}
      }
      if (t > 0) {
        prev = _lia_char_code_at(out, t - 1);
        if (prev != 59  and  prev != 123  and  prev != 125) { out = _lia_cat(out ,  ";") ;}
      }
      out = _lia_cat(out ,  "}");
      i = i + 1;
    }
     else {
      chs = _lia_char_at(s, i);
      out = _lia_cat(out ,  chs);
      i = i + 1;
    }
  }
  return out;

}

pub fn zig_ty(t: []const u8) []const u8 {

  if (@as(i64, @intCast(t.len)) == 6  and  starts_lit(t, 0, "string") == 1) { return "[]const u8" ;}
  if (@as(i64, @intCast(t.len)) == 3  and  starts_lit(t, 0, "str") == 1) { return "[]const u8" ;}
  if (@as(i64, @intCast(t.len)) == 4  and  starts_lit(t, 0, "bool") == 1) { return "bool" ;}
  return "i64";

}

pub fn skip_type(params: []const u8, k0: i64) i64 {
    var k: i64 = 0;
    var pn: i64 = 0;
    var t: []const u8 = "";

  k = skip_ws(params, k0);
  pn = @as(i64, @intCast(params.len));
  if (k < pn  and  _lia_char_code_at(params, k) == 58) {
    k = skip_ws(params, k + 1);
    t = read_ident(params, k);
    if (@as(i64, @intCast(t.len)) > 0) { k = k + @as(i64, @intCast(t.len)) ;}
  }
  return k;

}

pub fn param_zig_type(params: []const u8, after_id: i64) []const u8 {
    var k: i64 = 0;
    var pn: i64 = 0;
    var t: []const u8 = "";

  k = skip_ws(params, after_id);
  pn = @as(i64, @intCast(params.len));
  if (k < pn  and  _lia_char_code_at(params, k) == 58) {
    k = skip_ws(params, k + 1);
    t = read_ident(params, k);
    if (@as(i64, @intCast(t.len)) > 0) { return zig_ty(t) ;}
  }
  return "i64";

}

pub fn fn_ret_type(src: []const u8, after_paren: i64, brace: i64) []const u8 {
    var k: i64 = 0;
    var t: []const u8 = "";

  k = skip_ws(src, after_paren);
  if (k < brace  and  _lia_char_code_at(src, k) == 45  and  k + 1 < brace  and  _lia_char_code_at(src, k + 1) == 62) {
    k = skip_ws(src, k + 2);
    t = read_ident(src, k);
    if (@as(i64, @intCast(t.len)) > 0) { return zig_ty(t) ;}
  }
  if (k < brace  and  _lia_char_code_at(src, k) == 58) {
    k = skip_ws(src, k + 1);
    t = read_ident(src, k);
    if (@as(i64, @intCast(t.len)) > 0) { return zig_ty(t) ;}
  }
  return "i64";

}

pub fn rhs_kind(body: []const u8, eq_pos: i64) []const u8 {
    var n: i64 = 0;
    var k: i64 = 0;
    var id: []const u8 = "";
    var k2: i64 = 0;
    var fld: []const u8 = "";

  n = @as(i64, @intCast(body.len));
  k = skip_ws(body, eq_pos + 1);
  if (k >= n) { return "i64" ;}
  if (_lia_char_code_at(body, k) == 34) { return "[]const u8" ;}
  id = read_ident(body, k);
  if (@as(i64, @intCast(id.len)) == 0) { return "i64" ;}
  if (starts_lit(id, 0, "true") == 1  or  starts_lit(id, 0, "false") == 1) { return "bool" ;}
  k2 = skip_ws(body, k + @as(i64, @intCast(id.len)));
  if (k2 < n  and  _lia_char_code_at(body, k2) == 46) {
    fld = read_ident(body, k2 + 1);
    if (starts_lit(fld, 0, "length") == 1  or  starts_lit(fld, 0, "charCodeAt") == 1) { return "i64" ;}
    return "[]const u8";
  }
  if (starts_lit(id, 0, "read_ident") == 1  or  starts_lit(id, 0, "slice2") == 1  or  starts_lit(id, 0, "q") == 1) { return "[]const u8" ;}
  if (starts_lit(id, 0, "js_params") == 1  or  starts_lit(id, 0, "rewrite_") == 1  or  starts_lit(id, 0, "lin_") == 1) { return "[]const u8" ;}
  if (starts_lit(id, 0, "andor") == 1  or  starts_lit(id, 0, "kw_space") == 1  or  starts_lit(id, 0, "zig_") == 1) { return "[]const u8" ;}
  if (starts_lit(id, 0, "emit_") == 1  or  starts_lit(id, 0, "param_") == 1  or  starts_lit(id, 0, "fn_ret") == 1) { return "[]const u8" ;}
  return "i64";

}

pub fn zig_decls(body: []const u8, params: []const u8) []const u8 {
    var out: []const u8 = "";
    var seen: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var id: []const u8 = "";
    var ty: []const u8 = "";
    var j: i64 = 0;

  out = "";
  seen = "";
  i = 0;
  n = @as(i64, @intCast(body.len));
  id = "";
  ty = "";
  while (i < n) {
    if (_lia_char_code_at(body, i) == 34) {
      i = i + 1;
      while (i < n  and  _lia_char_code_at(body, i) != 34) { i = i + 1 ;}
      if (i < n) { i = i + 1 ;}
      continue;
    }
    id = read_ident(body, i);
    if (@as(i64, @intCast(id.len)) > 0) {
      if (@as(i64, @intCast(id.len)) == 1  and  _lia_char_code_at(id, 0) == 95) { i = i + 1; continue ;}
      j = skip_ws(body, i + @as(i64, @intCast(id.len)));
      if (j < n  and  starts_lit(body, j, "=>") == 1) { i = i + @as(i64, @intCast(id.len)); continue ;}
      if (j < n  and  _lia_char_code_at(body, j) == 61  and  (j + 1 >= n  or  _lia_char_code_at(body, j + 1) != 61)) {
        if (in_csv(params, id) == 0  and  in_csv(seen, id) == 0) {
          ty = rhs_kind(body, j);
          out = _lia_cat(out ,  "    var ");
          out = _lia_cat(out ,  id);
          out = _lia_cat(out ,  ": ");
          out = _lia_cat(out ,  ty);
          if (starts_lit(ty, 0, "[]const u8") == 1) {
            out = _lia_cat(out ,  " = ");
            out = _lia_cat(out ,  q());
            out = _lia_cat(out ,  q());
            out = _lia_cat(out ,  ";\n");
          }
           else if (starts_lit(ty, 0, "bool") == 1) { out = _lia_cat(out ,  " = false;\n") ;}
           else { out = _lia_cat(out ,  " = 0;\n") ;}
          if (@as(i64, @intCast(seen.len)) == 0) { seen = id ;}
           else { seen = _lia_cat(seen ,  ","); seen = _lia_cat(seen ,  id) ;}
        }
      }
      i = i + @as(i64, @intCast(id.len));
    }
     else { i = i + 1 ;}
  }
  return out;

}

pub fn zig_pipe(body: []const u8) []const u8 {

  return kw_space(andor(rewrite_semi(rewrite_plus(rewrite_js_methods(rewrite_body(rewrite_cfor(rewrite_match(body))))))));

}

pub fn emit_fns(src: []const u8, lang: i64) []const u8 {
    var out: []const u8 = "";
    var name: []const u8 = "";
    var params: []const u8 = "";
    var body: []const u8 = "";
    var js_p: []const u8 = "";
    var zig_params: []const u8 = "";
    var id: []const u8 = "";
    var n: i64 = 0;
    var i: i64 = 0;
    var p: i64 = 0;
    var close_p: i64 = 0;
    var b: i64 = 0;
    var close_b: i64 = 0;
    var k: i64 = 0;
    var pn: i64 = 0;
    var seen: i64 = 0;

  out = "";
  name = "";
  params = "";
  body = "";
  js_p = "";
  zig_params = "";
  id = "";
  n = @as(i64, @intCast(src.len));
  i = 0;
  if (lang == 0) { out = "/* generated by lin-rewrite 2.0.0 */\n" ;}
   else { out = "// generated by LIN Zig bootstrap\n" ;}
  while (i < n) {
    i = skip_ws(src, i);
    if (i >= n) { return out ;}
    if (_lia_char_code_at(src, i) == 33  and  (i + 1 >= n  or  _lia_char_code_at(src, i + 1) != 61)) {
      name = read_ident(src, i + 1);
      if (@as(i64, @intCast(name.len)) > 0) {
        p = skip_ws(src, i + 1 + @as(i64, @intCast(name.len)));
        if (p < n  and  _lia_char_code_at(src, p) == 40) {
          close_p = p + 1;
          while (close_p < n  and  _lia_char_code_at(src, close_p) != 41) { close_p = close_p + 1 ;}
          params = slice2(src, p + 1, close_p);
          b = find_brace(src, close_p + 1);
          if (b >= 0) {
            close_b = match_brace(src, b);
            if (close_b > b) {
              body = slice2(src, b + 1, close_b);
              js_p = js_params(params);
              if (lang == 0) {
                out = _lia_cat(out ,  "function ");
                out = _lia_cat(out ,  name);
                out = _lia_cat(out ,  "(");
                out = _lia_cat(out ,  js_p);
                out = _lia_cat(out ,  "){");
                out = _lia_cat(out ,  rewrite_body(body));
                out = _lia_cat(out ,  "}\n");
              }
               else {
                zig_params = "";
                k = 0;
                pn = @as(i64, @intCast(params.len));
                seen = 0;
                while (k < pn) {
                  k = skip_ws(params, k);
                  if (k >= pn) { break ;}
                  id = read_ident(params, k);
                  if (@as(i64, @intCast(id.len)) > 0) {
                    if (seen == 1) { zig_params = _lia_cat(zig_params ,  ", ") ;}
                    zig_params = _lia_cat(zig_params ,  id);
                    zig_params = _lia_cat(zig_params ,  ": ");
                    zig_params = _lia_cat(zig_params ,  param_zig_type(params, k + @as(i64, @intCast(id.len))));
                    seen = 1;
                    k = skip_type(params, k + @as(i64, @intCast(id.len)));
                  }
                   else { k = k + 1 ;}
                  while (k < pn  and  _lia_char_code_at(params, k) != 44) { k = k + 1 ;}
                  if (k < pn  and  _lia_char_code_at(params, k) == 44) { k = k + 1 ;}
                }
                out = _lia_cat(out ,  "pub fn ");
                out = _lia_cat(out ,  name);
                out = _lia_cat(out ,  "(");
                out = _lia_cat(out ,  zig_params);
                out = _lia_cat(out ,  ") ");
                out = _lia_cat(out ,  fn_ret_type(src, close_p + 1, b));
                out = _lia_cat(out ,  " {\n");
                out = _lia_cat(out ,  zig_decls(body, js_p));
                out = _lia_cat(out ,  zig_pipe(body));
                out = _lia_cat(out ,  "\n}\n\n");
              }
              i = close_b + 1;
              continue;
            }
          }
        }
      }
    }
    i = i + 1;
  }
  return out;

}

pub fn lin_to_js(src: []const u8) []const u8 {
 return emit_fns(src, 0) ;
}

pub fn lin_to_zig(src: []const u8) []const u8 {
 return emit_fns(src, 1) ;
}

pub fn rewrite_inc(inc: []const u8) []const u8 {
    var out: []const u8 = "";
    var k: i64 = 0;
    var id: []const u8 = "";
    var p: i64 = 0;

  out = "";
  k = skip_ws(inc, 0);
  id = read_ident(inc, k);
  if (@as(i64, @intCast(id.len)) == 0) { return inc ;}
  p = skip_ws(inc, k + @as(i64, @intCast(id.len)));
  if (p + 1 < @as(i64, @intCast(inc.len))  and  _lia_char_code_at(inc, p) == 43  and  _lia_char_code_at(inc, p + 1) == 43) {
    out = id;
    out = _lia_cat(out ,  " = ");
    out = _lia_cat(out ,  id);
    out = _lia_cat(out ,  " + 1");
    return out;
  }
  return inc;

}

pub fn rewrite_cfor(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var cl: i64 = 0;
    var b: i64 = 0;
    var cb: i64 = 0;
    var inner: []const u8 = "";
    var s1: i64 = 0;
    var s2: i64 = 0;
    var k: i64 = 0;

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  cl = 0;
  b = 0;
  cb = 0;
  inner = "";
  s1 = 0;
  s2 = 0;
  k = 0;
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (_lia_char_code_at(s, i) == 35  and  i + 1 < n  and  _lia_char_code_at(s, i + 1) == 40) {
      cl = match_paren(s, i + 1);
      if (cl > i + 1) {
        b = find_brace(s, cl + 1);
        if (b >= 0) {
          cb = match_brace(s, b);
          if (cb > b) {
            inner = slice2(s, i + 2, cl);
            s1 = -1;
            s2 = -1;
            k = 0;
            while (k < @as(i64, @intCast(inner.len))) {
              if (_lia_char_code_at(inner, k) == 59) {
                if (s1 < 0) { s1 = k ;}
                 else { s2 = k ;}
              }
              k = k + 1;
            }
            if (s1 >= 0  and  s2 > s1) {
              out = _lia_cat(out ,  slice2(inner, 0, s1));
              out = _lia_cat(out ,  ";");
              out = _lia_cat(out ,  "while");
              out = _lia_cat(out ,  "(");
              out = _lia_cat(out ,  slice2(inner, s1 + 1, s2));
              out = _lia_cat(out ,  ")");
              out = _lia_cat(out ,  "{");
              out = _lia_cat(out ,  slice2(s, b + 1, cb));
              out = _lia_cat(out ,  ";");
              out = _lia_cat(out ,  rewrite_inc(slice2(inner, s2 + 1, @as(i64, @intCast(inner.len)))));
              out = _lia_cat(out ,  ";");
              out = _lia_cat(out ,  "}");
              i = cb + 1;
              continue;
            }
          }
        }
      }
    }
    chs = _lia_char_at(s, i);
    out = _lia_cat(out ,  chs);
    i = i + 1;
  }
  return out;

}

pub fn rewrite_match(s: []const u8) []const u8 {
    var out: []const u8 = "";
    var chs: []const u8 = "";
    var i: i64 = 0;
    var n: i64 = 0;
    var cl: i64 = 0;
    var b: i64 = 0;
    var cb: i64 = 0;
    var expr: []const u8 = "";
    var inner: []const u8 = "";
    var p: i64 = 0;
    var first: i64 = 0;
    var pat: []const u8 = "";
    var j: i64 = 0;
    var ab: i64 = 0;
    var arm: []const u8 = "";

  out = "";
  chs = "";
  i = 0;
  n = @as(i64, @intCast(s.len));
  cl = 0;
  b = 0;
  cb = 0;
  expr = "";
  inner = "";
  p = 0;
  first = 0;
  pat = "";
  j = 0;
  ab = 0;
  arm = "";
  while (i < n) {
    if (_lia_char_code_at(s, i) == 34) {
      out = _lia_cat(out ,  q());
      i = i + 1;
      while (i < n  and  _lia_char_code_at(s, i) != 34) {
        chs = _lia_char_at(s, i);
        out = _lia_cat(out ,  chs);
        i = i + 1;
      }
      if (i < n) { out = _lia_cat(out ,  q()); i = i + 1 ;}
      continue;
    }
    if (starts_lit(s, i, "match(") == 1) {
      cl = match_paren(s, i + 5);
      if (cl > i) {
        b = find_brace(s, cl + 1);
        if (b >= 0) {
          cb = match_brace(s, b);
          if (cb > b) {
            expr = slice2(s, i + 6, cl);
            inner = slice2(s, b + 1, cb);
            p = 0;
            first = 1;
            while (p < @as(i64, @intCast(inner.len))) {
              p = skip_ws(inner, p);
              if (p >= @as(i64, @intCast(inner.len))) { break ;}
              if (_lia_char_code_at(inner, p) == 95) {
                p = skip_ws(inner, p + 1);
                if (p + 1 < @as(i64, @intCast(inner.len))  and  _lia_char_code_at(inner, p) == 61  and  _lia_char_code_at(inner, p + 1) == 62) {
                  p = skip_ws(inner, p + 2);
                  if (p < @as(i64, @intCast(inner.len))  and  _lia_char_code_at(inner, p) == 123) {
                    ab = match_brace(inner, p);
                    if (ab > p) {
                      arm = slice2(inner, p + 1, ab);
                      if (first == 1) { out = _lia_cat(out ,  "{") ;}
                       else { out = _lia_cat(out ,  ":{") ;}
                      out = _lia_cat(out ,  arm);
                      out = _lia_cat(out ,  "}");
                      first = 0;
                      p = ab + 1;
                      continue;
                    }
                  }
                }
              }
              pat = "";
              if (_lia_char_code_at(inner, p) >= 48  and  _lia_char_code_at(inner, p) <= 57) {
                j = p;
                while (j < @as(i64, @intCast(inner.len))  and  _lia_char_code_at(inner, j) >= 48  and  _lia_char_code_at(inner, j) <= 57) { j = j + 1 ;}
                pat = slice2(inner, p, j);
                p = j;
              }
               else {
                pat = read_ident(inner, p);
                if (@as(i64, @intCast(pat.len)) == 0) { break ;}
                p = p + @as(i64, @intCast(pat.len));
              }
              p = skip_ws(inner, p);
              if (p + 1 < @as(i64, @intCast(inner.len))  and  _lia_char_code_at(inner, p) == 61  and  _lia_char_code_at(inner, p + 1) == 62) {
                p = skip_ws(inner, p + 2);
                if (p < @as(i64, @intCast(inner.len))  and  _lia_char_code_at(inner, p) == 123) {
                  ab = match_brace(inner, p);
                  if (ab > p) {
                    arm = slice2(inner, p + 1, ab);
                    if (first == 1) { out = _lia_cat(out ,  "?(") ;}
                     else { out = _lia_cat(out ,  ":?(") ;}
                    out = _lia_cat(out ,  expr);
                    out = _lia_cat(out ,  "==");
                    out = _lia_cat(out ,  pat);
                    out = _lia_cat(out ,  "){");
                    out = _lia_cat(out ,  arm);
                    out = _lia_cat(out ,  "}");
                    first = 0;
                    p = ab + 1;
                    continue;
                  }
                }
              }
              break;
            }
            i = cb + 1;
            continue;
          }
        }
      }
    }
    chs = _lia_char_at(s, i);
    out = _lia_cat(out ,  chs);
    i = i + 1;
  }
  return out;

}


fn argEq(a: []const u8, b: []const u8) bool {
    return std.mem.eql(u8, a, b);
}

fn endsLin(name: []const u8) bool {
    if (std.mem.endsWith(u8, name, ".test.lin") or std.mem.eql(u8, name, "run_all.lin")) return false;
    return name.len >= 4 and std.mem.endsWith(u8, name, ".lin");
}

fn apply_dynamic_rules_if_present(allocator: std.mem.Allocator, src: []const u8) []const u8 {
    const rules_file = std.fs.cwd().openFile("storage/dynamic_rules.rulel", .{}) catch return src;
    rules_file.close();

    const rules_content = std.fs.cwd().readFileAlloc(allocator, "storage/dynamic_rules.rulel", 1024 * 1024) catch return src;
    defer allocator.free(rules_content);
    if (std.mem.indexOf(u8, rules_content, "RULE_TERNARY_R17_CANONICAL_LAZY") == null) {
        return src;
    }

    var s: []const u8 = src;
    var iterations: usize = 0;
    while (iterations < 100) : (iterations += 1) {
        var changed = false;
        var i: usize = 0;
        while (i < s.len) : (i += 1) {
            const is_ret = (s[i] == '^' and i + 1 < s.len and s[i + 1] == '(');
            const sp: ?usize = if (is_ret) i + 1 else if (s[i] == '(') i else null;
            if (sp) |start_p| {
                var depth: i64 = 0;
                var close_p: ?usize = null;
                var j: usize = start_p;
                while (j < s.len) : (j += 1) {
                    if (s[j] == '(') depth += 1
                    else if (s[j] == ')') {
                        depth -= 1;
                        if (depth == 0) { close_p = j; break; }
                    }
                }
                if (close_p) |cp| {
                    const inside = s[start_p + 1 .. cp];
                    var pdepth: i64 = 0;
                    var q_idx: ?usize = null;
                    var c_idx: ?usize = null;
                    var k: usize = 0;
                    while (k < inside.len) : (k += 1) {
                        if (inside[k] == '(') pdepth += 1
                        else if (inside[k] == ')') pdepth -= 1
                        else if (pdepth == 0) {
                            if (q_idx == null and k + 2 < inside.len and inside[k] == ' ' and inside[k + 1] == '?' and inside[k + 2] == ' ') {
                                q_idx = k;
                            } else if (q_idx != null and c_idx == null and k + 2 < inside.len and inside[k] == ' ' and inside[k + 1] == ':' and inside[k + 2] == ' ') {
                                c_idx = k;
                            }
                        }
                    }
                    if (q_idx != null and c_idx != null) {
                        const raw_cond = std.mem.trim(u8, inside[0..q_idx.?], " \t\r\n");
                        const val_a = std.mem.trim(u8, inside[q_idx.? + 3 .. c_idx.?], " \t\r\n");
                        const val_b = std.mem.trim(u8, inside[c_idx.? + 3 ..], " \t\r\n");

                        const has_cmp = (std.mem.indexOf(u8, raw_cond, "==") != null or std.mem.indexOf(u8, raw_cond, "!=") != null or std.mem.indexOf(u8, raw_cond, "<") != null or std.mem.indexOf(u8, raw_cond, ">") != null);
                        const cond = if (has_cmp) raw_cond else (std.fmt.allocPrint(allocator, "(({s}) != 0)", .{raw_cond}) catch raw_cond);

                        var repl = std.ArrayList(u8).init(allocator);
                        defer repl.deinit();
                        if (is_ret) {
                            repl.writer().print("?({s}){{ ^{s} }} : {{ ^{s} }}", .{ cond, val_a, val_b }) catch {};
                        } else {
                            repl.writer().print("(if ({s}) {s} else {s})", .{ cond, val_a, val_b }) catch {};
                        }

                        const prefix = s[0..i];
                        const suffix = s[cp + 1 ..];
                        s = std.mem.concat(allocator, u8, &.{ prefix, repl.items, suffix }) catch s;
                        changed = true;
                        break;
                    } else if (std.mem.indexOf(u8, rules_content, "RULE_COALESCE_R20_PROMOTED_FALLBACK") != null and std.mem.indexOf(u8, inside, " ?? ") != null) {
                        const qq_pos = std.mem.indexOf(u8, inside, " ?? ").?;
                        const val_a = std.mem.trim(u8, inside[0..qq_pos], " \t\r\n");
                        const val_b = std.mem.trim(u8, inside[qq_pos + 4 ..], " \t\r\n");

                        var repl = std.ArrayList(u8).init(allocator);
                        defer repl.deinit();
                        if (is_ret) {
                            repl.writer().print("?({s} != -1){{ ^{s} }} : {{ ^{s} }}", .{ val_a, val_a, val_b }) catch {};
                        } else {
                            repl.writer().print("(if ({s} != -1) {s} else {s})", .{ val_a, val_a, val_b }) catch {};
                        }

                        const prefix = s[0..i];
                        const suffix = s[cp + 1 ..];
                        s = std.mem.concat(allocator, u8, &.{ prefix, repl.items, suffix }) catch s;
                        changed = true;
                        break;
                    }
                }
            }
        }
        if (!changed) break;
    }
    return s;
}

fn runLinTestFile(path: []const u8) !std.process.Child.RunResult {
    const raw_src = try std.fs.cwd().readFileAlloc(LIA_ALLOC, path, 10 * 1024 * 1024);
    defer LIA_ALLOC.free(raw_src);
    const src = apply_dynamic_rules_if_present(LIA_ALLOC, raw_src);
    if (lin_valid(src) == 0) return error.LinParse;
    const names = lin_check(src);
    const fns = lin_to_zig(src);
    const host = try std.fs.cwd().readFileAlloc(LIA_ALLOC, "src/lin.zig", 10 * 1024 * 1024);
    defer LIA_ALLOC.free(host);
    const m_fn = std.mem.indexOf(u8, host, "\npub fn slice2(") orelse return error.MissingRuntime;
    var main_body = std.ArrayList(u8).init(LIA_ALLOC);
    defer main_body.deinit();
    const mw = main_body.writer();
    try mw.writeAll("pub fn main() !void {\n    LIA_ALLOC = std.heap.page_allocator;\n    var fails: i64 = 0;\n");
    var it = std.mem.splitScalar(u8, names, ',');
    var ntests: i64 = 0;
    while (it.next()) |raw| {
        const name = std.mem.trim(u8, raw, " \t");
        if (name.len >= 5 and std.mem.startsWith(u8, name, "test_")) {
            ntests += 1;
            try mw.print("    if ({s}() != 1) {{ fails += 1; std.debug.print(\"FAIL {s}\\n\", .{{}}); }}\n", .{ name, name });
        }
    }
    try mw.writeAll("    if (fails != 0) std.process.exit(1);\n    std.debug.print(\"ok ");
    try mw.print("{d}", .{ntests});
    try mw.writeAll("\\n\", .{});\n}\n");
    const zig_src = try std.mem.concat(LIA_ALLOC, u8, &.{ host[0..m_fn], "\n", fns, "\n", main_body.items });
    defer LIA_ALLOC.free(zig_src);
    const tmp_path = "src/lin_test_run.zig";
    const tf = try std.fs.cwd().createFile(tmp_path, .{});
    defer tf.close();
    try tf.writeAll(zig_src);
    var zb: []const u8 = "zig";
    if (std.fs.openFileAbsolute("/home/k/.local/bin/zig", .{})) |zf| {
        zf.close();
        zb = "/home/k/.local/bin/zig";
    } else |_| {}
    return std.process.Child.run(.{
        .allocator = LIA_ALLOC,
        .argv = &.{ zb, "run", "-O", "ReleaseFast", tmp_path },
        .max_output_bytes = 1024 * 1024,
    });
}

const ZIG_RUNTIME_PRELUDE =
    \\const std = @import("std");
    \\pub var LIA_ALLOC: std.mem.Allocator = undefined;
    \\fn _lia_str(x: anytype) []const u8 {
    \\    const T = @TypeOf(x);
    \\    switch (@typeInfo(T)) {
    \\        .Pointer => |p| {
    \\            if (p.size == .Slice and p.child == u8) return x;
    \\            if (p.size == .One) {
    \\                switch (@typeInfo(p.child)) {
    \\                    .Array => |a| { if (a.child == u8) return x[0..]; },
    \\                    else => {},
    \\                }
    \\            }
    \\        },
    \\        .Bool => return if (x) "true" else "false",
    \\        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
    \\        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
    \\        else => {},
    \\    }
    \\    return "";
    \\}
    \\pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    \\    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
    \\}
    \\fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    \\    if (i < 0) return "";
    \\    const idx = @as(usize, @intCast(i));
    \\    if (idx < s.len) return s[idx .. idx + 1];
    \\    return "";
    \\}
    \\fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    \\    if (i < 0) return 0;
    \\    const idx = @as(usize, @intCast(i));
    \\    if (idx < s.len) return @as(i64, s[idx]);
    \\    return 0;
    \\}
    \\fn _lia_from_code(c: i64) []const u8 {
    \\    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    \\    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
    \\}
    \\fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    \\    if (a < 0 or b < 0) return "";
    \\    var start = @as(usize, @intCast(a));
    \\    var end = @as(usize, @intCast(b));
    \\    if (start > s.len) start = s.len;
    \\    if (end > s.len) end = s.len;
    \\    if (start >= end) return "";
    \\    return s[start..end];
    \\}
    \\fn _lia_shl(a: i64, b: i64) i64 {
    \\    if (b < 0 or b >= 64) return 0;
    \\    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    \\    return a << shift;
    \\}
    \\fn _lia_shr(a: i64, b: i64) i64 {
    \\    if (b < 0 or b >= 64) return 0;
    \\    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    \\    return a >> shift;
    \\}
;

pub fn pick_target(src: []const u8, explicit: []const u8) []const u8 {
    if (explicit.len > 0 and !argEq(explicit, "auto")) return explicit;
    const zig_code = lin_to_zig(src);
    defer LIA_ALLOC.free(zig_code);
    const full = _lia_cat(ZIG_RUNTIME_PRELUDE, zig_code);
    defer LIA_ALLOC.free(full);
    const tmp_file = ".lin_ast_check.zig";
    if (std.fs.cwd().createFile(tmp_file, .{})) |f| {
        defer f.close();
        f.writeAll(full) catch return "js";
    } else |_| return "js";
    var zb: []const u8 = "zig";
    if (std.fs.openFileAbsolute("/home/k/.local/bin/zig", .{})) |zf| {
        zf.close();
        zb = "/home/k/.local/bin/zig";
    } else |_| {}
    const r = std.process.Child.run(.{
        .allocator = LIA_ALLOC,
        .argv = &.{ zb, "ast-check", tmp_file },
        .max_output_bytes = 64 * 1024,
    }) catch return "js";
    if (r.term == .Exited and r.term.Exited == 0) return "zig";
    return "js";
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    LIA_ALLOC = gpa.allocator();
    const stdout = std.io.getStdOut().writer();
    const stderr = std.io.getStdErr().writer();
    const args = try std.process.argsAlloc(LIA_ALLOC);
    defer std.process.argsFree(LIA_ALLOC, args);
    if (args.len < 2) {
        try stdout.print("2.0.0\n", .{});
        return;
    }
    const cmd = args[1];
    if (argEq(cmd, "version") or argEq(cmd, "-v") or argEq(cmd, "--version")) {
        try stdout.print("2.0.0\n", .{});
        return;
    }
    if (argEq(cmd, "rebuild")) {
        const boot = try std.fs.cwd().readFileAlloc(LIA_ALLOC, "src/lin_zig_bootstrap.lin", 10 * 1024 * 1024);
        defer LIA_ALLOC.free(boot);
        const em = try std.fs.cwd().readFileAlloc(LIA_ALLOC, "src/lin_zig_emit.lin", 10 * 1024 * 1024);
        defer LIA_ALLOC.free(em);
        const mt = try std.fs.cwd().readFileAlloc(LIA_ALLOC, "src/lin_zig_match.lin", 10 * 1024 * 1024);
        defer LIA_ALLOC.free(mt);
        const src = try std.mem.concat(LIA_ALLOC, u8, &.{ boot, "\n", em, "\n", mt });
        defer LIA_ALLOC.free(src);
        const fns = lin_to_zig(src);
        const host = try std.fs.cwd().readFileAlloc(LIA_ALLOC, "src/lin.zig", 10 * 1024 * 1024);
        defer LIA_ALLOC.free(host);
        const m_fn = std.mem.indexOf(u8, host, "\npub fn slice2(") orelse {
            try stderr.print("rebuild: missing slice2 marker\n", .{});
            std.process.exit(1);
        };
        const m_cli = std.mem.indexOf(u8, host, "\nfn argEq(") orelse {
            try stderr.print("rebuild: missing argEq marker\n", .{});
            std.process.exit(1);
        };
        const next = try std.mem.concat(LIA_ALLOC, u8, &.{ host[0..m_fn], "\n", fns, host[m_cli..] });
        defer LIA_ALLOC.free(next);
        const tf = try std.fs.cwd().createFile("src/lin.zig", .{});
        defer tf.close();
        try tf.writeAll(next);
        try stdout.print("{{\"rebuilt\":\"src/lin.zig\",\"fns\":{d}}}\n", .{fns.len});
        return;
    }
    var target: []const u8 = "auto";
    var out_path: ?[]const u8 = null;
    var file_path: ?[]const u8 = null;
    var ai: usize = 2;
    while (ai < args.len) : (ai += 1) {
        if (argEq(args[ai], "--target") and ai + 1 < args.len) {
            ai += 1;
            target = args[ai];
        } else if (argEq(args[ai], "-o") and ai + 1 < args.len) {
            ai += 1;
            out_path = args[ai];
        } else if (args[ai][0] != '-') file_path = args[ai];
    }
    if (argEq(cmd, "test")) {
        const p = file_path orelse "test";
        if (std.fs.cwd().openDir(p, .{ .iterate = true })) |dir_val| {
            var dir = dir_val;
            defer dir.close();
            var tot: i64 = 0;
            var it = dir.iterate();
            while (try it.next()) |ent| {
                if (ent.kind != .file or !endsLin(ent.name)) continue;
                const full = try std.fs.path.join(LIA_ALLOC, &.{ p, ent.name });
                defer LIA_ALLOC.free(full);
                try stdout.print("{s}: ", .{full});
                const rr = runLinTestFile(full) catch |err| {
                    try stderr.print("test: {s}: {s}\n", .{ full, @errorName(err) });
                    std.process.exit(1);
                };
                defer LIA_ALLOC.free(rr.stdout);
                defer LIA_ALLOC.free(rr.stderr);
                try stdout.writeAll(rr.stdout);
                try stderr.writeAll(rr.stderr);
                switch (rr.term) {
                    .Exited => |c| if (c != 0) std.process.exit(1),
                    else => std.process.exit(1),
                }
                tot += 1;
            }
            try stdout.print("suite {d}\n", .{tot});
            if (std.mem.eql(u8, p, "test")) {
                if (std.fs.cwd().openDir("test/fail", .{ .iterate = true })) |fail_dir_val| {
                    var fail_dir = fail_dir_val;
                    defer fail_dir.close();
                    var fit = fail_dir.iterate();
                    while (try fit.next()) |ent| {
                        if (ent.kind != .file or !endsLin(ent.name)) continue;
                        const full = try std.fs.path.join(LIA_ALLOC, &.{ "test/fail", ent.name });
                        defer LIA_ALLOC.free(full);
                        const bad = try std.fs.cwd().readFileAlloc(LIA_ALLOC, full, 1024 * 1024);
                        defer LIA_ALLOC.free(bad);
                        if (lin_valid(bad) != 0) {
                            try stderr.print("FAIL expected parse error: {s}\n", .{full});
                            std.process.exit(1);
                        }
                        try stdout.print("{s}: ok fail-closed\n", .{full});
                    }
                } else |_| {}
            }
            return;
        } else |_| {}
        const rr = runLinTestFile(p) catch |err| {
            try stderr.print("test: {s}\n", .{@errorName(err)});
            std.process.exit(1);
        };
        defer LIA_ALLOC.free(rr.stdout);
        defer LIA_ALLOC.free(rr.stderr);
        try stdout.writeAll(rr.stdout);
        try stderr.writeAll(rr.stderr);
        switch (rr.term) {
            .Exited => |c| if (c != 0) std.process.exit(1),
            else => std.process.exit(1),
        }
        return;
    }
    if (file_path == null) {
        try stderr.print("Error: missing file\n", .{});
        std.process.exit(1);
    }
    const file = try std.fs.cwd().openFile(file_path.?, .{});
    defer file.close();
    const raw_src = try file.readToEndAlloc(LIA_ALLOC, 10 * 1024 * 1024);
    defer LIA_ALLOC.free(raw_src);
    const src = apply_dynamic_rules_if_present(LIA_ALLOC, raw_src);
    if (argEq(cmd, "check")) {
        if (lin_syntax_valid(src) == 0) {
            try stderr.print("LIN_PARSE\n", .{});
            std.process.exit(1);
        }
        if (lin_type_check(src)) |err_msg| {
            try stderr.print("{s}\n", .{err_msg});
            std.process.exit(1);
        }
        try stdout.print("{s}\n", .{lin_check_json(src)});
        return;
    }
    if (argEq(cmd, "compile")) {
        const chosen = pick_target(src, target);
        const code = if (argEq(chosen, "zig")) _lia_cat(ZIG_RUNTIME_PRELUDE, lin_to_zig(src)) else lin_to_js(src);
        if (out_path) |op| {
            const f = try std.fs.cwd().createFile(op, .{});
            defer f.close();
            try f.writeAll(code);
            try stdout.print("{{\"out\":\"{s}\",\"target\":\"{s}\"}}\n", .{ op, chosen });
        } else try stdout.print("{s}", .{code});
        return;
    }
    try stderr.print("Error: command not in Zig host yet\n", .{});
    std.process.exit(2);
}
