const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a << shift;
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn shr32(x: i64, n: i64) i64 {

  return (_lia_shr(x & 4294967295, n))
;
}

pub fn rotr32(x: i64, n: i64) i64 {
    var u: i64 = 0;

  u = x & 4294967295;
  return (_lia_shr(u, n) | _lia_shl(u, 32 - n)) & 4294967295
;
}

pub fn ch32(x: i64, y: i64, z: i64) i64 {

  return ((x & y) ^ ((~x) & z)) & 4294967295
;
}

pub fn maj32(x: i64, y: i64, z: i64) i64 {

  return ((x & y) ^ (x & z) ^ (y & z)) & 4294967295
;
}

pub fn sigma0_32(x: i64) i64 {

  return (rotr32(x, 2) ^ rotr32(x, 13) ^ rotr32(x, 22)) & 4294967295
;
}

pub fn sigma1_32(x: i64) i64 {

  return (rotr32(x, 6) ^ rotr32(x, 11) ^ rotr32(x, 25)) & 4294967295
;
}

pub fn gamma0_32(x: i64) i64 {

  return (rotr32(x, 7) ^ rotr32(x, 18) ^ shr32(x, 3)) & 4294967295
;
}

pub fn gamma1_32(x: i64) i64 {

  return (rotr32(x, 17) ^ rotr32(x, 19) ^ shr32(x, 10)) & 4294967295
;
}

pub fn sha_k(i: i64) i64 {
    var k: [64]i64 = [_]i64{0} ** 64;

  k= [_]i64{1116352408, 1899447441, 3049323471, 3921009573, 961987163, 1508970993, 2453635748, 2870763221, 3624381080, 310598401, 607225278, 1426881987, 1925078388, 2162078206, 2614888103, 3248222580, 3835390401, 4022224774, 264347078, 604807628, 770255983, 1249150122, 1555081692, 1996064986, 2554220882, 2821834349, 2952996808, 3210313671, 3336571891, 3584528711, 113926993, 338241895, 666307205, 773529912, 1294757372, 1396182291, 1695183700, 1986661051, 2177026350, 2456956037, 2730485921, 2820302411, 3259730800, 3345764771, 3516065817, 3600352804, 4094571909, 275423344, 430227734, 506948616, 659060556, 883997877, 958139571, 1322822218, 1537002063, 1747873779, 1955562222, 2024104815, 2227730452, 2361852424, 2428436474, 2756734187, 3204031479, 3329325298};
  return k[_lia_idx(i)];

}

pub fn sha256_nist_abc(sel: i64) i64 {
    var W: [64]i64 = [_]i64{0} ** 64;
    var i: i64 = 0;
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var d: i64 = 0;
    var e: i64 = 0;
    var f: i64 = 0;
    var g: i64 = 0;
    var h: i64 = 0;
    var t1: i64 = 0;
    var t2: i64 = 0;
    var r0: i64 = 0;
    var r1: i64 = 0;
    var r2: i64 = 0;
    var r3: i64 = 0;
    var r4: i64 = 0;
    var r5: i64 = 0;
    var r6: i64 = 0;
    var r7: i64 = 0;

  
  W[_lia_idx(0)] = 1633837952;
  W[_lia_idx(1)] = 0; W[_lia_idx(2)] = 0; W[_lia_idx(3)] = 0; W[_lia_idx(4)] = 0; W[_lia_idx(5)] = 0; W[_lia_idx(6)] = 0; W[_lia_idx(7)] = 0;
  W[_lia_idx(8)] = 0; W[_lia_idx(9)] = 0; W[_lia_idx(10)] = 0; W[_lia_idx(11)] = 0; W[_lia_idx(12)] = 0; W[_lia_idx(13)] = 0; W[_lia_idx(14)] = 0;
  W[_lia_idx(15)] = 24;
  i = 16;
  while (i < 64) {
    W[_lia_idx(i)] = (gamma1_32(W[_lia_idx(i - 2)]) + W[_lia_idx(i - 7)] + gamma0_32(W[_lia_idx(i - 15)]) + W[_lia_idx(i - 16)]) & 4294967295;
    i = i + 1;
  }
  a = 1779033703; b = 3144134277; c = 1013904242; d = 2773480762;
  e = 1359893119; f = 2600822924; g = 528734635; h = 1541459225;
  i = 0;
  t1 = 0;
  t2 = 0;
  while (i < 64) {
    t1 = (h + sigma1_32(e) + ch32(e, f, g) + sha_k(i) + W[_lia_idx(i)]) & 4294967295;
    t2 = (sigma0_32(a) + maj32(a, b, c)) & 4294967295;
    h = g; g = f; f = e; e = (d + t1) & 4294967295;
    d = c; c = b; b = a; a = (t1 + t2) & 4294967295;
    i = i + 1;
  }
  r0 = (1779033703 + a) & 4294967295;
  r1 = (3144134277 + b) & 4294967295;
  r2 = (1013904242 + c) & 4294967295;
  r3 = (2773480762 + d) & 4294967295;
  r4 = (1359893119 + e) & 4294967295;
  r5 = (2600822924 + f) & 4294967295;
  r6 = (528734635 + g) & 4294967295;
  r7 = (1541459225 + h) & 4294967295;
  if (sel == 0) { return r0 ;}
  if (sel == 1) { return r1 ;}
  if (sel == 2) { return r2 ;}
  if (sel == 3) { return r3 ;}
  if (sel == 4) { return r4 ;}
  if (sel == 5) { return r5 ;}
  if (sel == 6) { return r6 ;}
  if (sel == 7) { return r7 ;}
  return (r0 ^ r1 ^ r2 ^ r3 ^ r4 ^ r5 ^ r6 ^ r7) & 4294967295;

}

pub fn btc_sha256d_sel(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0_in: i64, w1_in: i64, w2_in: i64, nonce: i64, sel: i64) i64 {
    var W: [64]i64 = [_]i64{0} ** 64;
    var i: i64 = 0;
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var d: i64 = 0;
    var e: i64 = 0;
    var f: i64 = 0;
    var g: i64 = 0;
    var h: i64 = 0;
    var t1: i64 = 0;
    var t2: i64 = 0;
    var h1_0: i64 = 0;
    var h1_1: i64 = 0;
    var h1_2: i64 = 0;
    var h1_3: i64 = 0;
    var h1_4: i64 = 0;
    var h1_5: i64 = 0;
    var h1_6: i64 = 0;
    var h1_7: i64 = 0;
    var r0: i64 = 0;
    var r1: i64 = 0;
    var r2: i64 = 0;
    var r3: i64 = 0;
    var r4: i64 = 0;
    var r5: i64 = 0;
    var r6: i64 = 0;
    var r7: i64 = 0;

  
  W[_lia_idx(0)] = w0_in; W[_lia_idx(1)] = w1_in; W[_lia_idx(2)] = w2_in; W[_lia_idx(3)] = nonce;
  W[_lia_idx(4)] = 2147483648; W[_lia_idx(5)] = 0; W[_lia_idx(6)] = 0; W[_lia_idx(7)] = 0;
  W[_lia_idx(8)] = 0; W[_lia_idx(9)] = 0; W[_lia_idx(10)] = 0; W[_lia_idx(11)] = 0;
  W[_lia_idx(12)] = 0; W[_lia_idx(13)] = 0; W[_lia_idx(14)] = 0; W[_lia_idx(15)] = 640;
  i = 16;
  while (i < 64) {
    W[_lia_idx(i)] = (gamma1_32(W[_lia_idx(i - 2)]) + W[_lia_idx(i - 7)] + gamma0_32(W[_lia_idx(i - 15)]) + W[_lia_idx(i - 16)]) & 4294967295;
    i = i + 1;
  }
  a = m0; b = m1; c = m2; d = m3; e = m4; f = m5; g = m6; h = m7;
  i = 0;
  t1 = 0;
  t2 = 0;
  while (i < 64) {
    t1 = (h + sigma1_32(e) + ch32(e, f, g) + sha_k(i) + W[_lia_idx(i)]) & 4294967295;
    t2 = (sigma0_32(a) + maj32(a, b, c)) & 4294967295;
    h = g; g = f; f = e; e = (d + t1) & 4294967295;
    d = c; c = b; b = a; a = (t1 + t2) & 4294967295;
    i = i + 1;
  }
  h1_0 = (m0 + a) & 4294967295;
  h1_1 = (m1 + b) & 4294967295;
  h1_2 = (m2 + c) & 4294967295;
  h1_3 = (m3 + d) & 4294967295;
  h1_4 = (m4 + e) & 4294967295;
  h1_5 = (m5 + f) & 4294967295;
  h1_6 = (m6 + g) & 4294967295;
  h1_7 = (m7 + h) & 4294967295;
  W[_lia_idx(0)] = h1_0; W[_lia_idx(1)] = h1_1; W[_lia_idx(2)] = h1_2; W[_lia_idx(3)] = h1_3;
  W[_lia_idx(4)] = h1_4; W[_lia_idx(5)] = h1_5; W[_lia_idx(6)] = h1_6; W[_lia_idx(7)] = h1_7;
  W[_lia_idx(8)] = 2147483648; W[_lia_idx(9)] = 0; W[_lia_idx(10)] = 0; W[_lia_idx(11)] = 0;
  W[_lia_idx(12)] = 0; W[_lia_idx(13)] = 0; W[_lia_idx(14)] = 0; W[_lia_idx(15)] = 256;
  i = 16;
  while (i < 64) {
    W[_lia_idx(i)] = (gamma1_32(W[_lia_idx(i - 2)]) + W[_lia_idx(i - 7)] + gamma0_32(W[_lia_idx(i - 15)]) + W[_lia_idx(i - 16)]) & 4294967295;
    i = i + 1;
  }
  a = 1779033703; b = 3144134277; c = 1013904242; d = 2773480762;
  e = 1359893119; f = 2600822924; g = 528734635; h = 1541459225;
  i = 0;
  while (i < 64) {
    t1 = (h + sigma1_32(e) + ch32(e, f, g) + sha_k(i) + W[_lia_idx(i)]) & 4294967295;
    t2 = (sigma0_32(a) + maj32(a, b, c)) & 4294967295;
    h = g; g = f; f = e; e = (d + t1) & 4294967295;
    d = c; c = b; b = a; a = (t1 + t2) & 4294967295;
    i = i + 1;
  }
  r0 = (1779033703 + a) & 4294967295;
  r1 = (3144134277 + b) & 4294967295;
  r2 = (1013904242 + c) & 4294967295;
  r3 = (2773480762 + d) & 4294967295;
  r4 = (1359893119 + e) & 4294967295;
  r5 = (2600822924 + f) & 4294967295;
  r6 = (528734635 + g) & 4294967295;
  r7 = (1541459225 + h) & 4294967295;
  if (sel == 0) { return r0 ;}
  if (sel == 1) { return r1 ;}
  if (sel == 2) { return r2 ;}
  if (sel == 3) { return r3 ;}
  if (sel == 4) { return r4 ;}
  if (sel == 5) { return r5 ;}
  if (sel == 6) { return r6 ;}
  if (sel == 7) { return r7 ;}
  return (r0 ^ r1 ^ r2 ^ r3 ^ r4 ^ r5 ^ r6 ^ r7) & 4294967295;

}

pub fn btc_pow_verify(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64) i64 {

  return btc_sha256d_sel(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, 7);

}

pub fn btc_sha256d_h0(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64) i64 {

  return btc_sha256d_sel(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, 0);

}

pub fn btc_sha256d_fold(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64) i64 {

  return btc_sha256d_sel(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, 8);

}

pub fn btc_mine_nonce(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, start_nonce: i64, count: i64) i64 {
    var nonce: i64 = 0;
    var end_nonce: i64 = 0;
    var res: i64 = 0;

  nonce = start_nonce;
  end_nonce = start_nonce + count;
  res = 1;
  while (nonce < end_nonce) {
    res = btc_pow_verify(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce);
    if (res == 0) {
      return nonce;
    }
    nonce = nonce + 1;
  }
  return -1;

}

pub fn bswap32(x: i64) i64 {
    var u: i64 = 0;

  u = x & 4294967295;
  return (_lia_shl(u & 255, 24) | _lia_shl(_lia_shr(u, 8) & 255, 16) | _lia_shl(_lia_shr(u, 16) & 255, 8) | _lia_shr(u, 24)) & 4294967295;

}

pub fn clz32(x: i64) i64 {
    var u: i64 = 0;
    var n: i64 = 0;

  u = x & 4294967295;
  if (u == 0) { return 32 ;}
  n = 0;
  if (u <= 65535) { n = n + 16; u = _lia_shl(u, 16) & 4294967295; }
  if (u <= 16777215) { n = n + 8; u = _lia_shl(u, 8) & 4294967295; }
  if (u <= 268435455) { n = n + 4; u = _lia_shl(u, 4) & 4294967295; }
  if (u <= 1073741823) { n = n + 2; u = _lia_shl(u, 2) & 4294967295; }
  if (u <= 2147483647) { n = n + 1; }
  return n;

}

pub fn nbits_put_byte(word: i64, pos: i64, b: i64) i64 {

  return ((word | _lia_shl(b & 255, _lia_shl(3 - pos, 3))) & 4294967295);

}

pub fn nbits_target_word(nbits: i64, wi: i64) i64 {
    var tgt: [8]i64 = [_]i64{0} ** 8;
    var nSize: i64 = 0;
    var mant: i64 = 0;
    var byte0: i64 = 0;
    var w0: i64 = 0;
    var p0: i64 = 0;
    var byte1: i64 = 0;
    var w1: i64 = 0;
    var p1: i64 = 0;
    var byte2: i64 = 0;
    var w2: i64 = 0;
    var p2: i64 = 0;

  
  tgt[_lia_idx(0)] = 0; tgt[_lia_idx(1)] = 0; tgt[_lia_idx(2)] = 0; tgt[_lia_idx(3)] = 0;
  tgt[_lia_idx(4)] = 0; tgt[_lia_idx(5)] = 0; tgt[_lia_idx(6)] = 0; tgt[_lia_idx(7)] = 0;
  nSize = _lia_shr(nbits, 24) & 255;
  mant = nbits & 8388607;
  if (nSize <= 3) {
    tgt[_lia_idx(7)] = _lia_shr(mant, _lia_shl(3 - nSize, 3)) & 4294967295;
    return tgt[_lia_idx(wi)];
  }
  if (nSize > 32) { return 0 ;}
  byte0 = 32 - nSize;
  w0 = _lia_shr(byte0, 2);
  p0 = byte0 - _lia_shl(w0, 2);
  tgt[_lia_idx(w0)] = nbits_put_byte(tgt[_lia_idx(w0)], p0, _lia_shr(mant, 16) & 255);
  byte1 = byte0 + 1;
  w1 = _lia_shr(byte1, 2);
  p1 = byte1 - _lia_shl(w1, 2);
  tgt[_lia_idx(w1)] = nbits_put_byte(tgt[_lia_idx(w1)], p1, _lia_shr(mant, 8) & 255);
  byte2 = byte0 + 2;
  w2 = _lia_shr(byte2, 2);
  p2 = byte2 - _lia_shl(w2, 2);
  tgt[_lia_idx(w2)] = nbits_put_byte(tgt[_lia_idx(w2)], p2, mant & 255);
  return tgt[_lia_idx(wi)];

}

pub fn btc_pow_digest_then(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0_in: i64, w1_in: i64, w2_in: i64, nonce: i64, nbits: i64, want: i64) i64 {
    var w: [16]i64 = [_]i64{0} ** 16;
    var a: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var d: i64 = 0;
    var e: i64 = 0;
    var f: i64 = 0;
    var g: i64 = 0;
    var h: i64 = 0;
    var i: i64 = 0;
    var cur_w: i64 = 0;
    var t1: i64 = 0;
    var t2: i64 = 0;
    var h1_0: i64 = 0;
    var h1_1: i64 = 0;
    var h1_2: i64 = 0;
    var h1_3: i64 = 0;
    var h1_4: i64 = 0;
    var h1_5: i64 = 0;
    var h1_6: i64 = 0;
    var h1_7: i64 = 0;
    var r0: i64 = 0;
    var r1: i64 = 0;
    var r2: i64 = 0;
    var r3: i64 = 0;
    var r4: i64 = 0;
    var r5: i64 = 0;
    var r6: i64 = 0;
    var r7: i64 = 0;
    var disp: [8]i64 = [_]i64{0} ** 8;
    var n: i64 = 0;
    var tw: i64 = 0;

  
  w[_lia_idx(0)] = w0_in; w[_lia_idx(1)] = w1_in; w[_lia_idx(2)] = w2_in; w[_lia_idx(3)] = nonce;
  w[_lia_idx(4)] = 2147483648; w[_lia_idx(5)] = 0; w[_lia_idx(6)] = 0; w[_lia_idx(7)] = 0;
  w[_lia_idx(8)] = 0; w[_lia_idx(9)] = 0; w[_lia_idx(10)] = 0; w[_lia_idx(11)] = 0;
  w[_lia_idx(12)] = 0; w[_lia_idx(13)] = 0; w[_lia_idx(14)] = 0; w[_lia_idx(15)] = 640;
  a = m0; b = m1; c = m2; d = m3; e = m4; f = m5; g = m6; h = m7;
  i = 0;
  cur_w = 0;
  t1 = 0;
  t2 = 0;
  while (i < 64) {
    if (i > 15) {
      t1 = (gamma1_32(w[_lia_idx((i - 2) & 15)]) + w[_lia_idx((i - 7) & 15)] + gamma0_32(w[_lia_idx((i - 15) & 15)]) + w[_lia_idx((i - 16) & 15)]) & 4294967295;
      w[_lia_idx(i & 15)] = t1;
    }
    cur_w = w[_lia_idx(i & 15)];
    t1 = (h + sigma1_32(e) + ch32(e, f, g) + sha_k(i) + cur_w) & 4294967295;
    t2 = (sigma0_32(a) + maj32(a, b, c)) & 4294967295;
    h = g; g = f; f = e; e = (d + t1) & 4294967295;
    d = c; c = b; b = a; a = (t1 + t2) & 4294967295;
    i = i + 1;
  }
  h1_0 = (m0 + a) & 4294967295;
  h1_1 = (m1 + b) & 4294967295;
  h1_2 = (m2 + c) & 4294967295;
  h1_3 = (m3 + d) & 4294967295;
  h1_4 = (m4 + e) & 4294967295;
  h1_5 = (m5 + f) & 4294967295;
  h1_6 = (m6 + g) & 4294967295;
  h1_7 = (m7 + h) & 4294967295;
  w[_lia_idx(0)] = h1_0; w[_lia_idx(1)] = h1_1; w[_lia_idx(2)] = h1_2; w[_lia_idx(3)] = h1_3;
  w[_lia_idx(4)] = h1_4; w[_lia_idx(5)] = h1_5; w[_lia_idx(6)] = h1_6; w[_lia_idx(7)] = h1_7;
  w[_lia_idx(8)] = 2147483648; w[_lia_idx(9)] = 0; w[_lia_idx(10)] = 0; w[_lia_idx(11)] = 0;
  w[_lia_idx(12)] = 0; w[_lia_idx(13)] = 0; w[_lia_idx(14)] = 0; w[_lia_idx(15)] = 256;
  a = 1779033703; b = 3144134277; c = 1013904242; d = 2773480762;
  e = 1359893119; f = 2600822924; g = 528734635; h = 1541459225;
  i = 0;
  while (i < 64) {
    if (i > 15) {
      t1 = (gamma1_32(w[_lia_idx((i - 2) & 15)]) + w[_lia_idx((i - 7) & 15)] + gamma0_32(w[_lia_idx((i - 15) & 15)]) + w[_lia_idx((i - 16) & 15)]) & 4294967295;
      w[_lia_idx(i & 15)] = t1;
    }
    cur_w = w[_lia_idx(i & 15)];
    t1 = (h + sigma1_32(e) + ch32(e, f, g) + sha_k(i) + cur_w) & 4294967295;
    t2 = (sigma0_32(a) + maj32(a, b, c)) & 4294967295;
    h = g; g = f; f = e; e = (d + t1) & 4294967295;
    d = c; c = b; b = a; a = (t1 + t2) & 4294967295;
    i = i + 1;
  }
  r0 = (1779033703 + a) & 4294967295;
  r1 = (3144134277 + b) & 4294967295;
  r2 = (1013904242 + c) & 4294967295;
  r3 = (2773480762 + d) & 4294967295;
  r4 = (1359893119 + e) & 4294967295;
  r5 = (2600822924 + f) & 4294967295;
  r6 = (528734635 + g) & 4294967295;
  r7 = (1541459225 + h) & 4294967295;
  
  disp[_lia_idx(0)] = bswap32(r7);
  disp[_lia_idx(1)] = bswap32(r6);
  disp[_lia_idx(2)] = bswap32(r5);
  disp[_lia_idx(3)] = bswap32(r4);
  disp[_lia_idx(4)] = bswap32(r3);
  disp[_lia_idx(5)] = bswap32(r2);
  disp[_lia_idx(6)] = bswap32(r1);
  disp[_lia_idx(7)] = bswap32(r0);
  if (want == 1) {
    n = 0;
    i = 0;
    while (i < 8) {
      if (disp[_lia_idx(i)] != 0) { return (n + clz32(disp[_lia_idx(i)])) ;}
      n = n + 32;
      i = i + 1;
    }
    return 256;
  }
  i = 0;
  tw = 0;
  while (i < 8) {
    tw = nbits_target_word(nbits, i);
    if (disp[_lia_idx(i)] < tw) { return 1 ;}
    if (disp[_lia_idx(i)] > tw) { return 0 ;}
    i = i + 1;
  }
  return 1;

}

pub fn btc_pow_meets_nbits(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64, nbits: i64) i64 {

  return btc_pow_digest_then(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, nbits, 0);

}

pub fn btc_pow_leading_zero_bits(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64) i64 {

  return btc_pow_digest_then(m0, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, 0, 1);

}

pub fn btc_pow_bind(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64, challenge: i64, sel: i64) i64 {

  return btc_sha256d_sel((m0 ^ challenge) & 4294967295, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, sel);

}

pub fn btc_pow_meets_nbits_bound(m0: i64, m1: i64, m2: i64, m3: i64, m4: i64, m5: i64, m6: i64, m7: i64, w0: i64, w1: i64, w2: i64, nonce: i64, nbits: i64, challenge: i64) i64 {

  return btc_pow_meets_nbits((m0 ^ challenge) & 4294967295, m1, m2, m3, m4, m5, m6, m7, w0, w1, w2, nonce, nbits);

}

pub fn btc_genesis_pow_ok(nonce: i64) i64 {

  if (nonce < 0) { return 0 ;}
  return btc_pow_meets_nbits(3163593267, 1666760688, 2429332605, 509201064, 3284719849, 1325466568, 2528216886, 1192884507, 1260281418, 699096905, 4294901789, nonce, 486604799);

}

pub fn btc_genesis_lzb(nonce: i64) i64 {

  if (nonce < 0) { return 0 ;}
  return btc_pow_leading_zero_bits(3163593267, 1666760688, 2429332605, 509201064, 3284719849, 1325466568, 2528216886, 1192884507, 1260281418, 699096905, 4294901789, nonce);

}

pub fn btc_genesis_bind_h7(nonce: i64, challenge: i64) i64 {

  return btc_pow_bind(3163593267, 1666760688, 2429332605, 509201064, 3284719849, 1325466568, 2528216886, 1192884507, 1260281418, 699096905, 4294901789, nonce, challenge, 7);

}

