const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn lk_rol32(word: i64, shift: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = word & 4294967295;
  s = shift & 31;
  return ((_lia_shl(w, s)) | (_lia_shr(w, (32 - s)))) & 4294967295;

}

pub fn lk_ror32(word: i64, shift: i64) i64 {
    var w: i64 = 0;
    var s: i64 = 0;

  w = word & 4294967295;
  s = shift & 31;
  return ((_lia_shr(w, s)) | (_lia_shl(w, (32 - s)))) & 4294967295;

}

pub fn lk_jhash_1word(a_in: i64, initval: i64) i64 {
    var init: i64 = 0;
    var b: i64 = 0;
    var c: i64 = 0;
    var a: i64 = 0;

  init = initval & 4294967295;
  b = (3735928559 + init) & 4294967295;
  c = (3735928559 + init + 4) & 4294967295;
  a = ((a_in & 4294967295) + 3735928559 + init) & 4294967295;

  c = (c  ^  b) - lk_rol32(b, 14);
  c = c & 4294967295;
  a = (a  ^  c) - lk_rol32(c, 11);
  a = a & 4294967295;
  b = (b  ^  a) - lk_rol32(a, 25);
  b = b & 4294967295;
  c = (c  ^  b) - lk_rol32(b, 16);
  c = c & 4294967295;
  a = (a  ^  c) - lk_rol32(c, 4);
  a = a & 4294967295;
  b = (b  ^  a) - lk_rol32(a, 14);
  b = b & 4294967295;
  c = (c  ^  b) - lk_rol32(b, 24);
  return c & 4294967295;

}

pub fn lk_gcd(a_in: i64, b_in: i64) i64 {
    var a: i64 = 0;
    var b: i64 = 0;
    var r: i64 = 0;
    var t: i64 = 0;

  a = a_in & 4294967295;
  b = b_in & 4294967295;
  if (a == 0) { return b ;}
  if (b == 0) { return a ;}

  r = 0;
  while (((a | b) & 1) == 0) {
    a = _lia_shr(a, 1);
    b = _lia_shr(b, 1);
    r = r + 1;
  }

  while ((a & 1) == 0) {
    a = _lia_shr(a, 1);
  }

  while (b != 0) {
    while ((b & 1) == 0) {
      b = _lia_shr(b, 1);
    }
    if (a > b) {
      t = b;
      b = a;
      a = t;
    }
    b = b - a;
  }

  return (_lia_shl(a, r)) & 4294967295;

}

pub fn lk_int_sqrt(x_in: i64) i64 {
    var x: i64 = 0;
    var b: i64 = 0;
    var m: i64 = 0;
    var y: i64 = 0;

  x = x_in & 4294967295;
  if (x <= 1) { return x ;}

  b = 0;
  m = 1073741824;
  y = 0;

  while (m > x) {
    m = _lia_shr(m, 2);
  }

  while (m != 0) {
    b = y + m;
    y = _lia_shr(y, 1);
    if (x >= b) {
      x = x - b;
      y = y + m;
    }
    m = _lia_shr(m, 2);
  }

  return y & 4294967295;

}

pub fn lk_hweight32(w_in: i64) i64 {
    var w: i64 = 0;
    var res: i64 = 0;

  w = w_in & 4294967295;
  res = (w - ((_lia_shr(w, 1)) & 1431655765)) & 4294967295;
  res = ((res & 858993459) + ((_lia_shr(res, 2)) & 858993459)) & 4294967295;
  res = (res + (_lia_shr(res, 4))) & 252645135;
  res = (res + (_lia_shr(res, 8))) & 4294967295;
  return (res + (_lia_shr(res, 16))) & 255;

}

pub fn lk_fls(x_in: i64) i64 {
    var x: i64 = 0;
    var r: i64 = 0;

  x = x_in & 4294967295;
  if (x == 0) { return 0 ;}
  r = 32;
  if ((x & 4294901760) == 0) {
    x = _lia_shl(x, 16);
    r = r - 16;
  }
  if ((x & 4278190080) == 0) {
    x = _lia_shl(x, 8);
    r = r - 8;
  }
  if ((x & 4026531840) == 0) {
    x = _lia_shl(x, 4);
    r = r - 4;
  }
  if ((x & 3221225472) == 0) {
    x = _lia_shl(x, 2);
    r = r - 2;
  }
  if ((x & 2147483648) == 0) {
    x = _lia_shl(x, 1);
    r = r - 1;
  }
  return r;

}

pub fn lin_opt_fls(x_in: i64) i64 {
    var x: i64 = 0;

  x = x_in & 4294967295;
  if (x == 0) { return 0 ;}
  x = x | _lia_shr(x, 1);
  x = x | _lia_shr(x, 2);
  x = x | _lia_shr(x, 4);
  x = x | _lia_shr(x, 8);
  x = x | _lia_shr(x, 16);
  return lk_hweight32(x);

}

pub fn lin_opt_gcd(a_in: i64, b_in: i64) i64 {
    var a: i64 = 0;
    var b: i64 = 0;
    var common_zeros: i64 = 0;
    var t: i64 = 0;

  a = a_in & 4294967295;
  b = b_in & 4294967295;
  if (a == 0) { return b ;}
  if (b == 0) { return a ;}

  // Fast common power of 2 elimination
  common_zeros = 0;
  while (((a | b) & 15) == 0) {
    a = _lia_shr(a, 4);
    b = _lia_shr(b, 4);
    common_zeros = common_zeros + 4;
  }
  while (((a | b) & 1) == 0) {
    a = _lia_shr(a, 1);
    b = _lia_shr(b, 1);
    common_zeros = common_zeros + 1;
  }

  while ((a & 15) == 0) { a = _lia_shr(a, 4); }
  while ((a & 1) == 0) { a = _lia_shr(a, 1); }

  while (b != 0) {
    while ((b & 15) == 0) { b = _lia_shr(b, 4); }
    while ((b & 1) == 0) { b = _lia_shr(b, 1); }
    if (a > b) {
      t = b;
      b = a;
      a = t;
    }
    b = b - a;
  }

  return (_lia_shl(a, common_zeros)) & 4294967295;

}

pub fn test_linux_kernel_vectors() i64 {

  // GCD tests
  if (lk_gcd(1071, 462) != 21) { return 0 ;}
  if (lin_opt_gcd(1071, 462) != 21) { return 0 ;}
  if (lk_gcd(48, 18) != 6) { return 0 ;}
  if (lin_opt_gcd(48, 18) != 6) { return 0 ;}

  // Integer sqrt tests
  if (lk_int_sqrt(0) != 0) { return 0 ;}
  if (lk_int_sqrt(1) != 1) { return 0 ;}
  if (lk_int_sqrt(144) != 12) { return 0 ;}
  if (lk_int_sqrt(1000000) != 1000) { return 0 ;}
  if (lk_int_sqrt(2147483647) != 46340) { return 0 ;}

  // Hamming weight tests
  if (lk_hweight32(0) != 0) { return 0 ;}
  if (lk_hweight32(15) != 4) { return 0 ;}
  if (lk_hweight32(3935318504) != 14) { return 0 ;}

  // FLS (Find Last Set) tests
  if (lk_fls(0) != 0) { return 0 ;}
  if (lk_fls(1) != 1) { return 0 ;}
  if (lk_fls(16) != 5) { return 0 ;}
  if (lk_fls(2147483648) != 32) { return 0 ;}
  if (lin_opt_fls(0) != 0) { return 0 ;}
  if (lin_opt_fls(1) != 1) { return 0 ;}
  if (lin_opt_fls(16) != 5) { return 0 ;}
  if (lin_opt_fls(2147483648) != 32) { return 0 ;}

  // JHash tests
  if (lk_jhash_1word(12345, 0) == 0) { return 0 ;}

  return 1;

}

