const std = @import("std");
const engine = @import("lin_mir_engine.zig");

/// MIR → OpenCL C Automatic Lowerer (LIN-GPU-003)
///
/// Protocol:
///   Takes a scalar MirFunction with the parallel_map pattern:
///     param %0      (element input)
///     <scalar SSA ops>
///     ret %N        (element output)
///   and emits a full OpenCL C kernel:
///     __kernel void <name>(
///         __global const int32_t* input,
///         __global int32_t* output,
///         const int n)
///     { ... }
///
/// Properties:
///   - MIR semantic hash is computed and embedded in the emitted source comment
///   - Output type follows MirFunction.returns
///   - All virtual registers emitted as cl_long (i64) matching MirVm semantics
///   - Final store casts to element type (i32/f64 etc)
///   - Supports: const_val, param, add, sub, mul, and_op, or_op, xor_op,
///               shl_op, ushr_op, shr_op, cmp_eq, cmp_lt, select_op, ret_op

pub const MirToOpenCLLowerer = struct {
    pub const LoweringResult = struct {
        source: []const u8,
        mir_semantic_hash: [32]u8,
        kernel_name: []const u8,

        pub fn deinit(self: LoweringResult, allocator: std.mem.Allocator) void {
            allocator.free(self.source);
        }
    };

    pub fn lower(
        allocator: std.mem.Allocator,
        func: engine.MirFunction,
        kernel_name: []const u8,
    ) !LoweringResult {
        // 1. Compute MIR semantic hash (device-independent, identical to Zig harness)
        var hasher = std.crypto.hash.sha2.Sha256.init(.{});
        hasher.update(func.name);
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                hasher.update(std.mem.asBytes(&inst));
            }
        }
        var mir_hash: [32]u8 = undefined;
        hasher.final(&mir_hash);

        var buf = std.ArrayList(u8).init(allocator);
        const w = buf.writer();

        // 2. Emit header comment with MIR semantic hash
        try w.print(
            \\ /* LIN-GPU-003: Auto-lowered from MIR function '{s}'
            \\  * mir_semantic_hash = sha256:{s}
            \\  * Generated by MirToOpenCLLowerer v1.0.0
            \\  */
            \\
        , .{ func.name, std.fmt.fmtSliceHexLower(&mir_hash) });

        // 3. Emit kernel signature
        // Element type from MirFunction.returns
        const elem_type: []const u8 = switch (func.returns) {
            .f64 => "double",
            .i32 => "int",
            .u32 => "uint",
            .i64, .i1, .u64 => "long",
            .ptr, .v8u32 => "int",
        };

        try w.print(
            \\__kernel void {s}(
            \\    __global const {s}* input,
            \\    __global {s}* output,
            \\    const int n)
            \\{{
            \\    int gid = get_global_id(0);
            \\    if (gid >= n) return;
            \\
        , .{ kernel_name, elem_type, elem_type });

        // 4. Emit virtual register declarations (all as long for MirVm semantics)
        // Count max dst register used
        var max_reg: u32 = 0;
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                if (inst.dst > max_reg) max_reg = inst.dst;
                if (inst.lhs > max_reg and inst.opcode != .br_if and inst.opcode != .br_jmp and inst.opcode != .ret_op) max_reg = inst.lhs;
                if (inst.rhs > max_reg) max_reg = inst.rhs;
            }
        }
        try w.print("    long r[{d}];\n", .{max_reg + 1});

        // 5. Emit instructions (single basic block path; parallel_map kernel is always entry-only)
        //    For the parallel_map pattern: param is the element load from input[gid]
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                switch (inst.opcode) {
                    .param => {
                        // param %dst = input[gid] cast to long
                        try w.print("    r[{d}] = (long)input[gid];\n", .{inst.dst});
                    },
                    .const_val => {
                        try w.print("    r[{d}] = {d}L;\n", .{ inst.dst, inst.imm });
                    },
                    .add => {
                        try w.print("    r[{d}] = r[{d}] + r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .sub => {
                        try w.print("    r[{d}] = r[{d}] - r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .mul => {
                        try w.print("    r[{d}] = r[{d}] * r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .and_op => {
                        try w.print("    r[{d}] = r[{d}] & r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .or_op => {
                        try w.print("    r[{d}] = r[{d}] | r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .xor_op => {
                        try w.print("    r[{d}] = r[{d}] ^ r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .shl_op => {
                        try w.print("    r[{d}] = r[{d}] << (r[{d}] & 63L);\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .ushr_op => {
                        try w.print("    r[{d}] = (long)((ulong)r[{d}] >> (r[{d}] & 63L));\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .shr_op => {
                        try w.print("    r[{d}] = r[{d}] >> (r[{d}] & 63L);\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .cmp_eq => {
                        try w.print("    r[{d}] = (r[{d}] == r[{d}]) ? 1L : 0L;\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .cmp_lt => {
                        try w.print("    r[{d}] = (r[{d}] < r[{d}]) ? 1L : 0L;\n", .{ inst.dst, inst.lhs, inst.rhs });
                    },
                    .select_op => {
                        try w.print("    r[{d}] = (r[{d}] != 0L) ? r[{d}] : r[{d}];\n", .{ inst.dst, inst.lhs, inst.rhs, inst.extra });
                    },
                    .ret_op => {
                        // Store result back to output[gid] with appropriate cast
                        try w.print("    output[gid] = ({s})r[{d}];\n", .{ elem_type, inst.lhs });
                    },
                    .phi_op, .br_jmp, .br_if,
                    .parallel_map, .parallel_reduce => {},
                }
            }
        }

        try w.print("}}\n", .{});

        return LoweringResult{
            .source = try buf.toOwnedSlice(),
            .mir_semantic_hash = mir_hash,
            .kernel_name = kernel_name,
        };
    }
};
