const std = @import("std");
const engine = @import("lin_mir_engine.zig");

/// MIR → OpenCL C Automatic Lowerer (LIN-GPU-003/004)
///
/// Hash separation:
///   semantic_hash  = SHA256(MIR function name + instruction bytes)
///                    device-independent, same for CPU and GPU targets
///   lowering_hash  = SHA256("LIN:GPU_LOWERING:1.0.0" || target || semantic_hash_bytes)
///                    target-specific, identifies this ABI/memory model/numeric model

pub const GpuTarget = struct {
    name: []const u8,          // e.g. "opencl_c_2.0"
    numeric_model: []const u8, // e.g. "ieee754_strict" or "opencl_relaxed"
    memory_model: []const u8,  // e.g. "global_int32"
};

pub const OPENCL_ROCM_TARGET = GpuTarget{
    .name          = "opencl_c_2.0",
    .numeric_model = "opencl_relaxed_i32",
    .memory_model  = "global_contiguous",
};

pub const MirToOpenCLLowerer = struct {
    pub const LoweringResult = struct {
        source: []const u8,
        mir_semantic_hash: [32]u8,
        lowering_hash: [32]u8,
        kernel_name: []const u8,
        target: GpuTarget,

        pub fn deinit(self: LoweringResult, allocator: std.mem.Allocator) void {
            allocator.free(self.source);
        }
    };
    pub fn lower(
        allocator: std.mem.Allocator,
        func: engine.MirFunction,
        kernel_name: []const u8,
        target: GpuTarget,
    ) !LoweringResult {
        var hasher = std.crypto.hash.sha2.Sha256.init(.{});
        hasher.update(func.name);
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                hasher.update(std.mem.asBytes(&inst.opcode));
                hasher.update(std.mem.asBytes(&inst.ty));
                hasher.update(std.mem.asBytes(&inst.dst));
                hasher.update(std.mem.asBytes(&inst.imm));
                hasher.update(std.mem.asBytes(&inst.lhs));
                hasher.update(std.mem.asBytes(&inst.rhs));
                hasher.update(std.mem.asBytes(&inst.extra));
                hasher.update(std.mem.asBytes(&inst.target_block));
                hasher.update(std.mem.asBytes(&inst.target_block_else));
                hasher.update(std.mem.asBytes(&inst.phi_incoming_blocks));
                hasher.update(std.mem.asBytes(&inst.phi_incoming_vals));
                hasher.update(std.mem.asBytes(&inst.phi_count));
            }
        }
        var mir_hash: [32]u8 = undefined;
        hasher.final(&mir_hash);

        // 2. Compute lowering_hash = SHA256("LIN:GPU_LOWERING:1.0.0" || target.name || mir_hash_bytes)
        //    Target-specific: identifies ABI + memory model + numeric model + semantic origin
        var lhasher = std.crypto.hash.sha2.Sha256.init(.{});
        lhasher.update("LIN:GPU_LOWERING:1.0.0");
        lhasher.update(target.name);
        lhasher.update(target.numeric_model);
        lhasher.update(target.memory_model);
        lhasher.update(&mir_hash);
        var lowering_hash: [32]u8 = undefined;
        lhasher.final(&lowering_hash);

        var buf = std.ArrayList(u8).init(allocator);
        const w = buf.writer();

        // 3. Emit header comment with both hashes
        try w.print(
            \\ /* LIN-GPU-004: Auto-lowered from MIR function '{s}'
            \\  * mir_semantic_hash = sha256:{s}
            \\  * lowering_hash     = sha256:{s}
            \\  * target            = {s} | {s} | {s}
            \\  * Generated by MirToOpenCLLowerer v1.1.0
            \\  */
            \\
        , .{
            func.name,
            std.fmt.fmtSliceHexLower(&mir_hash),
            std.fmt.fmtSliceHexLower(&lowering_hash),
            target.name, target.numeric_model, target.memory_model,
        });

        // 4. Emit kernel signature; element type from MirFunction.returns
        const elem_type: []const u8 = switch (func.returns) {
            .f64  => "double",
            .i32  => "int",
            .u32  => "uint",
            .i64, .i1, .u64 => "long",
            .ptr, .v8u32    => "int",
        };

        try w.print(
            \\__kernel void {s}(
            \\    __global const {s}* input,
            \\    __global {s}* output,
            \\    const int n)
            \\{{
            \\    int gid = get_global_id(0);
            \\    if (gid >= n) return;
            \\
        , .{ kernel_name, elem_type, elem_type });

        // 5. Emit virtual register declarations (all cl_long for MirVm numeric fidelity)
        var max_reg: u32 = 0;
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                if (inst.dst > max_reg) max_reg = inst.dst;
                if (inst.lhs > max_reg and inst.opcode != .br_if and
                    inst.opcode != .br_jmp and inst.opcode != .ret_op)
                    max_reg = inst.lhs;
                if (inst.rhs > max_reg) max_reg = inst.rhs;
            }
        }
        try w.print("    long r[{d}];\n", .{max_reg + 1});

        // 6. Emit instructions
        for (func.blocks) |block| {
            for (block.instructions) |inst| {
                switch (inst.opcode) {
                    .param     => try w.print("    r[{d}] = (long)input[gid];\n",                      .{inst.dst}),
                    .const_val => try w.print("    r[{d}] = {d}L;\n",                                  .{ inst.dst, inst.imm }),
                    .add       => try w.print("    r[{d}] = r[{d}] + r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .sub       => try w.print("    r[{d}] = r[{d}] - r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .mul       => try w.print("    r[{d}] = r[{d}] * r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .and_op    => try w.print("    r[{d}] = r[{d}] & r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .or_op     => try w.print("    r[{d}] = r[{d}] | r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .xor_op    => try w.print("    r[{d}] = r[{d}] ^ r[{d}];\n",                       .{ inst.dst, inst.lhs, inst.rhs }),
                    .shl_op    => try w.print("    r[{d}] = r[{d}] << (r[{d}] & 63L);\n",              .{ inst.dst, inst.lhs, inst.rhs }),
                    .ushr_op   => try w.print("    r[{d}] = (long)((ulong)r[{d}] >> (r[{d}] & 63L));\n", .{ inst.dst, inst.lhs, inst.rhs }),
                    .shr_op    => try w.print("    r[{d}] = r[{d}] >> (r[{d}] & 63L);\n",              .{ inst.dst, inst.lhs, inst.rhs }),
                    .cmp_eq    => try w.print("    r[{d}] = (r[{d}] == r[{d}]) ? 1L : 0L;\n",          .{ inst.dst, inst.lhs, inst.rhs }),
                    .cmp_lt    => try w.print("    r[{d}] = (r[{d}] < r[{d}]) ? 1L : 0L;\n",           .{ inst.dst, inst.lhs, inst.rhs }),
                    .select_op => try w.print("    r[{d}] = (r[{d}] != 0L) ? r[{d}] : r[{d}];\n",     .{ inst.dst, inst.lhs, inst.rhs, inst.extra }),
                    .ret_op    => try w.print("    output[gid] = ({s})r[{d}];\n",                       .{ elem_type, inst.lhs }),
                    .phi_op, .br_jmp, .br_if, .parallel_map, .parallel_reduce => {},
                }
            }
        }

        try w.print("}}\n", .{});

        return LoweringResult{
            .source           = try buf.toOwnedSlice(),
            .mir_semantic_hash = mir_hash,
            .lowering_hash    = lowering_hash,
            .kernel_name      = kernel_name,
            .target           = target,
        };
    }
};
