const std = @import("std");
pub var LIA_ALLOC: std.mem.Allocator = undefined;
fn _lia_str(x: anytype) []const u8 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice and p.child == u8) return x;
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| { if (a.child == u8) return x[0..]; },
                    else => {},
                }
            }
        },
        .Bool => return if (x) "true" else "false",
        .Int, .ComptimeInt => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        .Float, .ComptimeFloat => return std.fmt.allocPrint(LIA_ALLOC, "{d}", .{x}) catch "",
        else => {},
    }
    return "";
}
pub fn _lia_cat(a: anytype, b: anytype) []const u8 {
    return std.mem.concat(LIA_ALLOC, u8, &.{ _lia_str(a), _lia_str(b) }) catch "";
}
fn _lia_char_at(s: []const u8, i: i64) []const u8 {
    if (i < 0) return "";
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return s[idx .. idx + 1];
    return "";
}
fn _lia_char_code_at(s: []const u8, i: i64) i64 {
    if (i < 0) return 0;
    const idx = @as(usize, @intCast(i));
    if (idx < s.len) return @as(i64, s[idx]);
    return 0;
}
fn _lia_from_code(c: i64) []const u8 {
    var buf: [1]u8 = .{@as(u8, @truncate(@as(u64, @intCast(c))))};
    return std.fmt.allocPrint(LIA_ALLOC, "{s}", .{buf[0..]}) catch "";
}
fn _lia_slice(s: []const u8, a: i64, b: i64) []const u8 {
    if (a < 0 or b < 0) return "";
    var start = @as(usize, @intCast(a));
    var end = @as(usize, @intCast(b));
    if (start > s.len) start = s.len;
    if (end > s.len) end = s.len;
    if (start >= end) return "";
    return s[start..end];
}
fn _lia_idx(a: i64) usize {
    return @as(usize, @intCast(a));
}
fn _lia_shl(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    const ua: u64 = @bitCast(a);
    return @bitCast(ua << shift);
}
fn _lia_shr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return a >> shift;
}
fn _lia_ushr(a: i64, b: i64) i64 {
    if (b < 0 or b >= 64) return 0;
    const shift: u6 = @as(u6, @truncate(@as(u64, @intCast(b))));
    return @bitCast(@as(u64, @bitCast(a)) >> shift);
}
fn _lia_mod(a: i64, b: i64) i64 {
    if (b == 0) return 0;
    return @rem(a, b);
}
fn _lia_len(x: anytype) i64 {
    const T = @TypeOf(x);
    switch (@typeInfo(T)) {
        .Pointer => |p| {
            if (p.size == .Slice) return @as(i64, @intCast(x.len));
            if (p.size == .One) {
                switch (@typeInfo(p.child)) {
                    .Array => |a| return @as(i64, @intCast(a.len)),
                    else => {},
                }
            }
        },
        .Array => |a| return @as(i64, @intCast(a.len)),
        else => {},
    }
    return 0;
}// generated by LIN Zig bootstrap
pub fn mir_type_name(t: i64) []const u8 {

  if (t == 1) { return "i1" ;}
  if (t == 2) { return "i32" ;}
  if (t == 3) { return "i64" ;}
  if (t == 4) { return "f64" ;}
  if (t == 5) { return "ptr" ;}
  if (t == 6) { return "v8u32" ;}
  return "unknown";

}

pub fn mir_ssa_eval_binop(op: i64, a: i64, b: i64) i64 {

  if (op == 3) { return (a + b) ;}
  if (op == 4) { return (a - b) ;}
  if (op == 5) { return (a * b) ;}
  if (op == 6) { return (a & b) ;}
  if (op == 7) { return (a | b) ;}
  if (op == 8) { return (a ^ b) ;}
  if (op == 9) { return (_lia_shl(a, b & 63)) ;}
  if (op == 10) { return (_lia_ushr(a, b & 63)) ;}
  if (op == 11) { return (_lia_shr(a, b & 63)) ;}
  if (op == 12) { if (a == b) { return 1 ;} return 0 ;}
  if (op == 13) { if (a < b) { return 1 ;} return 0 ;}
  return 0;

}

pub fn mir_ssa_select(cond: i64, val_true: i64, val_false: i64) i64 {

  if (cond != 0) { return val_true ;}
  return val_false;

}

pub fn test_mir_ssa() i64 {
    var v0: i64 = 0;
    var v1: i64 = 0;
    var v2: i64 = 0;
    var v3: i64 = 0;
    var v4: i64 = 0;

  // Test %0 = const.i64 42
  // %1 = const.i64 100
  // %2 = add.i64 %0, %1 -> 142
  // %3 = cmp.lt.i64 %0, %1 -> 1 (true)
  // %4 = select.i64 %3, %2, 0 -> 142
  v0 = 42;
  v1 = 100;
  v2 = mir_ssa_eval_binop(3, v0, v1);
  v3 = mir_ssa_eval_binop(13, v0, v1);
  v4 = mir_ssa_select(v3, v2, 0);

  if (v2 != 142) { return 0 ;}
  if (v3 != 1) { return 0 ;}
  if (v4 != 142) { return 0 ;}
  return 1;

}

