import { renderBody, renderExpr, fnParamsText } from './render_core.mjs';
import { collectAssignedIds, firstUseIsRead, inferEffect } from './effects.mjs';

export function renderProgramJs(prog, opts = {}) {
  const parts = [];
  parts.push(`/* generated by lin-rewrite ${opts.version || '2.0.0'} */`);
  if (opts.prelude) parts.push(String(opts.prelude).trim());
  if (prog.consts) {
    const obj = Object.entries(prog.consts)
      .map(([k, v]) => `${JSON.stringify(k)}:${v}`)
      .join(',');
    parts.push(`var $K={${obj}};`);
  }
  for (const mod of prog.modules || []) {
    parts.push(`const ${mod.name} = ${renderModuleObj(mod)};`);
  }
  for (const u of prog.uses || []) {
    for (const sym of u.symbols) {
      parts.push(`const ${sym} = ${u.module}.${sym};`);
    }
  }
  const allFns = prog.fns;
  const effects = new Map();
  for (const fn of allFns) {
    effects.set(fn.name, inferEffect(fnTextStub(fn), allFns.map(fnTextStub)));
  }
  for (const fn of allFns) {
    fn.effect = effects.get(fn.name);
    const bodyText = renderBody(fn.body);
    const params = new Set((fn.params || []).map((p) => p.name));
    const bareIds = collectBareStmtIds(bodyText);
    const cleaned = stripBareIdStmts(bodyText);
    const assigned = collectAssignedIds(cleaned);
    const selfDeclared = new Set();
    for (const id of [...assigned, ...bareIds]) {
      if (new RegExp(`\\b(?:const|let|var)\\s+${id}\\b`).test(cleaned)) selfDeclared.add(id);
    }
    const locals = [...new Set([...assigned, ...bareIds])].filter((id) => {
      if (params.has(id)) return false;
      if (selfDeclared.has(id)) return false;
      if (bareIds.has(id)) return true;
      if (firstUseIsRead(cleaned, id)) return false;
      return true;
    });
    const decl = locals.length ? `var ${locals.join(',')};` : '';
    parts.push(`/* effect:${fn.effect} */function ${fn.name}(${fnParamsText(fn)}){${decl}${bodyText}}`);
  }
  if (opts.epilogue) {
    parts.push(String(opts.epilogue).trim());
  } else {
    const rawEx = prog.exports.length ? prog.exports : prog.fns.map((f) => f.name);
    const ex = rawEx.map((e) => {
      if (e.includes(' as ')) {
        const [src, alias] = e.split(/\s+as\s+/).map((s) => s.trim());
        return `${alias}:${src}`;
      }
      return e;
    });
    if (opts.exportMode === 'multiple') {
      parts.push(`module.exports={${ex.join(',')}};`);
    } else if (opts.exportMode === 'single' && ex[0]) {
      parts.push(`module.exports=${ex[0]};`);
    } else if (ex.length === 1 && !rawEx[0].includes(' as ')) {
      parts.push(`module.exports=${ex[0]};`);
    } else {
      parts.push(`module.exports={${ex.join(',')}};`);
    }
  }
  return parts.join('\n');
}

function fnTextStub(fn) {
  if (!fn.__text) {
    fn.__text = {
      name: fn.name,
      params: (fn.params || []).map((p) => p.name),
      get body() {
        if (typeof fn.rawBody === 'string') return fn.rawBody;
        return renderBody(fn.body || []);
      },
      effect: fn.effect,
    };
  }
  return fn.__text;
}

const BARE_ID_STMT_RE = /(^|[;{}])\s*([A-Za-z_$][\w$]*)\s*;/;

const JS_KEYWORDS = new Set([
  'break', 'continue', 'return', 'throw', 'function', 'var', 'let', 'const',
  'if', 'else', 'for', 'while', 'do', 'switch', 'case', 'default', 'new',
  'typeof', 'delete', 'void', 'in', 'of', 'instanceof', 'true', 'false',
  'null', 'undefined', 'this', 'try', 'catch', 'finally', 'class', 'extends',
]);

export function collectBareStmtIds(bodyText) {
  const ids = new Set();
  let s = String(bodyText || '');
  for (let guard = 0; guard < 50; guard++) {
    const re = new RegExp(BARE_ID_STMT_RE.source, 'g');
    const m = re.exec(s);
    if (!m) break;
    const id = m[2];
    if (/^[A-Za-z_$][\w$]*$/.test(id) && !JS_KEYWORDS.has(id)) ids.add(id);
    s = s.slice(0, m.index) + m[1] + '\u0000' + s.slice(m.index + m[0].length);
  }
  return ids;
}

export function stripBareIdStmts(bodyText) {
  let s = String(bodyText || '');
  for (let guard = 0; guard < 200; guard++) {
    const re = new RegExp(BARE_ID_STMT_RE.source, '');
    const m = re.exec(s);
    if (!m) break;
    s = s.slice(0, m.index) + m[1] + s.slice(m.index + m[0].length);
  }
  return s;
}

function renderModuleObj(mod) {
  const modFns = [];
  for (const fn of mod.program.fns || []) {
    modFns.push(`${fn.name}: function(${fnParamsText(fn)}){${renderBody(fn.body)}}`);
  }
  for (const inner of mod.program.modules || []) {
    modFns.push(`${inner.name}: ${renderModuleObj(inner)}`);
  }
  return `{\n  ${modFns.join(',\n  ')}\n}`;
}

export { renderExpr };
